query ArtifactRegistryGithubRepos($team: Slug!) {
	team(slug: $team) {
		artifactRegistryAllowedGithubRepos(first: 10) @paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				startCursor
				endCursor
			}
			edges {
				node {
					id
					name
				}
			}
		}
	}
}
