// Code generated by sqlc. DO NOT EDIT.
// source: gcpresources.sql

package grpcgcpresourcessql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

const getTeamFolder = `-- name: GetTeamFolder :one
SELECT
    gcp_team_folders.team_slug, gcp_team_folders.env, gcp_team_folders.folder_id
FROM
	gcp_team_folders
WHERE
	team_slug = $1
	AND env = $2
`

type GetTeamFolderParams struct {
	TeamSlug slug.Slug
	Env      string
}

type GetTeamFolderRow struct {
	GcpTeamFolder GcpTeamFolder
}

func (q *Queries) GetTeamFolder(ctx context.Context, arg GetTeamFolderParams) (*GetTeamFolderRow, error) {
	row := q.db.QueryRow(ctx, getTeamFolder, arg.TeamSlug, arg.Env)
	var i GetTeamFolderRow
	err := row.Scan(&i.GcpTeamFolder.TeamSlug, &i.GcpTeamFolder.Env, &i.GcpTeamFolder.FolderID)
	return &i, err
}

const listTeamFolders = `-- name: ListTeamFolders :many
SELECT
    gcp_team_folders.team_slug, gcp_team_folders.env, gcp_team_folders.folder_id
FROM
    gcp_team_folders
WHERE
    team_slug = $1
ORDER BY
    env
`

type ListTeamFoldersRow struct {
	GcpTeamFolder GcpTeamFolder
}

func (q *Queries) ListTeamFolders(ctx context.Context, teamSlug slug.Slug) ([]*ListTeamFoldersRow, error) {
	rows, err := q.db.Query(ctx, listTeamFolders, teamSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListTeamFoldersRow{}
	for rows.Next() {
		var i ListTeamFoldersRow
		if err := rows.Scan(&i.GcpTeamFolder.TeamSlug, &i.GcpTeamFolder.Env, &i.GcpTeamFolder.FolderID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTeamFolder = `-- name: UpsertTeamFolder :exec
INSERT INTO
	gcp_team_folders (team_slug, env, folder_id)
VALUES
	($1, $2, $3)
ON CONFLICT (team_slug, env) DO UPDATE
SET
	folder_id = EXCLUDED.folder_id
`

type UpsertTeamFolderParams struct {
	TeamSlug slug.Slug
	Env      string
	FolderID string
}

func (q *Queries) UpsertTeamFolder(ctx context.Context, arg UpsertTeamFolderParams) error {
	_, err := q.db.Exec(ctx, upsertTeamFolder, arg.TeamSlug, arg.Env, arg.FolderID)
	return err
}
