// Code generated by sqlc. DO NOT EDIT.
// source: gcpresources.sql

package grpcgcpresourcessql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

const deleteTeamFolders = `-- name: DeleteTeamFolders :exec
DELETE FROM gcp_team_folders
WHERE
	team_slug = $1
`

func (q *Queries) DeleteTeamFolders(ctx context.Context, teamSlug slug.Slug) error {
	_, err := q.db.Exec(ctx, deleteTeamFolders, teamSlug)
	return err
}

const getTeamFolder = `-- name: GetTeamFolder :one
SELECT
	team_slug,
	env,
	folder_id
FROM
	gcp_team_folders
WHERE
	team_slug = $1
	AND env = $2
`

type GetTeamFolderParams struct {
	TeamSlug slug.Slug
	Env      string
}

func (q *Queries) GetTeamFolder(ctx context.Context, arg GetTeamFolderParams) (*GcpTeamFolder, error) {
	row := q.db.QueryRow(ctx, getTeamFolder, arg.TeamSlug, arg.Env)
	var i GcpTeamFolder
	err := row.Scan(&i.TeamSlug, &i.Env, &i.FolderID)
	return &i, err
}

const upsertTeamFolder = `-- name: UpsertTeamFolder :exec
INSERT INTO
	gcp_team_folders (team_slug, env, folder_id)
VALUES
	($1, $2, $3)
ON CONFLICT (team_slug, env) DO UPDATE
SET
	folder_id = EXCLUDED.folder_id
`

type UpsertTeamFolderParams struct {
	TeamSlug slug.Slug
	Env      string
	FolderID string
}

func (q *Queries) UpsertTeamFolder(ctx context.Context, arg UpsertTeamFolderParams) error {
	_, err := q.db.Exec(ctx, upsertTeamFolder, arg.TeamSlug, arg.Env, arg.FolderID)
	return err
}
