// Code generated by sqlc. DO NOT EDIT.

package grpcgcpresourcessql

import (
	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

type GcpTeamFolder struct {
	TeamSlug slug.Slug
	Env      string
	FolderID string
}
