// Code generated by sqlc. DO NOT EDIT.

package grpcgcpresourcessql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

type Querier interface {
	GetTeamFolder(ctx context.Context, arg GetTeamFolderParams) (*GetTeamFolderRow, error)
	ListTeamFolders(ctx context.Context, teamSlug slug.Slug) ([]*ListTeamFoldersRow, error)
	UpsertTeamFolder(ctx context.Context, arg UpsertTeamFolderParams) error
}

var _ Querier = (*Queries)(nil)
