// Code generated by sqlc. DO NOT EDIT.

package grpcgcpresourcessql

import (
	"context"
)

type Querier interface {
	GetTeamFolder(ctx context.Context, arg GetTeamFolderParams) (*GcpTeamFolder, error)
	UpsertTeamFolder(ctx context.Context, arg UpsertTeamFolderParams) error
}

var _ Querier = (*Queries)(nil)
