// Code generated by metago; DO NOT EDIT.

package group

import (
	"fmt"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/model"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/pagination"
	"io"
	"slices"
	"strconv"
	"strings"
)

type (
	GroupConnection = pagination.Connection[*Group]
	GroupEdge       = pagination.Edge[*Group]
)

func (Group) IsNode()           {}
func (Group) IsSearchNode()     {}
func (Group) IsActivityLogger() {}

type GroupOrder struct {
	Field     GroupOrderField      `json:"field"`
	Direction model.OrderDirection `json:"direction"`
}

func (o *GroupOrder) String() string {
	if o == nil {
		return ""
	}

	return strings.ToLower(o.Field.String() + ":" + o.Direction.String())
}

type GroupOrderField string

const (
	GroupOrderFieldName     GroupOrderField = "NAME"
	GroupOrderFieldTeam     GroupOrderField = "TEAM"
	GroupOrderFieldCategory GroupOrderField = "CATEGORY"
)

var AllGroupOrderFields = []GroupOrderField{
	GroupOrderFieldName,
	GroupOrderFieldTeam,
	GroupOrderFieldCategory,
}

func (e GroupOrderField) IsValid() bool {
	return slices.Contains(AllGroupOrderFields, e)
}

func (e GroupOrderField) String() string {
	return string(e)
}

func (e *GroupOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GroupOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GroupOrderField", str)
	}
	return nil
}

func (e GroupOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type (
	GroupMemberConnection = pagination.Connection[*GroupMember]
	GroupMemberEdge       = pagination.Edge[*GroupMember]
)
