#!/usr/bin/env sh
#MISE description="Test all code"
#USAGE flag "--coverage" help="Generate a coverage profile"

set -e

# shellcheck disable=SC2154
if [ "$usage_coverage" = "true" ]; then
	rm -f hack/coverprofile.txt
	GOTOOLCHAIN=go1.25.5+auto go test \
	  -coverprofile=hack/coverprofile.txt \
	  -coverpkg github.com/statisticsnorway/dapla-api-reconcilers/... \
	  -v \
	  -race \
	  ./...
else
	go test -cover -race ./...
fi
