// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: artifactregistry.proto

package protoapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArtifactRegistry_GetArtifactRegistryRepo_FullMethodName          = "/dapla.api.protobuf.ArtifactRegistry/GetArtifactRegistryRepo"
	ArtifactRegistry_ListArtifactRegistryReposForTeam_FullMethodName = "/dapla.api.protobuf.ArtifactRegistry/ListArtifactRegistryReposForTeam"
)

// ArtifactRegistryClient is the client API for ArtifactRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtifactRegistryClient interface {
	GetArtifactRegistryRepo(ctx context.Context, in *GetArtifactRegistryRepoRequest, opts ...grpc.CallOption) (*GetArtifactRegistryRepoResponse, error)
	ListArtifactRegistryReposForTeam(ctx context.Context, in *ListArtifactRegistryReposForTeamRequest, opts ...grpc.CallOption) (*ListArtifactRegistryReposForTeamResponse, error)
}

type artifactRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewArtifactRegistryClient(cc grpc.ClientConnInterface) ArtifactRegistryClient {
	return &artifactRegistryClient{cc}
}

func (c *artifactRegistryClient) GetArtifactRegistryRepo(ctx context.Context, in *GetArtifactRegistryRepoRequest, opts ...grpc.CallOption) (*GetArtifactRegistryRepoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtifactRegistryRepoResponse)
	err := c.cc.Invoke(ctx, ArtifactRegistry_GetArtifactRegistryRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactRegistryClient) ListArtifactRegistryReposForTeam(ctx context.Context, in *ListArtifactRegistryReposForTeamRequest, opts ...grpc.CallOption) (*ListArtifactRegistryReposForTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArtifactRegistryReposForTeamResponse)
	err := c.cc.Invoke(ctx, ArtifactRegistry_ListArtifactRegistryReposForTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtifactRegistryServer is the server API for ArtifactRegistry service.
// All implementations must embed UnimplementedArtifactRegistryServer
// for forward compatibility.
type ArtifactRegistryServer interface {
	GetArtifactRegistryRepo(context.Context, *GetArtifactRegistryRepoRequest) (*GetArtifactRegistryRepoResponse, error)
	ListArtifactRegistryReposForTeam(context.Context, *ListArtifactRegistryReposForTeamRequest) (*ListArtifactRegistryReposForTeamResponse, error)
	mustEmbedUnimplementedArtifactRegistryServer()
}

// UnimplementedArtifactRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtifactRegistryServer struct{}

func (UnimplementedArtifactRegistryServer) GetArtifactRegistryRepo(context.Context, *GetArtifactRegistryRepoRequest) (*GetArtifactRegistryRepoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtifactRegistryRepo not implemented")
}
func (UnimplementedArtifactRegistryServer) ListArtifactRegistryReposForTeam(context.Context, *ListArtifactRegistryReposForTeamRequest) (*ListArtifactRegistryReposForTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArtifactRegistryReposForTeam not implemented")
}
func (UnimplementedArtifactRegistryServer) mustEmbedUnimplementedArtifactRegistryServer() {}
func (UnimplementedArtifactRegistryServer) testEmbeddedByValue()                          {}

// UnsafeArtifactRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtifactRegistryServer will
// result in compilation errors.
type UnsafeArtifactRegistryServer interface {
	mustEmbedUnimplementedArtifactRegistryServer()
}

func RegisterArtifactRegistryServer(s grpc.ServiceRegistrar, srv ArtifactRegistryServer) {
	// If the following call panics, it indicates UnimplementedArtifactRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtifactRegistry_ServiceDesc, srv)
}

func _ArtifactRegistry_GetArtifactRegistryRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactRegistryRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactRegistryServer).GetArtifactRegistryRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactRegistry_GetArtifactRegistryRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactRegistryServer).GetArtifactRegistryRepo(ctx, req.(*GetArtifactRegistryRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactRegistry_ListArtifactRegistryReposForTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArtifactRegistryReposForTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactRegistryServer).ListArtifactRegistryReposForTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactRegistry_ListArtifactRegistryReposForTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactRegistryServer).ListArtifactRegistryReposForTeam(ctx, req.(*ListArtifactRegistryReposForTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtifactRegistry_ServiceDesc is the grpc.ServiceDesc for ArtifactRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtifactRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapla.api.protobuf.ArtifactRegistry",
	HandlerType: (*ArtifactRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArtifactRegistryRepo",
			Handler:    _ArtifactRegistry_GetArtifactRegistryRepo_Handler,
		},
		{
			MethodName: "ListArtifactRegistryReposForTeam",
			Handler:    _ArtifactRegistry_ListArtifactRegistryReposForTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "artifactregistry.proto",
}
