// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: artifactregistry.proto

//go:build protoopaque

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactRegistryRepo struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamSlug  string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3"`
	xxx_hidden_Format    string                 `protobuf:"bytes,2,opt,name=format,proto3"`
	xxx_hidden_SizeBytes int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ArtifactRegistryRepo) Reset() {
	*x = ArtifactRegistryRepo{}
	mi := &file_artifactregistry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRegistryRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRegistryRepo) ProtoMessage() {}

func (x *ArtifactRegistryRepo) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ArtifactRegistryRepo) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *ArtifactRegistryRepo) GetFormat() string {
	if x != nil {
		return x.xxx_hidden_Format
	}
	return ""
}

func (x *ArtifactRegistryRepo) GetSizeBytes() int64 {
	if x != nil {
		return x.xxx_hidden_SizeBytes
	}
	return 0
}

func (x *ArtifactRegistryRepo) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

func (x *ArtifactRegistryRepo) SetFormat(v string) {
	x.xxx_hidden_Format = v
}

func (x *ArtifactRegistryRepo) SetSizeBytes(v int64) {
	x.xxx_hidden_SizeBytes = v
}

type ArtifactRegistryRepo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug  string
	Format    string
	SizeBytes int64
}

func (b0 ArtifactRegistryRepo_builder) Build() *ArtifactRegistryRepo {
	m0 := &ArtifactRegistryRepo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamSlug = b.TeamSlug
	x.xxx_hidden_Format = b.Format
	x.xxx_hidden_SizeBytes = b.SizeBytes
	return m0
}

type GetArtifactRegistryRepoResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Repo *ArtifactRegistryRepo  `protobuf:"bytes,1,opt,name=repo,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetArtifactRegistryRepoResponse) Reset() {
	*x = GetArtifactRegistryRepoResponse{}
	mi := &file_artifactregistry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRegistryRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRegistryRepoResponse) ProtoMessage() {}

func (x *GetArtifactRegistryRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetArtifactRegistryRepoResponse) GetRepo() *ArtifactRegistryRepo {
	if x != nil {
		return x.xxx_hidden_Repo
	}
	return nil
}

func (x *GetArtifactRegistryRepoResponse) SetRepo(v *ArtifactRegistryRepo) {
	x.xxx_hidden_Repo = v
}

func (x *GetArtifactRegistryRepoResponse) HasRepo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Repo != nil
}

func (x *GetArtifactRegistryRepoResponse) ClearRepo() {
	x.xxx_hidden_Repo = nil
}

type GetArtifactRegistryRepoResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Repo *ArtifactRegistryRepo
}

func (b0 GetArtifactRegistryRepoResponse_builder) Build() *GetArtifactRegistryRepoResponse {
	m0 := &GetArtifactRegistryRepoResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Repo = b.Repo
	return m0
}

type GetArtifactRegistryRepoRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamSlug string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3"`
	xxx_hidden_Format   string                 `protobuf:"bytes,2,opt,name=format,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetArtifactRegistryRepoRequest) Reset() {
	*x = GetArtifactRegistryRepoRequest{}
	mi := &file_artifactregistry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRegistryRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRegistryRepoRequest) ProtoMessage() {}

func (x *GetArtifactRegistryRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetArtifactRegistryRepoRequest) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *GetArtifactRegistryRepoRequest) GetFormat() string {
	if x != nil {
		return x.xxx_hidden_Format
	}
	return ""
}

func (x *GetArtifactRegistryRepoRequest) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

func (x *GetArtifactRegistryRepoRequest) SetFormat(v string) {
	x.xxx_hidden_Format = v
}

type GetArtifactRegistryRepoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug string
	Format   string
}

func (b0 GetArtifactRegistryRepoRequest_builder) Build() *GetArtifactRegistryRepoRequest {
	m0 := &GetArtifactRegistryRepoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamSlug = b.TeamSlug
	x.xxx_hidden_Format = b.Format
	return m0
}

type ListArtifactRegistryReposForTeamRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamSlug string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3"`
	xxx_hidden_Limit    int64                  `protobuf:"varint,2,opt,name=limit,proto3"`
	xxx_hidden_Offset   int64                  `protobuf:"varint,3,opt,name=offset,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListArtifactRegistryReposForTeamRequest) Reset() {
	*x = ListArtifactRegistryReposForTeamRequest{}
	mi := &file_artifactregistry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactRegistryReposForTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactRegistryReposForTeamRequest) ProtoMessage() {}

func (x *ListArtifactRegistryReposForTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListArtifactRegistryReposForTeamRequest) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *ListArtifactRegistryReposForTeamRequest) GetLimit() int64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListArtifactRegistryReposForTeamRequest) GetOffset() int64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListArtifactRegistryReposForTeamRequest) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

func (x *ListArtifactRegistryReposForTeamRequest) SetLimit(v int64) {
	x.xxx_hidden_Limit = v
}

func (x *ListArtifactRegistryReposForTeamRequest) SetOffset(v int64) {
	x.xxx_hidden_Offset = v
}

type ListArtifactRegistryReposForTeamRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug string
	Limit    int64
	Offset   int64
}

func (b0 ListArtifactRegistryReposForTeamRequest_builder) Build() *ListArtifactRegistryReposForTeamRequest {
	m0 := &ListArtifactRegistryReposForTeamRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamSlug = b.TeamSlug
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Offset = b.Offset
	return m0
}

type ListArtifactRegistryReposForTeamResponse struct {
	state               protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Team     string                   `protobuf:"bytes,1,opt,name=team,proto3"`
	xxx_hidden_Nodes    *[]*ArtifactRegistryRepo `protobuf:"bytes,2,rep,name=nodes,proto3"`
	xxx_hidden_PageInfo *PageInfo                `protobuf:"bytes,3,opt,name=page_info,json=pageInfo,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListArtifactRegistryReposForTeamResponse) Reset() {
	*x = ListArtifactRegistryReposForTeamResponse{}
	mi := &file_artifactregistry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactRegistryReposForTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactRegistryReposForTeamResponse) ProtoMessage() {}

func (x *ListArtifactRegistryReposForTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListArtifactRegistryReposForTeamResponse) GetTeam() string {
	if x != nil {
		return x.xxx_hidden_Team
	}
	return ""
}

func (x *ListArtifactRegistryReposForTeamResponse) GetNodes() []*ArtifactRegistryRepo {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *ListArtifactRegistryReposForTeamResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.xxx_hidden_PageInfo
	}
	return nil
}

func (x *ListArtifactRegistryReposForTeamResponse) SetTeam(v string) {
	x.xxx_hidden_Team = v
}

func (x *ListArtifactRegistryReposForTeamResponse) SetNodes(v []*ArtifactRegistryRepo) {
	x.xxx_hidden_Nodes = &v
}

func (x *ListArtifactRegistryReposForTeamResponse) SetPageInfo(v *PageInfo) {
	x.xxx_hidden_PageInfo = v
}

func (x *ListArtifactRegistryReposForTeamResponse) HasPageInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PageInfo != nil
}

func (x *ListArtifactRegistryReposForTeamResponse) ClearPageInfo() {
	x.xxx_hidden_PageInfo = nil
}

type ListArtifactRegistryReposForTeamResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Team     string
	Nodes    []*ArtifactRegistryRepo
	PageInfo *PageInfo
}

func (b0 ListArtifactRegistryReposForTeamResponse_builder) Build() *ListArtifactRegistryReposForTeamResponse {
	m0 := &ListArtifactRegistryReposForTeamResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Team = b.Team
	x.xxx_hidden_Nodes = &b.Nodes
	x.xxx_hidden_PageInfo = b.PageInfo
	return m0
}

type SetArtifactRegistryRepoSizeBytesResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetArtifactRegistryRepoSizeBytesResponse) Reset() {
	*x = SetArtifactRegistryRepoSizeBytesResponse{}
	mi := &file_artifactregistry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetArtifactRegistryRepoSizeBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetArtifactRegistryRepoSizeBytesResponse) ProtoMessage() {}

func (x *SetArtifactRegistryRepoSizeBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SetArtifactRegistryRepoSizeBytesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SetArtifactRegistryRepoSizeBytesResponse_builder) Build() *SetArtifactRegistryRepoSizeBytesResponse {
	m0 := &SetArtifactRegistryRepoSizeBytesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SetArtifactRegistryRepoSizeBytesRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamSlug  string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3"`
	xxx_hidden_Format    string                 `protobuf:"bytes,2,opt,name=format,proto3"`
	xxx_hidden_SizeBytes int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SetArtifactRegistryRepoSizeBytesRequest) Reset() {
	*x = SetArtifactRegistryRepoSizeBytesRequest{}
	mi := &file_artifactregistry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetArtifactRegistryRepoSizeBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetArtifactRegistryRepoSizeBytesRequest) ProtoMessage() {}

func (x *SetArtifactRegistryRepoSizeBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetArtifactRegistryRepoSizeBytesRequest) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *SetArtifactRegistryRepoSizeBytesRequest) GetFormat() string {
	if x != nil {
		return x.xxx_hidden_Format
	}
	return ""
}

func (x *SetArtifactRegistryRepoSizeBytesRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.xxx_hidden_SizeBytes
	}
	return 0
}

func (x *SetArtifactRegistryRepoSizeBytesRequest) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

func (x *SetArtifactRegistryRepoSizeBytesRequest) SetFormat(v string) {
	x.xxx_hidden_Format = v
}

func (x *SetArtifactRegistryRepoSizeBytesRequest) SetSizeBytes(v int64) {
	x.xxx_hidden_SizeBytes = v
}

type SetArtifactRegistryRepoSizeBytesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug  string
	Format    string
	SizeBytes int64
}

func (b0 SetArtifactRegistryRepoSizeBytesRequest_builder) Build() *SetArtifactRegistryRepoSizeBytesRequest {
	m0 := &SetArtifactRegistryRepoSizeBytesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamSlug = b.TeamSlug
	x.xxx_hidden_Format = b.Format
	x.xxx_hidden_SizeBytes = b.SizeBytes
	return m0
}

type GetArtifactRegistryGithubAllowlistRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamSlug string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3"`
	xxx_hidden_Limit    int64                  `protobuf:"varint,2,opt,name=limit,proto3"`
	xxx_hidden_Offset   int64                  `protobuf:"varint,3,opt,name=offset,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetArtifactRegistryGithubAllowlistRequest) Reset() {
	*x = GetArtifactRegistryGithubAllowlistRequest{}
	mi := &file_artifactregistry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRegistryGithubAllowlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRegistryGithubAllowlistRequest) ProtoMessage() {}

func (x *GetArtifactRegistryGithubAllowlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetArtifactRegistryGithubAllowlistRequest) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *GetArtifactRegistryGithubAllowlistRequest) GetLimit() int64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *GetArtifactRegistryGithubAllowlistRequest) GetOffset() int64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *GetArtifactRegistryGithubAllowlistRequest) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

func (x *GetArtifactRegistryGithubAllowlistRequest) SetLimit(v int64) {
	x.xxx_hidden_Limit = v
}

func (x *GetArtifactRegistryGithubAllowlistRequest) SetOffset(v int64) {
	x.xxx_hidden_Offset = v
}

type GetArtifactRegistryGithubAllowlistRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug string
	Limit    int64
	Offset   int64
}

func (b0 GetArtifactRegistryGithubAllowlistRequest_builder) Build() *GetArtifactRegistryGithubAllowlistRequest {
	m0 := &GetArtifactRegistryGithubAllowlistRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamSlug = b.TeamSlug
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Offset = b.Offset
	return m0
}

type GetArtifactRegistryGithubAllowlistResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes    []string               `protobuf:"bytes,1,rep,name=nodes,proto3"`
	xxx_hidden_PageInfo *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetArtifactRegistryGithubAllowlistResponse) Reset() {
	*x = GetArtifactRegistryGithubAllowlistResponse{}
	mi := &file_artifactregistry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRegistryGithubAllowlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRegistryGithubAllowlistResponse) ProtoMessage() {}

func (x *GetArtifactRegistryGithubAllowlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetArtifactRegistryGithubAllowlistResponse) GetNodes() []string {
	if x != nil {
		return x.xxx_hidden_Nodes
	}
	return nil
}

func (x *GetArtifactRegistryGithubAllowlistResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.xxx_hidden_PageInfo
	}
	return nil
}

func (x *GetArtifactRegistryGithubAllowlistResponse) SetNodes(v []string) {
	x.xxx_hidden_Nodes = v
}

func (x *GetArtifactRegistryGithubAllowlistResponse) SetPageInfo(v *PageInfo) {
	x.xxx_hidden_PageInfo = v
}

func (x *GetArtifactRegistryGithubAllowlistResponse) HasPageInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PageInfo != nil
}

func (x *GetArtifactRegistryGithubAllowlistResponse) ClearPageInfo() {
	x.xxx_hidden_PageInfo = nil
}

type GetArtifactRegistryGithubAllowlistResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes    []string
	PageInfo *PageInfo
}

func (b0 GetArtifactRegistryGithubAllowlistResponse_builder) Build() *GetArtifactRegistryGithubAllowlistResponse {
	m0 := &GetArtifactRegistryGithubAllowlistResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = b.Nodes
	x.xxx_hidden_PageInfo = b.PageInfo
	return m0
}

var File_artifactregistry_proto protoreflect.FileDescriptor

const file_artifactregistry_proto_rawDesc = "" +
	"\n" +
	"\x16artifactregistry.proto\x12\x12dapla.api.protobuf\x1a\x10pagination.proto\"j\n" +
	"\x14ArtifactRegistryRepo\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"_\n" +
	"\x1fGetArtifactRegistryRepoResponse\x12<\n" +
	"\x04repo\x18\x01 \x01(\v2(.dapla.api.protobuf.ArtifactRegistryRepoR\x04repo\"U\n" +
	"\x1eGetArtifactRegistryRepoRequest\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"t\n" +
	"'ListArtifactRegistryReposForTeamRequest\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"\xb9\x01\n" +
	"(ListArtifactRegistryReposForTeamResponse\x12\x12\n" +
	"\x04team\x18\x01 \x01(\tR\x04team\x12>\n" +
	"\x05nodes\x18\x02 \x03(\v2(.dapla.api.protobuf.ArtifactRegistryRepoR\x05nodes\x129\n" +
	"\tpage_info\x18\x03 \x01(\v2\x1c.dapla.api.protobuf.PageInfoR\bpageInfo\"*\n" +
	"(SetArtifactRegistryRepoSizeBytesResponse\"}\n" +
	"'SetArtifactRegistryRepoSizeBytesRequest\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"v\n" +
	")GetArtifactRegistryGithubAllowlistRequest\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"}\n" +
	"*GetArtifactRegistryGithubAllowlistResponse\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes\x129\n" +
	"\tpage_info\x18\x02 \x01(\v2\x1c.dapla.api.protobuf.PageInfoR\bpageInfo2\x85\x05\n" +
	"\x10ArtifactRegistry\x12\x84\x01\n" +
	"\x17GetArtifactRegistryRepo\x122.dapla.api.protobuf.GetArtifactRegistryRepoRequest\x1a3.dapla.api.protobuf.GetArtifactRegistryRepoResponse\"\x00\x12\x9f\x01\n" +
	" ListArtifactRegistryReposForTeam\x12;.dapla.api.protobuf.ListArtifactRegistryReposForTeamRequest\x1a<.dapla.api.protobuf.ListArtifactRegistryReposForTeamResponse\"\x00\x12\x9f\x01\n" +
	" SetArtifactRegistryRepoSizeBytes\x12;.dapla.api.protobuf.SetArtifactRegistryRepoSizeBytesRequest\x1a<.dapla.api.protobuf.SetArtifactRegistryRepoSizeBytesResponse\"\x00\x12\xa5\x01\n" +
	"\"GetArtifactRegistryGithubAllowlist\x12=.dapla.api.protobuf.GetArtifactRegistryGithubAllowlistRequest\x1a>.dapla.api.protobuf.GetArtifactRegistryGithubAllowlistResponse\"\x00B\x1aZ\x18./pkg/apiclient/protoapib\x06proto3"

var file_artifactregistry_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_artifactregistry_proto_goTypes = []any{
	(*ArtifactRegistryRepo)(nil),                       // 0: dapla.api.protobuf.ArtifactRegistryRepo
	(*GetArtifactRegistryRepoResponse)(nil),            // 1: dapla.api.protobuf.GetArtifactRegistryRepoResponse
	(*GetArtifactRegistryRepoRequest)(nil),             // 2: dapla.api.protobuf.GetArtifactRegistryRepoRequest
	(*ListArtifactRegistryReposForTeamRequest)(nil),    // 3: dapla.api.protobuf.ListArtifactRegistryReposForTeamRequest
	(*ListArtifactRegistryReposForTeamResponse)(nil),   // 4: dapla.api.protobuf.ListArtifactRegistryReposForTeamResponse
	(*SetArtifactRegistryRepoSizeBytesResponse)(nil),   // 5: dapla.api.protobuf.SetArtifactRegistryRepoSizeBytesResponse
	(*SetArtifactRegistryRepoSizeBytesRequest)(nil),    // 6: dapla.api.protobuf.SetArtifactRegistryRepoSizeBytesRequest
	(*GetArtifactRegistryGithubAllowlistRequest)(nil),  // 7: dapla.api.protobuf.GetArtifactRegistryGithubAllowlistRequest
	(*GetArtifactRegistryGithubAllowlistResponse)(nil), // 8: dapla.api.protobuf.GetArtifactRegistryGithubAllowlistResponse
	(*PageInfo)(nil), // 9: dapla.api.protobuf.PageInfo
}
var file_artifactregistry_proto_depIdxs = []int32{
	0, // 0: dapla.api.protobuf.GetArtifactRegistryRepoResponse.repo:type_name -> dapla.api.protobuf.ArtifactRegistryRepo
	0, // 1: dapla.api.protobuf.ListArtifactRegistryReposForTeamResponse.nodes:type_name -> dapla.api.protobuf.ArtifactRegistryRepo
	9, // 2: dapla.api.protobuf.ListArtifactRegistryReposForTeamResponse.page_info:type_name -> dapla.api.protobuf.PageInfo
	9, // 3: dapla.api.protobuf.GetArtifactRegistryGithubAllowlistResponse.page_info:type_name -> dapla.api.protobuf.PageInfo
	2, // 4: dapla.api.protobuf.ArtifactRegistry.GetArtifactRegistryRepo:input_type -> dapla.api.protobuf.GetArtifactRegistryRepoRequest
	3, // 5: dapla.api.protobuf.ArtifactRegistry.ListArtifactRegistryReposForTeam:input_type -> dapla.api.protobuf.ListArtifactRegistryReposForTeamRequest
	6, // 6: dapla.api.protobuf.ArtifactRegistry.SetArtifactRegistryRepoSizeBytes:input_type -> dapla.api.protobuf.SetArtifactRegistryRepoSizeBytesRequest
	7, // 7: dapla.api.protobuf.ArtifactRegistry.GetArtifactRegistryGithubAllowlist:input_type -> dapla.api.protobuf.GetArtifactRegistryGithubAllowlistRequest
	1, // 8: dapla.api.protobuf.ArtifactRegistry.GetArtifactRegistryRepo:output_type -> dapla.api.protobuf.GetArtifactRegistryRepoResponse
	4, // 9: dapla.api.protobuf.ArtifactRegistry.ListArtifactRegistryReposForTeam:output_type -> dapla.api.protobuf.ListArtifactRegistryReposForTeamResponse
	5, // 10: dapla.api.protobuf.ArtifactRegistry.SetArtifactRegistryRepoSizeBytes:output_type -> dapla.api.protobuf.SetArtifactRegistryRepoSizeBytesResponse
	8, // 11: dapla.api.protobuf.ArtifactRegistry.GetArtifactRegistryGithubAllowlist:output_type -> dapla.api.protobuf.GetArtifactRegistryGithubAllowlistResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_artifactregistry_proto_init() }
func file_artifactregistry_proto_init() {
	if File_artifactregistry_proto != nil {
		return
	}
	file_pagination_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifactregistry_proto_rawDesc), len(file_artifactregistry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artifactregistry_proto_goTypes,
		DependencyIndexes: file_artifactregistry_proto_depIdxs,
		MessageInfos:      file_artifactregistry_proto_msgTypes,
	}.Build()
	File_artifactregistry_proto = out.File
	file_artifactregistry_proto_goTypes = nil
	file_artifactregistry_proto_depIdxs = nil
}
