// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: atlantis.proto

//go:build !protoopaque

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AtlantisConfig struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	TeamSlug      string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3" json:"team_slug,omitempty"`
	WebhookSecret *string                `protobuf:"bytes,2,opt,name=webhook_secret,json=webhookSecret,proto3,oneof" json:"webhook_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtlantisConfig) Reset() {
	*x = AtlantisConfig{}
	mi := &file_atlantis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtlantisConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtlantisConfig) ProtoMessage() {}

func (x *AtlantisConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AtlantisConfig) GetTeamSlug() string {
	if x != nil {
		return x.TeamSlug
	}
	return ""
}

func (x *AtlantisConfig) GetWebhookSecret() string {
	if x != nil && x.WebhookSecret != nil {
		return *x.WebhookSecret
	}
	return ""
}

func (x *AtlantisConfig) SetTeamSlug(v string) {
	x.TeamSlug = v
}

func (x *AtlantisConfig) SetWebhookSecret(v string) {
	x.WebhookSecret = &v
}

func (x *AtlantisConfig) HasWebhookSecret() bool {
	if x == nil {
		return false
	}
	return x.WebhookSecret != nil
}

func (x *AtlantisConfig) ClearWebhookSecret() {
	x.WebhookSecret = nil
}

type AtlantisConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug      string
	WebhookSecret *string
}

func (b0 AtlantisConfig_builder) Build() *AtlantisConfig {
	m0 := &AtlantisConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.TeamSlug = b.TeamSlug
	x.WebhookSecret = b.WebhookSecret
	return m0
}

type GetTeamAtlantisRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	TeamSlug      string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3" json:"team_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamAtlantisRequest) Reset() {
	*x = GetTeamAtlantisRequest{}
	mi := &file_atlantis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamAtlantisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamAtlantisRequest) ProtoMessage() {}

func (x *GetTeamAtlantisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetTeamAtlantisRequest) GetTeamSlug() string {
	if x != nil {
		return x.TeamSlug
	}
	return ""
}

func (x *GetTeamAtlantisRequest) SetTeamSlug(v string) {
	x.TeamSlug = v
}

type GetTeamAtlantisRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug string
}

func (b0 GetTeamAtlantisRequest_builder) Build() *GetTeamAtlantisRequest {
	m0 := &GetTeamAtlantisRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.TeamSlug = b.TeamSlug
	return m0
}

type GetTeamAtlantisResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Config        *AtlantisConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamAtlantisResponse) Reset() {
	*x = GetTeamAtlantisResponse{}
	mi := &file_atlantis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamAtlantisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamAtlantisResponse) ProtoMessage() {}

func (x *GetTeamAtlantisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetTeamAtlantisResponse) GetConfig() *AtlantisConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetTeamAtlantisResponse) SetConfig(v *AtlantisConfig) {
	x.Config = v
}

func (x *GetTeamAtlantisResponse) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.Config != nil
}

func (x *GetTeamAtlantisResponse) ClearConfig() {
	x.Config = nil
}

type GetTeamAtlantisResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Config *AtlantisConfig
}

func (b0 GetTeamAtlantisResponse_builder) Build() *GetTeamAtlantisResponse {
	m0 := &GetTeamAtlantisResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Config = b.Config
	return m0
}

var File_atlantis_proto protoreflect.FileDescriptor

const file_atlantis_proto_rawDesc = "" +
	"\n" +
	"\x0eatlantis.proto\x12\x12dapla.api.protobuf\"l\n" +
	"\x0eAtlantisConfig\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12*\n" +
	"\x0ewebhook_secret\x18\x02 \x01(\tH\x00R\rwebhookSecret\x88\x01\x01B\x11\n" +
	"\x0f_webhook_secret\"5\n" +
	"\x16GetTeamAtlantisRequest\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\"U\n" +
	"\x17GetTeamAtlantisResponse\x12:\n" +
	"\x06config\x18\x01 \x01(\v2\".dapla.api.protobuf.AtlantisConfigR\x06config2x\n" +
	"\bAtlantis\x12l\n" +
	"\x0fGetTeamAtlantis\x12*.dapla.api.protobuf.GetTeamAtlantisRequest\x1a+.dapla.api.protobuf.GetTeamAtlantisResponse\"\x00B\x1aZ\x18./pkg/apiclient/protoapib\x06proto3"

var file_atlantis_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_atlantis_proto_goTypes = []any{
	(*AtlantisConfig)(nil),          // 0: dapla.api.protobuf.AtlantisConfig
	(*GetTeamAtlantisRequest)(nil),  // 1: dapla.api.protobuf.GetTeamAtlantisRequest
	(*GetTeamAtlantisResponse)(nil), // 2: dapla.api.protobuf.GetTeamAtlantisResponse
}
var file_atlantis_proto_depIdxs = []int32{
	0, // 0: dapla.api.protobuf.GetTeamAtlantisResponse.config:type_name -> dapla.api.protobuf.AtlantisConfig
	1, // 1: dapla.api.protobuf.Atlantis.GetTeamAtlantis:input_type -> dapla.api.protobuf.GetTeamAtlantisRequest
	2, // 2: dapla.api.protobuf.Atlantis.GetTeamAtlantis:output_type -> dapla.api.protobuf.GetTeamAtlantisResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_atlantis_proto_init() }
func file_atlantis_proto_init() {
	if File_atlantis_proto != nil {
		return
	}
	file_atlantis_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atlantis_proto_rawDesc), len(file_atlantis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atlantis_proto_goTypes,
		DependencyIndexes: file_atlantis_proto_depIdxs,
		MessageInfos:      file_atlantis_proto_msgTypes,
	}.Build()
	File_atlantis_proto = out.File
	file_atlantis_proto_goTypes = nil
	file_atlantis_proto_depIdxs = nil
}
