// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: atlantis.proto

package protoapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Atlantis_GetTeamAtlantis_FullMethodName = "/dapla.api.protobuf.Atlantis/GetTeamAtlantis"
)

// AtlantisClient is the client API for Atlantis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AtlantisClient interface {
	GetTeamAtlantis(ctx context.Context, in *GetTeamAtlantisRequest, opts ...grpc.CallOption) (*GetTeamAtlantisResponse, error)
}

type atlantisClient struct {
	cc grpc.ClientConnInterface
}

func NewAtlantisClient(cc grpc.ClientConnInterface) AtlantisClient {
	return &atlantisClient{cc}
}

func (c *atlantisClient) GetTeamAtlantis(ctx context.Context, in *GetTeamAtlantisRequest, opts ...grpc.CallOption) (*GetTeamAtlantisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamAtlantisResponse)
	err := c.cc.Invoke(ctx, Atlantis_GetTeamAtlantis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AtlantisServer is the server API for Atlantis service.
// All implementations must embed UnimplementedAtlantisServer
// for forward compatibility.
type AtlantisServer interface {
	GetTeamAtlantis(context.Context, *GetTeamAtlantisRequest) (*GetTeamAtlantisResponse, error)
	mustEmbedUnimplementedAtlantisServer()
}

// UnimplementedAtlantisServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAtlantisServer struct{}

func (UnimplementedAtlantisServer) GetTeamAtlantis(context.Context, *GetTeamAtlantisRequest) (*GetTeamAtlantisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeamAtlantis not implemented")
}
func (UnimplementedAtlantisServer) mustEmbedUnimplementedAtlantisServer() {}
func (UnimplementedAtlantisServer) testEmbeddedByValue()                  {}

// UnsafeAtlantisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AtlantisServer will
// result in compilation errors.
type UnsafeAtlantisServer interface {
	mustEmbedUnimplementedAtlantisServer()
}

func RegisterAtlantisServer(s grpc.ServiceRegistrar, srv AtlantisServer) {
	// If the following call panics, it indicates UnimplementedAtlantisServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Atlantis_ServiceDesc, srv)
}

func _Atlantis_GetTeamAtlantis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamAtlantisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtlantisServer).GetTeamAtlantis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Atlantis_GetTeamAtlantis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtlantisServer).GetTeamAtlantis(ctx, req.(*GetTeamAtlantisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Atlantis_ServiceDesc is the grpc.ServiceDesc for Atlantis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Atlantis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapla.api.protobuf.Atlantis",
	HandlerType: (*AtlantisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTeamAtlantis",
			Handler:    _Atlantis_GetTeamAtlantis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atlantis.proto",
}
