// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: gcpteamresources.proto

//go:build !protoopaque

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GcpTeamFolder struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	TeamSlug      string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3" json:"team_slug,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	FolderId      string                 `protobuf:"bytes,3,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpTeamFolder) Reset() {
	*x = GcpTeamFolder{}
	mi := &file_gcpteamresources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpTeamFolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpTeamFolder) ProtoMessage() {}

func (x *GcpTeamFolder) ProtoReflect() protoreflect.Message {
	mi := &file_gcpteamresources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GcpTeamFolder) GetTeamSlug() string {
	if x != nil {
		return x.TeamSlug
	}
	return ""
}

func (x *GcpTeamFolder) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *GcpTeamFolder) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *GcpTeamFolder) SetTeamSlug(v string) {
	x.TeamSlug = v
}

func (x *GcpTeamFolder) SetEnv(v string) {
	x.Env = v
}

func (x *GcpTeamFolder) SetFolderId(v string) {
	x.FolderId = v
}

type GcpTeamFolder_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug string
	Env      string
	FolderId string
}

func (b0 GcpTeamFolder_builder) Build() *GcpTeamFolder {
	m0 := &GcpTeamFolder{}
	b, x := &b0, m0
	_, _ = b, x
	x.TeamSlug = b.TeamSlug
	x.Env = b.Env
	x.FolderId = b.FolderId
	return m0
}

type UpsertGcpTeamFolderRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Folder        *GcpTeamFolder         `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGcpTeamFolderRequest) Reset() {
	*x = UpsertGcpTeamFolderRequest{}
	mi := &file_gcpteamresources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGcpTeamFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGcpTeamFolderRequest) ProtoMessage() {}

func (x *UpsertGcpTeamFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gcpteamresources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpsertGcpTeamFolderRequest) GetFolder() *GcpTeamFolder {
	if x != nil {
		return x.Folder
	}
	return nil
}

func (x *UpsertGcpTeamFolderRequest) SetFolder(v *GcpTeamFolder) {
	x.Folder = v
}

func (x *UpsertGcpTeamFolderRequest) HasFolder() bool {
	if x == nil {
		return false
	}
	return x.Folder != nil
}

func (x *UpsertGcpTeamFolderRequest) ClearFolder() {
	x.Folder = nil
}

type UpsertGcpTeamFolderRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Folder *GcpTeamFolder
}

func (b0 UpsertGcpTeamFolderRequest_builder) Build() *UpsertGcpTeamFolderRequest {
	m0 := &UpsertGcpTeamFolderRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Folder = b.Folder
	return m0
}

type UpsertGcpTeamFolderResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGcpTeamFolderResponse) Reset() {
	*x = UpsertGcpTeamFolderResponse{}
	mi := &file_gcpteamresources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGcpTeamFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGcpTeamFolderResponse) ProtoMessage() {}

func (x *UpsertGcpTeamFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gcpteamresources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UpsertGcpTeamFolderResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UpsertGcpTeamFolderResponse_builder) Build() *UpsertGcpTeamFolderResponse {
	m0 := &UpsertGcpTeamFolderResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetGcpTeamFolderRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	TeamSlug      string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3" json:"team_slug,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGcpTeamFolderRequest) Reset() {
	*x = GetGcpTeamFolderRequest{}
	mi := &file_gcpteamresources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGcpTeamFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGcpTeamFolderRequest) ProtoMessage() {}

func (x *GetGcpTeamFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gcpteamresources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetGcpTeamFolderRequest) GetTeamSlug() string {
	if x != nil {
		return x.TeamSlug
	}
	return ""
}

func (x *GetGcpTeamFolderRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *GetGcpTeamFolderRequest) SetTeamSlug(v string) {
	x.TeamSlug = v
}

func (x *GetGcpTeamFolderRequest) SetEnv(v string) {
	x.Env = v
}

type GetGcpTeamFolderRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug string
	Env      string
}

func (b0 GetGcpTeamFolderRequest_builder) Build() *GetGcpTeamFolderRequest {
	m0 := &GetGcpTeamFolderRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.TeamSlug = b.TeamSlug
	x.Env = b.Env
	return m0
}

type GetGcpTeamFolderResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Folder        *GcpTeamFolder         `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGcpTeamFolderResponse) Reset() {
	*x = GetGcpTeamFolderResponse{}
	mi := &file_gcpteamresources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGcpTeamFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGcpTeamFolderResponse) ProtoMessage() {}

func (x *GetGcpTeamFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gcpteamresources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetGcpTeamFolderResponse) GetFolder() *GcpTeamFolder {
	if x != nil {
		return x.Folder
	}
	return nil
}

func (x *GetGcpTeamFolderResponse) SetFolder(v *GcpTeamFolder) {
	x.Folder = v
}

func (x *GetGcpTeamFolderResponse) HasFolder() bool {
	if x == nil {
		return false
	}
	return x.Folder != nil
}

func (x *GetGcpTeamFolderResponse) ClearFolder() {
	x.Folder = nil
}

type GetGcpTeamFolderResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Folder *GcpTeamFolder
}

func (b0 GetGcpTeamFolderResponse_builder) Build() *GetGcpTeamFolderResponse {
	m0 := &GetGcpTeamFolderResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Folder = b.Folder
	return m0
}

var File_gcpteamresources_proto protoreflect.FileDescriptor

const file_gcpteamresources_proto_rawDesc = "" +
	"\n" +
	"\x16gcpteamresources.proto\x12\x12dapla.api.protobuf\"[\n" +
	"\rGcpTeamFolder\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12\x1b\n" +
	"\tfolder_id\x18\x03 \x01(\tR\bfolderId\"W\n" +
	"\x1aUpsertGcpTeamFolderRequest\x129\n" +
	"\x06folder\x18\x01 \x01(\v2!.dapla.api.protobuf.GcpTeamFolderR\x06folder\"\x1d\n" +
	"\x1bUpsertGcpTeamFolderResponse\"H\n" +
	"\x17GetGcpTeamFolderRequest\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\"U\n" +
	"\x18GetGcpTeamFolderResponse\x129\n" +
	"\x06folder\x18\x01 \x01(\v2!.dapla.api.protobuf.GcpTeamFolderR\x06folder2\xf7\x01\n" +
	"\x10GcpTeamResources\x12u\n" +
	"\x10UpsertTeamFolder\x12..dapla.api.protobuf.UpsertGcpTeamFolderRequest\x1a/.dapla.api.protobuf.UpsertGcpTeamFolderResponse\"\x00\x12l\n" +
	"\rGetTeamFolder\x12+.dapla.api.protobuf.GetGcpTeamFolderRequest\x1a,.dapla.api.protobuf.GetGcpTeamFolderResponse\"\x00B\x1aZ\x18./pkg/apiclient/protoapib\x06proto3"

var file_gcpteamresources_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gcpteamresources_proto_goTypes = []any{
	(*GcpTeamFolder)(nil),               // 0: dapla.api.protobuf.GcpTeamFolder
	(*UpsertGcpTeamFolderRequest)(nil),  // 1: dapla.api.protobuf.UpsertGcpTeamFolderRequest
	(*UpsertGcpTeamFolderResponse)(nil), // 2: dapla.api.protobuf.UpsertGcpTeamFolderResponse
	(*GetGcpTeamFolderRequest)(nil),     // 3: dapla.api.protobuf.GetGcpTeamFolderRequest
	(*GetGcpTeamFolderResponse)(nil),    // 4: dapla.api.protobuf.GetGcpTeamFolderResponse
}
var file_gcpteamresources_proto_depIdxs = []int32{
	0, // 0: dapla.api.protobuf.UpsertGcpTeamFolderRequest.folder:type_name -> dapla.api.protobuf.GcpTeamFolder
	0, // 1: dapla.api.protobuf.GetGcpTeamFolderResponse.folder:type_name -> dapla.api.protobuf.GcpTeamFolder
	1, // 2: dapla.api.protobuf.GcpTeamResources.UpsertTeamFolder:input_type -> dapla.api.protobuf.UpsertGcpTeamFolderRequest
	3, // 3: dapla.api.protobuf.GcpTeamResources.GetTeamFolder:input_type -> dapla.api.protobuf.GetGcpTeamFolderRequest
	2, // 4: dapla.api.protobuf.GcpTeamResources.UpsertTeamFolder:output_type -> dapla.api.protobuf.UpsertGcpTeamFolderResponse
	4, // 5: dapla.api.protobuf.GcpTeamResources.GetTeamFolder:output_type -> dapla.api.protobuf.GetGcpTeamFolderResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gcpteamresources_proto_init() }
func file_gcpteamresources_proto_init() {
	if File_gcpteamresources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcpteamresources_proto_rawDesc), len(file_gcpteamresources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gcpteamresources_proto_goTypes,
		DependencyIndexes: file_gcpteamresources_proto_depIdxs,
		MessageInfos:      file_gcpteamresources_proto_msgTypes,
	}.Build()
	File_gcpteamresources_proto = out.File
	file_gcpteamresources_proto_goTypes = nil
	file_gcpteamresources_proto_depIdxs = nil
}
