// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package protoapi

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamsServer creates a new instance of MockTeamsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamsServer(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockTeamsServer {
	mock := &MockTeamsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamsServer is an autogenerated mock type for the TeamsServer type
type MockTeamsServer struct {
	mock.Mock
}

type MockTeamsServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamsServer) EXPECT() *MockTeamsServer_Expecter {
	return &MockTeamsServer_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockTeamsServer
func (_mock *MockTeamsServer) Delete(context1 context.Context, deleteTeamRequest *DeleteTeamRequest) (*DeleteTeamResponse, error) {
	ret := _mock.Called(context1, deleteTeamRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *DeleteTeamResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeleteTeamRequest) (*DeleteTeamResponse, error)); ok {
		return returnFunc(context1, deleteTeamRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeleteTeamRequest) *DeleteTeamResponse); ok {
		r0 = returnFunc(context1, deleteTeamRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeleteTeamResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *DeleteTeamRequest) error); ok {
		r1 = returnFunc(context1, deleteTeamRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamsServer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTeamsServer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteTeamRequest *DeleteTeamRequest
func (_e *MockTeamsServer_Expecter) Delete(context1 interface{}, deleteTeamRequest interface{}) *MockTeamsServer_Delete_Call {
	return &MockTeamsServer_Delete_Call{Call: _e.mock.On("Delete", context1, deleteTeamRequest)}
}

func (_c *MockTeamsServer_Delete_Call) Run(run func(context1 context.Context, deleteTeamRequest *DeleteTeamRequest)) *MockTeamsServer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DeleteTeamRequest
		if args[1] != nil {
			arg1 = args[1].(*DeleteTeamRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamsServer_Delete_Call) Return(deleteTeamResponse *DeleteTeamResponse, err error) *MockTeamsServer_Delete_Call {
	_c.Call.Return(deleteTeamResponse, err)
	return _c
}

func (_c *MockTeamsServer_Delete_Call) RunAndReturn(run func(context1 context.Context, deleteTeamRequest *DeleteTeamRequest) (*DeleteTeamResponse, error)) *MockTeamsServer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTeamsServer
func (_mock *MockTeamsServer) Get(context1 context.Context, getTeamRequest *GetTeamRequest) (*GetTeamResponse, error) {
	ret := _mock.Called(context1, getTeamRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *GetTeamResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetTeamRequest) (*GetTeamResponse, error)); ok {
		return returnFunc(context1, getTeamRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetTeamRequest) *GetTeamResponse); ok {
		r0 = returnFunc(context1, getTeamRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetTeamResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *GetTeamRequest) error); ok {
		r1 = returnFunc(context1, getTeamRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamsServer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTeamsServer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - getTeamRequest *GetTeamRequest
func (_e *MockTeamsServer_Expecter) Get(context1 interface{}, getTeamRequest interface{}) *MockTeamsServer_Get_Call {
	return &MockTeamsServer_Get_Call{Call: _e.mock.On("Get", context1, getTeamRequest)}
}

func (_c *MockTeamsServer_Get_Call) Run(run func(context1 context.Context, getTeamRequest *GetTeamRequest)) *MockTeamsServer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *GetTeamRequest
		if args[1] != nil {
			arg1 = args[1].(*GetTeamRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamsServer_Get_Call) Return(getTeamResponse *GetTeamResponse, err error) *MockTeamsServer_Get_Call {
	_c.Call.Return(getTeamResponse, err)
	return _c
}

func (_c *MockTeamsServer_Get_Call) RunAndReturn(run func(context1 context.Context, getTeamRequest *GetTeamRequest) (*GetTeamResponse, error)) *MockTeamsServer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Groups provides a mock function for the type MockTeamsServer
func (_mock *MockTeamsServer) Groups(context1 context.Context, listTeamGroupsRequest *ListTeamGroupsRequest) (*ListTeamGroupsResponse, error) {
	ret := _mock.Called(context1, listTeamGroupsRequest)

	if len(ret) == 0 {
		panic("no return value specified for Groups")
	}

	var r0 *ListTeamGroupsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListTeamGroupsRequest) (*ListTeamGroupsResponse, error)); ok {
		return returnFunc(context1, listTeamGroupsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListTeamGroupsRequest) *ListTeamGroupsResponse); ok {
		r0 = returnFunc(context1, listTeamGroupsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ListTeamGroupsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ListTeamGroupsRequest) error); ok {
		r1 = returnFunc(context1, listTeamGroupsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamsServer_Groups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Groups'
type MockTeamsServer_Groups_Call struct {
	*mock.Call
}

// Groups is a helper method to define mock.On call
//   - context1 context.Context
//   - listTeamGroupsRequest *ListTeamGroupsRequest
func (_e *MockTeamsServer_Expecter) Groups(context1 interface{}, listTeamGroupsRequest interface{}) *MockTeamsServer_Groups_Call {
	return &MockTeamsServer_Groups_Call{Call: _e.mock.On("Groups", context1, listTeamGroupsRequest)}
}

func (_c *MockTeamsServer_Groups_Call) Run(run func(context1 context.Context, listTeamGroupsRequest *ListTeamGroupsRequest)) *MockTeamsServer_Groups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ListTeamGroupsRequest
		if args[1] != nil {
			arg1 = args[1].(*ListTeamGroupsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamsServer_Groups_Call) Return(listTeamGroupsResponse *ListTeamGroupsResponse, err error) *MockTeamsServer_Groups_Call {
	_c.Call.Return(listTeamGroupsResponse, err)
	return _c
}

func (_c *MockTeamsServer_Groups_Call) RunAndReturn(run func(context1 context.Context, listTeamGroupsRequest *ListTeamGroupsRequest) (*ListTeamGroupsResponse, error)) *MockTeamsServer_Groups_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTeamsServer
func (_mock *MockTeamsServer) List(context1 context.Context, listTeamsRequest *ListTeamsRequest) (*ListTeamsResponse, error) {
	ret := _mock.Called(context1, listTeamsRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *ListTeamsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListTeamsRequest) (*ListTeamsResponse, error)); ok {
		return returnFunc(context1, listTeamsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListTeamsRequest) *ListTeamsResponse); ok {
		r0 = returnFunc(context1, listTeamsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ListTeamsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ListTeamsRequest) error); ok {
		r1 = returnFunc(context1, listTeamsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamsServer_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTeamsServer_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - listTeamsRequest *ListTeamsRequest
func (_e *MockTeamsServer_Expecter) List(context1 interface{}, listTeamsRequest interface{}) *MockTeamsServer_List_Call {
	return &MockTeamsServer_List_Call{Call: _e.mock.On("List", context1, listTeamsRequest)}
}

func (_c *MockTeamsServer_List_Call) Run(run func(context1 context.Context, listTeamsRequest *ListTeamsRequest)) *MockTeamsServer_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ListTeamsRequest
		if args[1] != nil {
			arg1 = args[1].(*ListTeamsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamsServer_List_Call) Return(listTeamsResponse *ListTeamsResponse, err error) *MockTeamsServer_List_Call {
	_c.Call.Return(listTeamsResponse, err)
	return _c
}

func (_c *MockTeamsServer_List_Call) RunAndReturn(run func(context1 context.Context, listTeamsRequest *ListTeamsRequest) (*ListTeamsResponse, error)) *MockTeamsServer_List_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedTeamsServer provides a mock function for the type MockTeamsServer
func (_mock *MockTeamsServer) mustEmbedUnimplementedTeamsServer() {
	_mock.Called()
	return
}

// MockTeamsServer_mustEmbedUnimplementedTeamsServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedTeamsServer'
type MockTeamsServer_mustEmbedUnimplementedTeamsServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedTeamsServer is a helper method to define mock.On call
func (_e *MockTeamsServer_Expecter) mustEmbedUnimplementedTeamsServer() *MockTeamsServer_mustEmbedUnimplementedTeamsServer_Call {
	return &MockTeamsServer_mustEmbedUnimplementedTeamsServer_Call{Call: _e.mock.On("mustEmbedUnimplementedTeamsServer")}
}

func (_c *MockTeamsServer_mustEmbedUnimplementedTeamsServer_Call) Run(run func()) *MockTeamsServer_mustEmbedUnimplementedTeamsServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTeamsServer_mustEmbedUnimplementedTeamsServer_Call) Return() *MockTeamsServer_mustEmbedUnimplementedTeamsServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTeamsServer_mustEmbedUnimplementedTeamsServer_Call) RunAndReturn(run func()) *MockTeamsServer_mustEmbedUnimplementedTeamsServer_Call {
	_c.Run(run)
	return _c
}
