// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: sharedbucketsstopgap.proto

package protoapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SharedBucketsStopgap_Create_FullMethodName      = "/dapla.api.protobuf.SharedBucketsStopgap/Create"
	SharedBucketsStopgap_Get_FullMethodName         = "/dapla.api.protobuf.SharedBucketsStopgap/Get"
	SharedBucketsStopgap_Groups_FullMethodName      = "/dapla.api.protobuf.SharedBucketsStopgap/Groups"
	SharedBucketsStopgap_AddGroup_FullMethodName    = "/dapla.api.protobuf.SharedBucketsStopgap/AddGroup"
	SharedBucketsStopgap_RemoveGroup_FullMethodName = "/dapla.api.protobuf.SharedBucketsStopgap/RemoveGroup"
)

// SharedBucketsStopgapClient is the client API for SharedBucketsStopgap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SharedBucketsStopgapClient interface {
	Create(ctx context.Context, in *CreateSharedBucketsStopgapRequest, opts ...grpc.CallOption) (*CreateSharedBucketsStopgapResponse, error)
	Get(ctx context.Context, in *GetSharedBucketsStopgapRequest, opts ...grpc.CallOption) (*GetSharedBucketsStopgapResponse, error)
	Groups(ctx context.Context, in *ListSharedBucketsStopgapGroupsRequest, opts ...grpc.CallOption) (*ListSharedBucketsStopgapGroupsResponse, error)
	AddGroup(ctx context.Context, in *AddSharedBucketsStopgapGroupRequest, opts ...grpc.CallOption) (*AddSharedBucketsStopgapGroupResponse, error)
	RemoveGroup(ctx context.Context, in *RemoveSharedBucketsStopgapGroupRequest, opts ...grpc.CallOption) (*RemoveSharedBucketsStopgapGroupResponse, error)
}

type sharedBucketsStopgapClient struct {
	cc grpc.ClientConnInterface
}

func NewSharedBucketsStopgapClient(cc grpc.ClientConnInterface) SharedBucketsStopgapClient {
	return &sharedBucketsStopgapClient{cc}
}

func (c *sharedBucketsStopgapClient) Create(ctx context.Context, in *CreateSharedBucketsStopgapRequest, opts ...grpc.CallOption) (*CreateSharedBucketsStopgapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSharedBucketsStopgapResponse)
	err := c.cc.Invoke(ctx, SharedBucketsStopgap_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharedBucketsStopgapClient) Get(ctx context.Context, in *GetSharedBucketsStopgapRequest, opts ...grpc.CallOption) (*GetSharedBucketsStopgapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSharedBucketsStopgapResponse)
	err := c.cc.Invoke(ctx, SharedBucketsStopgap_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharedBucketsStopgapClient) Groups(ctx context.Context, in *ListSharedBucketsStopgapGroupsRequest, opts ...grpc.CallOption) (*ListSharedBucketsStopgapGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSharedBucketsStopgapGroupsResponse)
	err := c.cc.Invoke(ctx, SharedBucketsStopgap_Groups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharedBucketsStopgapClient) AddGroup(ctx context.Context, in *AddSharedBucketsStopgapGroupRequest, opts ...grpc.CallOption) (*AddSharedBucketsStopgapGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSharedBucketsStopgapGroupResponse)
	err := c.cc.Invoke(ctx, SharedBucketsStopgap_AddGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharedBucketsStopgapClient) RemoveGroup(ctx context.Context, in *RemoveSharedBucketsStopgapGroupRequest, opts ...grpc.CallOption) (*RemoveSharedBucketsStopgapGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSharedBucketsStopgapGroupResponse)
	err := c.cc.Invoke(ctx, SharedBucketsStopgap_RemoveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SharedBucketsStopgapServer is the server API for SharedBucketsStopgap service.
// All implementations must embed UnimplementedSharedBucketsStopgapServer
// for forward compatibility.
type SharedBucketsStopgapServer interface {
	Create(context.Context, *CreateSharedBucketsStopgapRequest) (*CreateSharedBucketsStopgapResponse, error)
	Get(context.Context, *GetSharedBucketsStopgapRequest) (*GetSharedBucketsStopgapResponse, error)
	Groups(context.Context, *ListSharedBucketsStopgapGroupsRequest) (*ListSharedBucketsStopgapGroupsResponse, error)
	AddGroup(context.Context, *AddSharedBucketsStopgapGroupRequest) (*AddSharedBucketsStopgapGroupResponse, error)
	RemoveGroup(context.Context, *RemoveSharedBucketsStopgapGroupRequest) (*RemoveSharedBucketsStopgapGroupResponse, error)
	mustEmbedUnimplementedSharedBucketsStopgapServer()
}

// UnimplementedSharedBucketsStopgapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSharedBucketsStopgapServer struct{}

func (UnimplementedSharedBucketsStopgapServer) Create(context.Context, *CreateSharedBucketsStopgapRequest) (*CreateSharedBucketsStopgapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSharedBucketsStopgapServer) Get(context.Context, *GetSharedBucketsStopgapRequest) (*GetSharedBucketsStopgapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSharedBucketsStopgapServer) Groups(context.Context, *ListSharedBucketsStopgapGroupsRequest) (*ListSharedBucketsStopgapGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Groups not implemented")
}
func (UnimplementedSharedBucketsStopgapServer) AddGroup(context.Context, *AddSharedBucketsStopgapGroupRequest) (*AddSharedBucketsStopgapGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGroup not implemented")
}
func (UnimplementedSharedBucketsStopgapServer) RemoveGroup(context.Context, *RemoveSharedBucketsStopgapGroupRequest) (*RemoveSharedBucketsStopgapGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveGroup not implemented")
}
func (UnimplementedSharedBucketsStopgapServer) mustEmbedUnimplementedSharedBucketsStopgapServer() {}
func (UnimplementedSharedBucketsStopgapServer) testEmbeddedByValue()                              {}

// UnsafeSharedBucketsStopgapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SharedBucketsStopgapServer will
// result in compilation errors.
type UnsafeSharedBucketsStopgapServer interface {
	mustEmbedUnimplementedSharedBucketsStopgapServer()
}

func RegisterSharedBucketsStopgapServer(s grpc.ServiceRegistrar, srv SharedBucketsStopgapServer) {
	// If the following call pancis, it indicates UnimplementedSharedBucketsStopgapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SharedBucketsStopgap_ServiceDesc, srv)
}

func _SharedBucketsStopgap_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSharedBucketsStopgapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharedBucketsStopgapServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharedBucketsStopgap_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharedBucketsStopgapServer).Create(ctx, req.(*CreateSharedBucketsStopgapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharedBucketsStopgap_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSharedBucketsStopgapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharedBucketsStopgapServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharedBucketsStopgap_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharedBucketsStopgapServer).Get(ctx, req.(*GetSharedBucketsStopgapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharedBucketsStopgap_Groups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSharedBucketsStopgapGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharedBucketsStopgapServer).Groups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharedBucketsStopgap_Groups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharedBucketsStopgapServer).Groups(ctx, req.(*ListSharedBucketsStopgapGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharedBucketsStopgap_AddGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSharedBucketsStopgapGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharedBucketsStopgapServer).AddGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharedBucketsStopgap_AddGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharedBucketsStopgapServer).AddGroup(ctx, req.(*AddSharedBucketsStopgapGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharedBucketsStopgap_RemoveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSharedBucketsStopgapGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharedBucketsStopgapServer).RemoveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharedBucketsStopgap_RemoveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharedBucketsStopgapServer).RemoveGroup(ctx, req.(*RemoveSharedBucketsStopgapGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SharedBucketsStopgap_ServiceDesc is the grpc.ServiceDesc for SharedBucketsStopgap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SharedBucketsStopgap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapla.api.protobuf.SharedBucketsStopgap",
	HandlerType: (*SharedBucketsStopgapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SharedBucketsStopgap_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SharedBucketsStopgap_Get_Handler,
		},
		{
			MethodName: "Groups",
			Handler:    _SharedBucketsStopgap_Groups_Handler,
		},
		{
			MethodName: "AddGroup",
			Handler:    _SharedBucketsStopgap_AddGroup_Handler,
		},
		{
			MethodName: "RemoveGroup",
			Handler:    _SharedBucketsStopgap_RemoveGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sharedbucketsstopgap.proto",
}
