// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: sharedbucketsstopgap.proto

//go:build protoopaque

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SharedBucketStopgap struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamSlug  string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3"`
	xxx_hidden_ShortName string                 `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3"`
	xxx_hidden_Type      string                 `protobuf:"bytes,3,opt,name=type,proto3"`
	xxx_hidden_Env       string                 `protobuf:"bytes,4,opt,name=env,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SharedBucketStopgap) Reset() {
	*x = SharedBucketStopgap{}
	mi := &file_sharedbucketsstopgap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedBucketStopgap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedBucketStopgap) ProtoMessage() {}

func (x *SharedBucketStopgap) ProtoReflect() protoreflect.Message {
	mi := &file_sharedbucketsstopgap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SharedBucketStopgap) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *SharedBucketStopgap) GetShortName() string {
	if x != nil {
		return x.xxx_hidden_ShortName
	}
	return ""
}

func (x *SharedBucketStopgap) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *SharedBucketStopgap) GetEnv() string {
	if x != nil {
		return x.xxx_hidden_Env
	}
	return ""
}

func (x *SharedBucketStopgap) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

func (x *SharedBucketStopgap) SetShortName(v string) {
	x.xxx_hidden_ShortName = v
}

func (x *SharedBucketStopgap) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *SharedBucketStopgap) SetEnv(v string) {
	x.xxx_hidden_Env = v
}

type SharedBucketStopgap_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug  string
	ShortName string
	Type      string
	Env       string
}

func (b0 SharedBucketStopgap_builder) Build() *SharedBucketStopgap {
	m0 := &SharedBucketStopgap{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamSlug = b.TeamSlug
	x.xxx_hidden_ShortName = b.ShortName
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Env = b.Env
	return m0
}

type GetSharedBucketsStopgapRequest struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SharedBucketStopgap *SharedBucketStopgap   `protobuf:"bytes,1,opt,name=shared_bucket_stopgap,json=sharedBucketStopgap,proto3"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GetSharedBucketsStopgapRequest) Reset() {
	*x = GetSharedBucketsStopgapRequest{}
	mi := &file_sharedbucketsstopgap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharedBucketsStopgapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharedBucketsStopgapRequest) ProtoMessage() {}

func (x *GetSharedBucketsStopgapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedbucketsstopgap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSharedBucketsStopgapRequest) GetSharedBucketStopgap() *SharedBucketStopgap {
	if x != nil {
		return x.xxx_hidden_SharedBucketStopgap
	}
	return nil
}

func (x *GetSharedBucketsStopgapRequest) SetSharedBucketStopgap(v *SharedBucketStopgap) {
	x.xxx_hidden_SharedBucketStopgap = v
}

func (x *GetSharedBucketsStopgapRequest) HasSharedBucketStopgap() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SharedBucketStopgap != nil
}

func (x *GetSharedBucketsStopgapRequest) ClearSharedBucketStopgap() {
	x.xxx_hidden_SharedBucketStopgap = nil
}

type GetSharedBucketsStopgapRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SharedBucketStopgap *SharedBucketStopgap
}

func (b0 GetSharedBucketsStopgapRequest_builder) Build() *GetSharedBucketsStopgapRequest {
	m0 := &GetSharedBucketsStopgapRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SharedBucketStopgap = b.SharedBucketStopgap
	return m0
}

type GetSharedBucketsStopgapResponse struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SharedBucketStopgap *SharedBucketStopgap   `protobuf:"bytes,1,opt,name=shared_bucket_stopgap,json=sharedBucketStopgap,proto3"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GetSharedBucketsStopgapResponse) Reset() {
	*x = GetSharedBucketsStopgapResponse{}
	mi := &file_sharedbucketsstopgap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharedBucketsStopgapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharedBucketsStopgapResponse) ProtoMessage() {}

func (x *GetSharedBucketsStopgapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedbucketsstopgap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSharedBucketsStopgapResponse) GetSharedBucketStopgap() *SharedBucketStopgap {
	if x != nil {
		return x.xxx_hidden_SharedBucketStopgap
	}
	return nil
}

func (x *GetSharedBucketsStopgapResponse) SetSharedBucketStopgap(v *SharedBucketStopgap) {
	x.xxx_hidden_SharedBucketStopgap = v
}

func (x *GetSharedBucketsStopgapResponse) HasSharedBucketStopgap() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SharedBucketStopgap != nil
}

func (x *GetSharedBucketsStopgapResponse) ClearSharedBucketStopgap() {
	x.xxx_hidden_SharedBucketStopgap = nil
}

type GetSharedBucketsStopgapResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SharedBucketStopgap *SharedBucketStopgap
}

func (b0 GetSharedBucketsStopgapResponse_builder) Build() *GetSharedBucketsStopgapResponse {
	m0 := &GetSharedBucketsStopgapResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SharedBucketStopgap = b.SharedBucketStopgap
	return m0
}

type CreateSharedBucketsStopgapRequest struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SharedBucketStopgap *SharedBucketStopgap   `protobuf:"bytes,1,opt,name=shared_bucket_stopgap,json=sharedBucketStopgap,proto3"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *CreateSharedBucketsStopgapRequest) Reset() {
	*x = CreateSharedBucketsStopgapRequest{}
	mi := &file_sharedbucketsstopgap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSharedBucketsStopgapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSharedBucketsStopgapRequest) ProtoMessage() {}

func (x *CreateSharedBucketsStopgapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedbucketsstopgap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSharedBucketsStopgapRequest) GetSharedBucketStopgap() *SharedBucketStopgap {
	if x != nil {
		return x.xxx_hidden_SharedBucketStopgap
	}
	return nil
}

func (x *CreateSharedBucketsStopgapRequest) SetSharedBucketStopgap(v *SharedBucketStopgap) {
	x.xxx_hidden_SharedBucketStopgap = v
}

func (x *CreateSharedBucketsStopgapRequest) HasSharedBucketStopgap() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SharedBucketStopgap != nil
}

func (x *CreateSharedBucketsStopgapRequest) ClearSharedBucketStopgap() {
	x.xxx_hidden_SharedBucketStopgap = nil
}

type CreateSharedBucketsStopgapRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SharedBucketStopgap *SharedBucketStopgap
}

func (b0 CreateSharedBucketsStopgapRequest_builder) Build() *CreateSharedBucketsStopgapRequest {
	m0 := &CreateSharedBucketsStopgapRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SharedBucketStopgap = b.SharedBucketStopgap
	return m0
}

type CreateSharedBucketsStopgapResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSharedBucketsStopgapResponse) Reset() {
	*x = CreateSharedBucketsStopgapResponse{}
	mi := &file_sharedbucketsstopgap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSharedBucketsStopgapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSharedBucketsStopgapResponse) ProtoMessage() {}

func (x *CreateSharedBucketsStopgapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedbucketsstopgap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CreateSharedBucketsStopgapResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CreateSharedBucketsStopgapResponse_builder) Build() *CreateSharedBucketsStopgapResponse {
	m0 := &CreateSharedBucketsStopgapResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListSharedBucketsStopgapGroupsRequest struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SharedBucketStopgap *SharedBucketStopgap   `protobuf:"bytes,1,opt,name=shared_bucket_stopgap,json=sharedBucketStopgap,proto3"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ListSharedBucketsStopgapGroupsRequest) Reset() {
	*x = ListSharedBucketsStopgapGroupsRequest{}
	mi := &file_sharedbucketsstopgap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharedBucketsStopgapGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharedBucketsStopgapGroupsRequest) ProtoMessage() {}

func (x *ListSharedBucketsStopgapGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedbucketsstopgap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListSharedBucketsStopgapGroupsRequest) GetSharedBucketStopgap() *SharedBucketStopgap {
	if x != nil {
		return x.xxx_hidden_SharedBucketStopgap
	}
	return nil
}

func (x *ListSharedBucketsStopgapGroupsRequest) SetSharedBucketStopgap(v *SharedBucketStopgap) {
	x.xxx_hidden_SharedBucketStopgap = v
}

func (x *ListSharedBucketsStopgapGroupsRequest) HasSharedBucketStopgap() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SharedBucketStopgap != nil
}

func (x *ListSharedBucketsStopgapGroupsRequest) ClearSharedBucketStopgap() {
	x.xxx_hidden_SharedBucketStopgap = nil
}

type ListSharedBucketsStopgapGroupsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SharedBucketStopgap *SharedBucketStopgap
}

func (b0 ListSharedBucketsStopgapGroupsRequest_builder) Build() *ListSharedBucketsStopgapGroupsRequest {
	m0 := &ListSharedBucketsStopgapGroupsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SharedBucketStopgap = b.SharedBucketStopgap
	return m0
}

type ListSharedBucketsStopgapGroupsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes *[]*Group              `protobuf:"bytes,1,rep,name=nodes,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListSharedBucketsStopgapGroupsResponse) Reset() {
	*x = ListSharedBucketsStopgapGroupsResponse{}
	mi := &file_sharedbucketsstopgap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharedBucketsStopgapGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharedBucketsStopgapGroupsResponse) ProtoMessage() {}

func (x *ListSharedBucketsStopgapGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedbucketsstopgap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListSharedBucketsStopgapGroupsResponse) GetNodes() []*Group {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *ListSharedBucketsStopgapGroupsResponse) SetNodes(v []*Group) {
	x.xxx_hidden_Nodes = &v
}

type ListSharedBucketsStopgapGroupsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes []*Group
}

func (b0 ListSharedBucketsStopgapGroupsResponse_builder) Build() *ListSharedBucketsStopgapGroupsResponse {
	m0 := &ListSharedBucketsStopgapGroupsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = &b.Nodes
	return m0
}

type AddSharedBucketsStopgapGroupRequest struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SharedBucketStopgap *SharedBucketStopgap   `protobuf:"bytes,1,opt,name=shared_bucket_stopgap,json=sharedBucketStopgap,proto3"`
	xxx_hidden_Group               string                 `protobuf:"bytes,2,opt,name=group,proto3"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *AddSharedBucketsStopgapGroupRequest) Reset() {
	*x = AddSharedBucketsStopgapGroupRequest{}
	mi := &file_sharedbucketsstopgap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSharedBucketsStopgapGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSharedBucketsStopgapGroupRequest) ProtoMessage() {}

func (x *AddSharedBucketsStopgapGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedbucketsstopgap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddSharedBucketsStopgapGroupRequest) GetSharedBucketStopgap() *SharedBucketStopgap {
	if x != nil {
		return x.xxx_hidden_SharedBucketStopgap
	}
	return nil
}

func (x *AddSharedBucketsStopgapGroupRequest) GetGroup() string {
	if x != nil {
		return x.xxx_hidden_Group
	}
	return ""
}

func (x *AddSharedBucketsStopgapGroupRequest) SetSharedBucketStopgap(v *SharedBucketStopgap) {
	x.xxx_hidden_SharedBucketStopgap = v
}

func (x *AddSharedBucketsStopgapGroupRequest) SetGroup(v string) {
	x.xxx_hidden_Group = v
}

func (x *AddSharedBucketsStopgapGroupRequest) HasSharedBucketStopgap() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SharedBucketStopgap != nil
}

func (x *AddSharedBucketsStopgapGroupRequest) ClearSharedBucketStopgap() {
	x.xxx_hidden_SharedBucketStopgap = nil
}

type AddSharedBucketsStopgapGroupRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SharedBucketStopgap *SharedBucketStopgap
	Group               string
}

func (b0 AddSharedBucketsStopgapGroupRequest_builder) Build() *AddSharedBucketsStopgapGroupRequest {
	m0 := &AddSharedBucketsStopgapGroupRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SharedBucketStopgap = b.SharedBucketStopgap
	x.xxx_hidden_Group = b.Group
	return m0
}

type AddSharedBucketsStopgapGroupResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSharedBucketsStopgapGroupResponse) Reset() {
	*x = AddSharedBucketsStopgapGroupResponse{}
	mi := &file_sharedbucketsstopgap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSharedBucketsStopgapGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSharedBucketsStopgapGroupResponse) ProtoMessage() {}

func (x *AddSharedBucketsStopgapGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedbucketsstopgap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AddSharedBucketsStopgapGroupResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AddSharedBucketsStopgapGroupResponse_builder) Build() *AddSharedBucketsStopgapGroupResponse {
	m0 := &AddSharedBucketsStopgapGroupResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RemoveSharedBucketsStopgapGroupRequest struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SharedBucketStopgap *SharedBucketStopgap   `protobuf:"bytes,1,opt,name=shared_bucket_stopgap,json=sharedBucketStopgap,proto3"`
	xxx_hidden_Group               string                 `protobuf:"bytes,2,opt,name=group,proto3"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *RemoveSharedBucketsStopgapGroupRequest) Reset() {
	*x = RemoveSharedBucketsStopgapGroupRequest{}
	mi := &file_sharedbucketsstopgap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSharedBucketsStopgapGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSharedBucketsStopgapGroupRequest) ProtoMessage() {}

func (x *RemoveSharedBucketsStopgapGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedbucketsstopgap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RemoveSharedBucketsStopgapGroupRequest) GetSharedBucketStopgap() *SharedBucketStopgap {
	if x != nil {
		return x.xxx_hidden_SharedBucketStopgap
	}
	return nil
}

func (x *RemoveSharedBucketsStopgapGroupRequest) GetGroup() string {
	if x != nil {
		return x.xxx_hidden_Group
	}
	return ""
}

func (x *RemoveSharedBucketsStopgapGroupRequest) SetSharedBucketStopgap(v *SharedBucketStopgap) {
	x.xxx_hidden_SharedBucketStopgap = v
}

func (x *RemoveSharedBucketsStopgapGroupRequest) SetGroup(v string) {
	x.xxx_hidden_Group = v
}

func (x *RemoveSharedBucketsStopgapGroupRequest) HasSharedBucketStopgap() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SharedBucketStopgap != nil
}

func (x *RemoveSharedBucketsStopgapGroupRequest) ClearSharedBucketStopgap() {
	x.xxx_hidden_SharedBucketStopgap = nil
}

type RemoveSharedBucketsStopgapGroupRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SharedBucketStopgap *SharedBucketStopgap
	Group               string
}

func (b0 RemoveSharedBucketsStopgapGroupRequest_builder) Build() *RemoveSharedBucketsStopgapGroupRequest {
	m0 := &RemoveSharedBucketsStopgapGroupRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SharedBucketStopgap = b.SharedBucketStopgap
	x.xxx_hidden_Group = b.Group
	return m0
}

type RemoveSharedBucketsStopgapGroupResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSharedBucketsStopgapGroupResponse) Reset() {
	*x = RemoveSharedBucketsStopgapGroupResponse{}
	mi := &file_sharedbucketsstopgap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSharedBucketsStopgapGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSharedBucketsStopgapGroupResponse) ProtoMessage() {}

func (x *RemoveSharedBucketsStopgapGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedbucketsstopgap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RemoveSharedBucketsStopgapGroupResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RemoveSharedBucketsStopgapGroupResponse_builder) Build() *RemoveSharedBucketsStopgapGroupResponse {
	m0 := &RemoveSharedBucketsStopgapGroupResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_sharedbucketsstopgap_proto protoreflect.FileDescriptor

const file_sharedbucketsstopgap_proto_rawDesc = "" +
	"\n" +
	"\x1asharedbucketsstopgap.proto\x12\x12dapla.api.protobuf\x1a\fgroups.proto\"w\n" +
	"\x13SharedBucketStopgap\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12\x1d\n" +
	"\n" +
	"short_name\x18\x02 \x01(\tR\tshortName\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\"}\n" +
	"\x1eGetSharedBucketsStopgapRequest\x12[\n" +
	"\x15shared_bucket_stopgap\x18\x01 \x01(\v2'.dapla.api.protobuf.SharedBucketStopgapR\x13sharedBucketStopgap\"~\n" +
	"\x1fGetSharedBucketsStopgapResponse\x12[\n" +
	"\x15shared_bucket_stopgap\x18\x01 \x01(\v2'.dapla.api.protobuf.SharedBucketStopgapR\x13sharedBucketStopgap\"\x80\x01\n" +
	"!CreateSharedBucketsStopgapRequest\x12[\n" +
	"\x15shared_bucket_stopgap\x18\x01 \x01(\v2'.dapla.api.protobuf.SharedBucketStopgapR\x13sharedBucketStopgap\"$\n" +
	"\"CreateSharedBucketsStopgapResponse\"\x84\x01\n" +
	"%ListSharedBucketsStopgapGroupsRequest\x12[\n" +
	"\x15shared_bucket_stopgap\x18\x01 \x01(\v2'.dapla.api.protobuf.SharedBucketStopgapR\x13sharedBucketStopgap\"Y\n" +
	"&ListSharedBucketsStopgapGroupsResponse\x12/\n" +
	"\x05nodes\x18\x01 \x03(\v2\x19.dapla.api.protobuf.GroupR\x05nodes\"\x98\x01\n" +
	"#AddSharedBucketsStopgapGroupRequest\x12[\n" +
	"\x15shared_bucket_stopgap\x18\x01 \x01(\v2'.dapla.api.protobuf.SharedBucketStopgapR\x13sharedBucketStopgap\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"&\n" +
	"$AddSharedBucketsStopgapGroupResponse\"\x9b\x01\n" +
	"&RemoveSharedBucketsStopgapGroupRequest\x12[\n" +
	"\x15shared_bucket_stopgap\x18\x01 \x01(\v2'.dapla.api.protobuf.SharedBucketStopgapR\x13sharedBucketStopgap\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\")\n" +
	"'RemoveSharedBucketsStopgapGroupResponse2\x93\x05\n" +
	"\x14SharedBucketsStopgap\x12y\n" +
	"\x06Create\x125.dapla.api.protobuf.CreateSharedBucketsStopgapRequest\x1a6.dapla.api.protobuf.CreateSharedBucketsStopgapResponse\"\x00\x12p\n" +
	"\x03Get\x122.dapla.api.protobuf.GetSharedBucketsStopgapRequest\x1a3.dapla.api.protobuf.GetSharedBucketsStopgapResponse\"\x00\x12\x81\x01\n" +
	"\x06Groups\x129.dapla.api.protobuf.ListSharedBucketsStopgapGroupsRequest\x1a:.dapla.api.protobuf.ListSharedBucketsStopgapGroupsResponse\"\x00\x12\x7f\n" +
	"\bAddGroup\x127.dapla.api.protobuf.AddSharedBucketsStopgapGroupRequest\x1a8.dapla.api.protobuf.AddSharedBucketsStopgapGroupResponse\"\x00\x12\x88\x01\n" +
	"\vRemoveGroup\x12:.dapla.api.protobuf.RemoveSharedBucketsStopgapGroupRequest\x1a;.dapla.api.protobuf.RemoveSharedBucketsStopgapGroupResponse\"\x00B\x1aZ\x18./pkg/apiclient/protoapib\x06proto3"

var file_sharedbucketsstopgap_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sharedbucketsstopgap_proto_goTypes = []any{
	(*SharedBucketStopgap)(nil),                     // 0: dapla.api.protobuf.SharedBucketStopgap
	(*GetSharedBucketsStopgapRequest)(nil),          // 1: dapla.api.protobuf.GetSharedBucketsStopgapRequest
	(*GetSharedBucketsStopgapResponse)(nil),         // 2: dapla.api.protobuf.GetSharedBucketsStopgapResponse
	(*CreateSharedBucketsStopgapRequest)(nil),       // 3: dapla.api.protobuf.CreateSharedBucketsStopgapRequest
	(*CreateSharedBucketsStopgapResponse)(nil),      // 4: dapla.api.protobuf.CreateSharedBucketsStopgapResponse
	(*ListSharedBucketsStopgapGroupsRequest)(nil),   // 5: dapla.api.protobuf.ListSharedBucketsStopgapGroupsRequest
	(*ListSharedBucketsStopgapGroupsResponse)(nil),  // 6: dapla.api.protobuf.ListSharedBucketsStopgapGroupsResponse
	(*AddSharedBucketsStopgapGroupRequest)(nil),     // 7: dapla.api.protobuf.AddSharedBucketsStopgapGroupRequest
	(*AddSharedBucketsStopgapGroupResponse)(nil),    // 8: dapla.api.protobuf.AddSharedBucketsStopgapGroupResponse
	(*RemoveSharedBucketsStopgapGroupRequest)(nil),  // 9: dapla.api.protobuf.RemoveSharedBucketsStopgapGroupRequest
	(*RemoveSharedBucketsStopgapGroupResponse)(nil), // 10: dapla.api.protobuf.RemoveSharedBucketsStopgapGroupResponse
	(*Group)(nil), // 11: dapla.api.protobuf.Group
}
var file_sharedbucketsstopgap_proto_depIdxs = []int32{
	0,  // 0: dapla.api.protobuf.GetSharedBucketsStopgapRequest.shared_bucket_stopgap:type_name -> dapla.api.protobuf.SharedBucketStopgap
	0,  // 1: dapla.api.protobuf.GetSharedBucketsStopgapResponse.shared_bucket_stopgap:type_name -> dapla.api.protobuf.SharedBucketStopgap
	0,  // 2: dapla.api.protobuf.CreateSharedBucketsStopgapRequest.shared_bucket_stopgap:type_name -> dapla.api.protobuf.SharedBucketStopgap
	0,  // 3: dapla.api.protobuf.ListSharedBucketsStopgapGroupsRequest.shared_bucket_stopgap:type_name -> dapla.api.protobuf.SharedBucketStopgap
	11, // 4: dapla.api.protobuf.ListSharedBucketsStopgapGroupsResponse.nodes:type_name -> dapla.api.protobuf.Group
	0,  // 5: dapla.api.protobuf.AddSharedBucketsStopgapGroupRequest.shared_bucket_stopgap:type_name -> dapla.api.protobuf.SharedBucketStopgap
	0,  // 6: dapla.api.protobuf.RemoveSharedBucketsStopgapGroupRequest.shared_bucket_stopgap:type_name -> dapla.api.protobuf.SharedBucketStopgap
	3,  // 7: dapla.api.protobuf.SharedBucketsStopgap.Create:input_type -> dapla.api.protobuf.CreateSharedBucketsStopgapRequest
	1,  // 8: dapla.api.protobuf.SharedBucketsStopgap.Get:input_type -> dapla.api.protobuf.GetSharedBucketsStopgapRequest
	5,  // 9: dapla.api.protobuf.SharedBucketsStopgap.Groups:input_type -> dapla.api.protobuf.ListSharedBucketsStopgapGroupsRequest
	7,  // 10: dapla.api.protobuf.SharedBucketsStopgap.AddGroup:input_type -> dapla.api.protobuf.AddSharedBucketsStopgapGroupRequest
	9,  // 11: dapla.api.protobuf.SharedBucketsStopgap.RemoveGroup:input_type -> dapla.api.protobuf.RemoveSharedBucketsStopgapGroupRequest
	4,  // 12: dapla.api.protobuf.SharedBucketsStopgap.Create:output_type -> dapla.api.protobuf.CreateSharedBucketsStopgapResponse
	2,  // 13: dapla.api.protobuf.SharedBucketsStopgap.Get:output_type -> dapla.api.protobuf.GetSharedBucketsStopgapResponse
	6,  // 14: dapla.api.protobuf.SharedBucketsStopgap.Groups:output_type -> dapla.api.protobuf.ListSharedBucketsStopgapGroupsResponse
	8,  // 15: dapla.api.protobuf.SharedBucketsStopgap.AddGroup:output_type -> dapla.api.protobuf.AddSharedBucketsStopgapGroupResponse
	10, // 16: dapla.api.protobuf.SharedBucketsStopgap.RemoveGroup:output_type -> dapla.api.protobuf.RemoveSharedBucketsStopgapGroupResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_sharedbucketsstopgap_proto_init() }
func file_sharedbucketsstopgap_proto_init() {
	if File_sharedbucketsstopgap_proto != nil {
		return
	}
	file_groups_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sharedbucketsstopgap_proto_rawDesc), len(file_sharedbucketsstopgap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sharedbucketsstopgap_proto_goTypes,
		DependencyIndexes: file_sharedbucketsstopgap_proto_depIdxs,
		MessageInfos:      file_sharedbucketsstopgap_proto_msgTypes,
	}.Build()
	File_sharedbucketsstopgap_proto = out.File
	file_sharedbucketsstopgap_proto_goTypes = nil
	file_sharedbucketsstopgap_proto_depIdxs = nil
}
