query LaunchLab($team: Slug!) {
	team(slug: $team) {
		id
		viewerTeamMember {
			groups {
				id
				name
				sharedBucketsAccess {
					nodes {
						id
						team {
							id
							slug
							displayName
						}
						name
						shortName
						env
						kind
					}
				}
			}
		}
	}
}
