name: Kildomaten

permissions:
  contents: "read"
  id-token: "write"
  issues: "write"
  pull-requests: "write"
  statuses: "read"

on:
  pull_request:
    branches: [ "main" ]
    paths: ["automation/source-data/**"]
  push:
    branches: [ "main" ]
    paths: ["automation/source-data/**"]
  pull_request_review:
    types: [submitted, edited]
  workflow_dispatch:

jobs:
  kildomaten:
    uses: statisticsnorway/dapla-source-data-processor-build-scripts/.github/workflows/kildomaten.yaml@main
    secrets: inherit
