apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dapla-api
  title: Dapla API
  description: |
    Management Service for Dapla teams and their resources
  tags:
    - go
    - dapla
    - graphql
  annotations:
    github.com/project-slug: statisticsnorway/dapla-ctrl
spec:
  type: service
  owner: dapla-skyinfra-developers
  lifecycle: production
  system: kuben
  dependsOn:
    - component:sup-postman
    - system:nais
  providesApis:
    - dapla-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dapla-api
  description: Management API for Dapla teams and their resources
spec:
  type: graphql
  lifecycle: production
  owner: dapla-skyinfra-developers
  system: kuben
  definition:
    $text: ./api/internal/graph/schema
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dapla-api-internal
  description: Internal API used for resource reconciliation
spec:
  type: grpc
  lifecycle: production
  owner: dapla-skyinfra-developers
  system: kuben
  definition:
    $text: ./api/pkg/apiclient/protoapi/schema
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dapla-ctrl
  title: Dapla Ctrl
  description: |
    Web interface for managing Dapla teams and their resources
  tags:
    - typescript
    - sveltekit
    - dapla
  annotations:
    github.com/project-slug: statisticsnorway/dapla-ctrl
spec:
  type: website
  owner: dapla-skyinfra-developers
  lifecycle: production
  system: kuben
  dependsOn:
    - system:nais
  consumesApis:
    - api:dapla-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dapla-api-reconcilers
  title: Dapla API Reconcilers
  description: |
    Reconciliation service for resources defined by Dapla API
  tags:
    - go
    - dapla
  annotations:
    github.com/project-slug: statisticsnorway/dapla-ctrl
spec:
  type: service
  owner: dapla-skyinfra-developers
  lifecycle: production
  system: kuben
  consumesApis:
    - api:dapla-api-internal
