apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: dapla-ctrl
spec:
  type: url
  targets:
    - ./api/backstage.yaml
    - ./frontend/backstage.yaml
    - ./reconcilers/backstage.yaml
