allowBuilds:
  esbuild: set this to true or false
autoInstallPeers: false
lockfile: true
# https://pnpm.io/settings
minimumReleaseAge: 10080 # 7 days, 60min*24 hour * 7days
saveExact: false
strictSsl: true
