query UserTeams @cache(policy: CacheAndNetwork) {
	me {
		__typename
		... on User {
			teams(first: 25) @paginate(mode: SinglePage) {
				pageInfo {
					hasNextPage
					hasPreviousPage
					pageEnd
					pageStart
					startCursor
					endCursor
					totalCount
				}
				nodes {
					groups {
						id
						name
					}
					team {
						id
						slug
						purpose
						displayName
						section {
							code
							name
							manager {
								name
								email
							}
						}
						members {
							pageInfo {
								totalCount
							}
						}
					}
				}
			}
		}
	}
	teams(first: 1) {
		pageInfo {
			totalCount
		}
	}
}
