apiVersion: "monitoring.coreos.com/v1"
kind: PrometheusRule
metadata:
  name: alert-dapla-ctrl
  namespace: dapla-stat
  labels:
    team: dapla-stat
spec:
  groups:
    - name: dapla-stat
      rules:
        - alert: High number of errors
          expr: (100 * sum by (app, namespace) (rate(log_messages_errors{app="dapla-ctrl",level=~"Error"}[3m])) / sum by (app, namespace) (rate(log_messages_total{app="dapla-ctrl"}[3m]))) > 10
          for: 3m
          annotations:
            title: "High number of errors logged"
            consequence: "There can be different causes for errors, check logs for cause and evaluation of consequences."
            action: "`kubectl describe pod -l app=dapla-ctrl -n dapla-stat` -> `kubectl logs <podname>`"
          labels:
            service: dapla-ctrl
            namespace: dapla-stat
            severity: critical

        - alert: Dapla Ctrl is unavailable
          expr: kube_deployment_status_replicas_available{deployment="dapla-ctrl"} == 0
          for: 1m
          annotations:
            title: "Dapla Ctrl is unavailable"
            consequence: "Service is unavailable to users."
          labels:
            service: dapla-ctrl
            namespace: dapla-stat
            severity: critical
