// Code generated by metago; DO NOT EDIT.

package serviceaccount

import (
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/pagination"
)

type (
	ServiceAccountConnection = pagination.Connection[*ServiceAccount]
	ServiceAccountEdge       = pagination.Edge[*ServiceAccount]
)

func (ServiceAccount) IsNode() {}

type (
	ServiceAccountTokenConnection = pagination.Connection[*ServiceAccountToken]
	ServiceAccountTokenEdge       = pagination.Edge[*ServiceAccountToken]
)

func (ServiceAccountToken) IsNode() {}
