// Code generated by ./cmd/gen_complexity, DO NOT EDIT.

package gengql

import (
	pagination "github.com/statisticsnorway/dapla-api/internal/graph/pagination"
	group "github.com/statisticsnorway/dapla-api/internal/group"
	search "github.com/statisticsnorway/dapla-api/internal/search"
	team "github.com/statisticsnorway/dapla-api/internal/team"
	user "github.com/statisticsnorway/dapla-api/internal/user"
)

func NewComplexityRoot() ComplexityRoot {
	c := ComplexityRoot{}

	c.Group.Members = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *group.GroupMemberOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Groups = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *group.GroupOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Reconcilers = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Roles = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Search = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, filter search.SearchFilter) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.ServiceAccounts = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Teams = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *team.TeamOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.UserSyncLog = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Users = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *user.UserOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Reconciler.ActivityLog = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Reconciler.Errors = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.ServiceAccount.Roles = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.ServiceAccount.Tokens = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Team.ActivityLog = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Team.Groups = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *group.GroupOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Team.Members = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *team.TeamMemberOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.User.Teams = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *team.UserTeamOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}

	return c
}

func cursorComplexity(first, last *int) int {
	if first != nil {
		return *first
	}
	if last != nil {
		return *last
	}
	return pagination.DefaultPageSize
}
