// Code generated by ./cmd/gen_complexity, DO NOT EDIT.

package gengql

import (
	activitylog "github.com/statisticsnorway/dapla-api/internal/activitylog"
	pagination "github.com/statisticsnorway/dapla-api/internal/graph/pagination"
	group "github.com/statisticsnorway/dapla-api/internal/group"
	search "github.com/statisticsnorway/dapla-api/internal/search"
	section "github.com/statisticsnorway/dapla-api/internal/section"
	sharedbucketsstopgap "github.com/statisticsnorway/dapla-api/internal/sharedbucketsstopgap"
	team "github.com/statisticsnorway/dapla-api/internal/team"
	user "github.com/statisticsnorway/dapla-api/internal/user"
)

func NewComplexityRoot() ComplexityRoot {
	c := ComplexityRoot{}

	c.Group.ActivityLog = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, filter *activitylog.ActivityLogFilter) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Group.Members = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *group.GroupMemberOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.ActivityLog = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, filter *activitylog.ActivityLogFilter) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Groups = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *group.GroupOrder, filter *group.GroupFilter) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Reconcilers = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Roles = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Search = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, filter search.SearchFilter) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Sections = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *section.SectionOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.ServiceAccounts = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.SharedBuckets = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *sharedbucketsstopgap.SharedBucketOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Teams = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *team.TeamOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.UserSyncLog = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Query.Users = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *user.UserOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Reconciler.ActivityLog = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, filter *activitylog.ActivityLogFilter) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Reconciler.Errors = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.ServiceAccount.Roles = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.ServiceAccount.Tokens = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.SharedBucket.Groups = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.SharedBucket.Teams = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *team.TeamOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.SharedBucket.UniqueUsers = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *user.UserOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.SharedBucket.Users = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *team.TeamMemberOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Team.ActivityLog = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, filter *activitylog.ActivityLogFilter) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Team.Groups = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *group.GroupOrder, filter *group.GroupFilter) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Team.Members = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *team.TeamMemberOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.Team.SharedBuckets = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *sharedbucketsstopgap.SharedBucketOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.User.Groups = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *group.UserGroupOrder, filter *group.GroupFilter) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.User.SharedBucketsAccess = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *sharedbucketsstopgap.SharedBucketOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.User.TeamMembers = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *user.UserOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}
	c.User.Teams = func(childComplexity int, first *int, after *pagination.Cursor, last *int, before *pagination.Cursor, orderBy *team.UserTeamOrder) int {
		return cursorComplexity(first, last) * childComplexity
	}

	return c
}

func cursorComplexity(first, last *int) int {
	if first != nil {
		return *first
	}
	if last != nil {
		return *last
	}
	return pagination.DefaultPageSize
}
