// Code generated by sqlc. DO NOT EDIT.
// source: buckets.sql

package teambucketssql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

const getByName = `-- name: GetByName :one
SELECT
	name, team_slug, kind, env
FROM
	(
		SELECT
			FORMAT('ssb-%s-data-%s-%s', t.slug, tbs.kind, tbs.env) AS name,
			t.slug AS team_slug,
			tbs.kind,
			tbs.env
		FROM
			teams t
			CROSS JOIN team_bucket_specs tbs
		WHERE
			t.is_managed = TRUE
	) X
WHERE
	name = $1::TEXT
`

type GetByNameRow struct {
	Name     string
	TeamSlug slug.Slug
	Kind     string
	Env      string
}

func (q *Queries) GetByName(ctx context.Context, name string) (*GetByNameRow, error) {
	row := q.db.QueryRow(ctx, getByName, name)
	var i GetByNameRow
	err := row.Scan(
		&i.Name,
		&i.TeamSlug,
		&i.Kind,
		&i.Env,
	)
	return &i, err
}

const getByNames = `-- name: GetByNames :many
SELECT
	name, team_slug, kind, env
FROM
	(
		SELECT
			FORMAT('ssb-%s-data-%s-%s', t.slug, tbs.kind, tbs.env) AS name,
			t.slug AS team_slug,
			tbs.kind,
			tbs.env
		FROM
			teams t
			CROSS JOIN team_bucket_specs tbs
		WHERE
			t.is_managed = TRUE
	) X
WHERE
	name = ANY ($1::TEXT[])
ORDER BY
	name
`

type GetByNamesRow struct {
	Name     string
	TeamSlug slug.Slug
	Kind     string
	Env      string
}

func (q *Queries) GetByNames(ctx context.Context, names []string) ([]*GetByNamesRow, error) {
	rows, err := q.db.Query(ctx, getByNames, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetByNamesRow{}
	for rows.Next() {
		var i GetByNamesRow
		if err := rows.Scan(
			&i.Name,
			&i.TeamSlug,
			&i.Kind,
			&i.Env,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const list = `-- name: List :many
SELECT
	name, team_slug, kind, env,
	COUNT(*) OVER () AS total_count
FROM
	(
		SELECT
			FORMAT('ssb-%s-data-%s-%s', t.slug, tbs.kind, tbs.env) AS name,
			t.slug AS team_slug,
			tbs.kind,
			tbs.env
		FROM
			teams t
			CROSS JOIN team_bucket_specs tbs
		WHERE
			t.is_managed = TRUE
	) X
WHERE
	(
		$1::TEXT[] IS NULL
		OR (kind) = ANY ($1::TEXT[])
	)
	AND (
		$2::TEXT[] IS NULL
		OR (env) = ANY ($2::TEXT[])
	)
ORDER BY
	CASE
		WHEN $3::TEXT = 'name:asc' THEN name
	END ASC,
	CASE
		WHEN $3::TEXT = 'name:desc' THEN name
	END DESC,
	CASE
		WHEN $3::TEXT = 'kind:asc' THEN kind
	END ASC,
	CASE
		WHEN $3::TEXT = 'kind:desc' THEN kind
	END DESC,
	CASE
		WHEN $3::TEXT = 'env:asc' THEN env
	END ASC,
	CASE
		WHEN $3::TEXT = 'env:desc' THEN env
	END DESC,
	CASE
		WHEN $3::TEXT = 'team:asc' THEN team_slug
	END ASC,
	CASE
		WHEN $3::TEXT = 'team:desc' THEN team_slug
	END DESC,
	team_slug ASC
LIMIT
	$5
OFFSET
	$4
`

type ListParams struct {
	Kinds   []string
	Envs    []string
	OrderBy string
	Offset  int32
	Limit   int32
}

type ListRow struct {
	Name       string
	TeamSlug   slug.Slug
	Kind       string
	Env        string
	TotalCount int64
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]*ListRow, error) {
	rows, err := q.db.Query(ctx, list,
		arg.Kinds,
		arg.Envs,
		arg.OrderBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListRow{}
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(
			&i.Name,
			&i.TeamSlug,
			&i.Kind,
			&i.Env,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForTeam = `-- name: ListForTeam :many
SELECT
	name, team_slug, kind, env,
	COUNT(*) OVER () AS total_count
FROM
	(
		SELECT
			FORMAT('ssb-%s-data-%s-%s', t.slug, tbs.kind, tbs.env) AS name,
			t.slug AS team_slug,
			tbs.kind,
			tbs.env
		FROM
			teams t
			CROSS JOIN team_bucket_specs tbs
		WHERE
			t.is_managed = TRUE
	) X
WHERE
	team_slug = $1::slug
	AND (
		$2::TEXT[] IS NULL
		OR (kind) = ANY ($2::TEXT[])
	)
	AND (
		$3::TEXT[] IS NULL
		OR (env) = ANY ($3::TEXT[])
	)
ORDER BY
	CASE
		WHEN $4::TEXT = 'name:asc' THEN name
	END ASC,
	CASE
		WHEN $4::TEXT = 'name:desc' THEN name
	END DESC,
	CASE
		WHEN $4::TEXT = 'kind:asc' THEN kind
	END ASC,
	CASE
		WHEN $4::TEXT = 'kind:desc' THEN kind
	END DESC,
	CASE
		WHEN $4::TEXT = 'env:asc' THEN env
	END ASC,
	CASE
		WHEN $4::TEXT = 'env:desc' THEN env
	END DESC,
	CASE
		WHEN $4::TEXT = 'team:asc' THEN team_slug
	END ASC,
	CASE
		WHEN $4::TEXT = 'team:desc' THEN team_slug
	END DESC,
	team_slug ASC
LIMIT
	$6
OFFSET
	$5
`

type ListForTeamParams struct {
	TeamSlug slug.Slug
	Kinds    []string
	Envs     []string
	OrderBy  string
	Offset   int32
	Limit    int32
}

type ListForTeamRow struct {
	Name       string
	TeamSlug   slug.Slug
	Kind       string
	Env        string
	TotalCount int64
}

func (q *Queries) ListForTeam(ctx context.Context, arg ListForTeamParams) ([]*ListForTeamRow, error) {
	rows, err := q.db.Query(ctx, listForTeam,
		arg.TeamSlug,
		arg.Kinds,
		arg.Envs,
		arg.OrderBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListForTeamRow{}
	for rows.Next() {
		var i ListForTeamRow
		if err := rows.Scan(
			&i.Name,
			&i.TeamSlug,
			&i.Kind,
			&i.Env,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
