// Code generated by sqlc. DO NOT EDIT.

package teambucketssql

import (
	"context"
)

type Querier interface {
	GetByName(ctx context.Context, name string) (*GetByNameRow, error)
	GetByNames(ctx context.Context, names []string) ([]*GetByNamesRow, error)
	List(ctx context.Context, arg ListParams) ([]*ListRow, error)
	ListForTeam(ctx context.Context, arg ListForTeamParams) ([]*ListForTeamRow, error)
}

var _ Querier = (*Queries)(nil)
