// Code generated by sqlc. DO NOT EDIT.

package grpcatlantissql

import (
	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

type TeamAtlantisConfig struct {
	TeamSlug      slug.Slug
	CustomName    *string
	WebhookSecret *string
	CustomImage   *string
	Resources     *string
	DiskSize      *string
}
