// Code generated by sqlc. DO NOT EDIT.

package grpcatlantissql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

type Querier interface {
	Get(ctx context.Context, teamSlug slug.Slug) (*GetRow, error)
	Set(ctx context.Context, arg SetParams) (interface{}, error)
}

var _ Querier = (*Queries)(nil)
