// Code generated by sqlc. DO NOT EDIT.
// source: repos.sql

package grpcatlantissql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

const get = `-- name: Get :one
SELECT
    team_atlantis_config.team_slug, team_atlantis_config.webhook_secret
FROM team_atlantis_config
WHERE
    team_slug = $1::slug
`

type GetRow struct {
	TeamAtlantisConfig TeamAtlantisConfig
}

func (q *Queries) Get(ctx context.Context, teamSlug slug.Slug) (*GetRow, error) {
	row := q.db.QueryRow(ctx, get, teamSlug)
	var i GetRow
	err := row.Scan(&i.TeamAtlantisConfig.TeamSlug, &i.TeamAtlantisConfig.WebhookSecret)
	return &i, err
}

const upsertWebhookSecret = `-- name: UpsertWebhookSecret :exec
INSERT INTO
    team_atlantis_config (team_slug, webhook_secret)
VALUES
    ($1, $2)
ON CONFLICT (team_slug) DO UPDATE
SET
    webhook_secret = EXCLUDED.webhook_secret
`

type UpsertWebhookSecretParams struct {
	TeamSlug      slug.Slug
	WebhookSecret *string
}

func (q *Queries) UpsertWebhookSecret(ctx context.Context, arg UpsertWebhookSecretParams) error {
	_, err := q.db.Exec(ctx, upsertWebhookSecret, arg.TeamSlug, arg.WebhookSecret)
	return err
}
