// Code generated by sqlc. DO NOT EDIT.
// source: repos.sql

package grpcatlantissql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

const get = `-- name: Get :one
SELECT
    team_atlantis_config.team_slug, team_atlantis_config.webhook_secret
FROM team_atlantis_config
WHERE
    team_slug = $1::slug
`

type GetRow struct {
	TeamAtlantisConfig TeamAtlantisConfig
}

func (q *Queries) Get(ctx context.Context, teamSlug slug.Slug) (*GetRow, error) {
	row := q.db.QueryRow(ctx, get, teamSlug)
	var i GetRow
	err := row.Scan(&i.TeamAtlantisConfig.TeamSlug, &i.TeamAtlantisConfig.WebhookSecret)
	return &i, err
}

const set = `-- name: Set :one
UPDATE team_atlantis_config
SET
    webhook_secret = $1
WHERE
    team_slug = $2::slug
RETURNING
    sql.embed(team_atlantis_config)
`

type SetParams struct {
	WebhookSecret *string
	TeamSlug      slug.Slug
}

func (q *Queries) Set(ctx context.Context, arg SetParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, set, arg.WebhookSecret, arg.TeamSlug)
	var embed interface{}
	err := row.Scan(&embed)
	return embed, err
}
