// Code generated by sqlc. DO NOT EDIT.
// source: groups.sql

package groupsql

import (
	"context"

	"github.com/statisticsnorway/dapla-api/internal/slug"
)

const create = `-- name: Create :one
INSERT INTO
	groups (name, team_slug, category, suffix, external_id)
VALUES
	(
		$1,
		$2,
		$3,
		$4,
		$5
	)
RETURNING
	name, team_slug, category, suffix, external_id
`

type CreateParams struct {
	Name       string
	TeamSlug   slug.Slug
	Category   string
	Suffix     string
	ExternalID *string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*Group, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Name,
		arg.TeamSlug,
		arg.Category,
		arg.Suffix,
		arg.ExternalID,
	)
	var i Group
	err := row.Scan(
		&i.Name,
		&i.TeamSlug,
		&i.Category,
		&i.Suffix,
		&i.ExternalID,
	)
	return &i, err
}

const get = `-- name: Get :one
SELECT
	name, team_slug, category, suffix, external_id
FROM
	groups
WHERE
	name = $1
`

func (q *Queries) Get(ctx context.Context, name string) (*Group, error) {
	row := q.db.QueryRow(ctx, get, name)
	var i Group
	err := row.Scan(
		&i.Name,
		&i.TeamSlug,
		&i.Category,
		&i.Suffix,
		&i.ExternalID,
	)
	return &i, err
}

const getByNames = `-- name: GetByNames :many
SELECT
	name, team_slug, category, suffix, external_id
FROM
	groups
WHERE
	name = ANY ($1::TEXT[])
ORDER BY
	team_slug,
	category,
	suffix
`

func (q *Queries) GetByNames(ctx context.Context, ids []string) ([]*Group, error) {
	rows, err := q.db.Query(ctx, getByNames, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.Name,
			&i.TeamSlug,
			&i.Category,
			&i.Suffix,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupExists = `-- name: GroupExists :one
SELECT
	EXISTS (
		SELECT
			team_slug,
			category,
			suffix
		FROM
			groups
		WHERE
			team_slug = $1
			AND category = $2
			AND suffix = $3
	)
`

type GroupExistsParams struct {
	TeamSlug slug.Slug
	Category string
	Suffix   string
}

func (q *Queries) GroupExists(ctx context.Context, arg GroupExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupExists, arg.TeamSlug, arg.Category, arg.Suffix)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const list = `-- name: List :many
SELECT
	groups.name, groups.team_slug, groups.category, groups.suffix, groups.external_id,
	COUNT(*) OVER () AS total_count
FROM
	groups
ORDER BY
	CASE
		WHEN $1::TEXT = 'slug:asc' THEN team_slug
	END ASC,
	CASE
		WHEN $1::TEXT = 'slug:desc' THEN team_slug
	END DESC,
	team_slug ASC
LIMIT
	$3
OFFSET
	$2
`

type ListParams struct {
	OrderBy string
	Offset  int32
	Limit   int32
}

type ListRow struct {
	Group      Group
	TotalCount int64
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]*ListRow, error) {
	rows, err := q.db.Query(ctx, list, arg.OrderBy, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListRow{}
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(
			&i.Group.Name,
			&i.Group.TeamSlug,
			&i.Group.Category,
			&i.Group.Suffix,
			&i.Group.ExternalID,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByTeamSlug = `-- name: ListByTeamSlug :many
SELECT
	name, team_slug, category, suffix, external_id
FROM
	groups
WHERE
	team_slug = $1::slug
ORDER BY
	CASE
		WHEN $2::TEXT = 'slug:asc' THEN team_slug
	END ASC,
	CASE
		WHEN $2::TEXT = 'slug:desc' THEN team_slug
	END DESC,
	team_slug ASC
`

type ListByTeamSlugParams struct {
	TeamSlug slug.Slug
	OrderBy  string
}

func (q *Queries) ListByTeamSlug(ctx context.Context, arg ListByTeamSlugParams) ([]*Group, error) {
	rows, err := q.db.Query(ctx, listByTeamSlug, arg.TeamSlug, arg.OrderBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.Name,
			&i.TeamSlug,
			&i.Category,
			&i.Suffix,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamExists = `-- name: TeamExists :one
SELECT
	EXISTS (
		SELECT
			slug
		FROM
			teams
		WHERE
			slug = $1
			AND delete_key_confirmed_at IS NULL
	)
`

func (q *Queries) TeamExists(ctx context.Context, argSlug slug.Slug) (bool, error) {
	row := q.db.QueryRow(ctx, teamExists, argSlug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
