// Code generated by sqlc. DO NOT EDIT.
// source: group_members.sql

package groupsql

import (
	"context"

	"github.com/google/uuid"
	"github.com/statisticsnorway/dapla-api/internal/slug"
)

const addMember = `-- name: AddMember :exec
INSERT INTO
	group_members (group_name, user_id)
VALUES
	($1, $2)
ON CONFLICT DO NOTHING
`

type AddMemberParams struct {
	GroupName string
	UserID    uuid.UUID
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.GroupName, arg.UserID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT
	users.id, users.email, users.name, users.external_id, users.admin
FROM
	group_members
	JOIN users ON users.id = group_members.user_id
WHERE
	group_members.group_name = $1
	AND group_members.user_id = $2
`

type GetMemberParams struct {
	GroupName string
	UserID    uuid.UUID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (*User, error) {
	row := q.db.QueryRow(ctx, getMember, arg.GroupName, arg.UserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.ExternalID,
		&i.Admin,
	)
	return &i, err
}

const getMemberByEmail = `-- name: GetMemberByEmail :one
SELECT
	users.id, users.email, users.name, users.external_id, users.admin
FROM
	group_members
	JOIN users ON users.id = group_members.user_id
WHERE
	group_members.group_name = $1
	AND users.email = $2
`

type GetMemberByEmailParams struct {
	GroupName string
	Email     string
}

func (q *Queries) GetMemberByEmail(ctx context.Context, arg GetMemberByEmailParams) (*User, error) {
	row := q.db.QueryRow(ctx, getMemberByEmail, arg.GroupName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.ExternalID,
		&i.Admin,
	)
	return &i, err
}

const listForTeamMember = `-- name: ListForTeamMember :many
SELECT
	groups.name, groups.team_slug, groups.category, groups.suffix, groups.external_id,
	COUNT(*) OVER () AS total_count
FROM
	group_members
	JOIN groups ON groups.name = group_members.group_name
	JOIN users ON users.id = group_members.user_id
WHERE
	group_members.user_id = $1
	AND groups.team_slug = $2
ORDER BY
	CASE
		WHEN $3::TEXT = 'name:asc' THEN groups.name
	END ASC,
	CASE
		WHEN $3::TEXT = 'name:desc' THEN groups.name
	END DESC,
	groups.name ASC
`

type ListForTeamMemberParams struct {
	UserID   uuid.UUID
	TeamSlug slug.Slug
	OrderBy  string
}

type ListForTeamMemberRow struct {
	Group      Group
	TotalCount int64
}

func (q *Queries) ListForTeamMember(ctx context.Context, arg ListForTeamMemberParams) ([]*ListForTeamMemberRow, error) {
	rows, err := q.db.Query(ctx, listForTeamMember, arg.UserID, arg.TeamSlug, arg.OrderBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListForTeamMemberRow{}
	for rows.Next() {
		var i ListForTeamMemberRow
		if err := rows.Scan(
			&i.Group.Name,
			&i.Group.TeamSlug,
			&i.Group.Category,
			&i.Group.Suffix,
			&i.Group.ExternalID,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForUser = `-- name: ListForUser :many
SELECT
	users.id, users.email, users.name, users.external_id, users.admin,
	groups.name, groups.team_slug, groups.category, groups.suffix, groups.external_id,
	COUNT(*) OVER () AS total_count
FROM
	group_members
	JOIN groups ON groups.name = group_members.group_name
	JOIN users ON users.id = group_members.user_id
WHERE
	group_members.user_id = $1
ORDER BY
	CASE
		WHEN $2::TEXT = 'slug:asc' THEN groups.team_slug
	END ASC,
	CASE
		WHEN $2::TEXT = 'slug:desc' THEN groups.team_slug
	END DESC,
	groups.team_slug ASC
LIMIT
	$4
OFFSET
	$3
`

type ListForUserParams struct {
	UserID  uuid.UUID
	OrderBy string
	Offset  int32
	Limit   int32
}

type ListForUserRow struct {
	User       User
	Group      Group
	TotalCount int64
}

func (q *Queries) ListForUser(ctx context.Context, arg ListForUserParams) ([]*ListForUserRow, error) {
	rows, err := q.db.Query(ctx, listForUser,
		arg.UserID,
		arg.OrderBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListForUserRow{}
	for rows.Next() {
		var i ListForUserRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Email,
			&i.User.Name,
			&i.User.ExternalID,
			&i.User.Admin,
			&i.Group.Name,
			&i.Group.TeamSlug,
			&i.Group.Category,
			&i.Group.Suffix,
			&i.Group.ExternalID,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT
	users.id, users.email, users.name, users.external_id, users.admin,
	groups.name, groups.team_slug, groups.category, groups.suffix, groups.external_id,
	COUNT(*) OVER () AS total_count
FROM
	group_members
	JOIN groups ON groups.name = group_members.group_name
	JOIN users ON users.id = group_members.user_id
WHERE
	group_members.group_name = $1
ORDER BY
	CASE
		WHEN $2::TEXT = 'name:asc' THEN LOWER(users.name)
	END ASC,
	CASE
		WHEN $2::TEXT = 'name:desc' THEN LOWER(users.name)
	END DESC,
	CASE
		WHEN $2::TEXT = 'email:asc' THEN users.email
	END ASC,
	CASE
		WHEN $2::TEXT = 'email:desc' THEN users.email
	END DESC,
	users.name,
	users.email ASC
LIMIT
	$4
OFFSET
	$3
`

type ListMembersParams struct {
	GroupName string
	OrderBy   string
	Offset    int32
	Limit     int32
}

type ListMembersRow struct {
	User       User
	Group      Group
	TotalCount int64
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]*ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers,
		arg.GroupName,
		arg.OrderBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Email,
			&i.User.Name,
			&i.User.ExternalID,
			&i.User.Admin,
			&i.Group.Name,
			&i.Group.TeamSlug,
			&i.Group.Category,
			&i.Group.Suffix,
			&i.Group.ExternalID,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM group_members
WHERE
	user_id = $1
	AND group_name = $2
`

type RemoveMemberParams struct {
	UserID    uuid.UUID
	GroupName string
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.UserID, arg.GroupName)
	return err
}
