// Code generated by sqlc. DO NOT EDIT.

package groupsql

import (
	"github.com/google/uuid"
	"github.com/statisticsnorway/dapla-api/internal/slug"
)

type Group struct {
	Name       string
	TeamSlug   slug.Slug
	Category   string
	Suffix     string
	ExternalID *string
}

type User struct {
	ID          uuid.UUID
	Email       string
	Name        string
	ExternalID  string
	Admin       bool
	SectionCode *string
	JobTitle    *string
}
