// Code generated by sqlc. DO NOT EDIT.

package groupsql

import (
	"context"

	"github.com/statisticsnorway/dapla-api/internal/slug"
)

type Querier interface {
	AddMember(ctx context.Context, arg AddMemberParams) error
	Create(ctx context.Context, arg CreateParams) (*Group, error)
	Get(ctx context.Context, name string) (*Group, error)
	GetByNames(ctx context.Context, ids []string) ([]*Group, error)
	GetMember(ctx context.Context, arg GetMemberParams) (*User, error)
	GetMemberByEmail(ctx context.Context, arg GetMemberByEmailParams) (*User, error)
	GroupExists(ctx context.Context, arg GroupExistsParams) (bool, error)
	List(ctx context.Context, arg ListParams) ([]*ListRow, error)
	ListByTeamSlug(ctx context.Context, arg ListByTeamSlugParams) ([]*Group, error)
	ListForUser(ctx context.Context, arg ListForUserParams) ([]*ListForUserRow, error)
	ListMembers(ctx context.Context, arg ListMembersParams) ([]*ListMembersRow, error)
	RemoveMember(ctx context.Context, arg RemoveMemberParams) error
	TeamExists(ctx context.Context, argSlug slug.Slug) (bool, error)
}

var _ Querier = (*Queries)(nil)
