// Code generated by sqlc. DO NOT EDIT.
// source: teams.sql

package grpcteamsql

import (
	"context"

	"github.com/statisticsnorway/dapla-api/internal/slug"
)

const count = `-- name: Count :one
SELECT
	COUNT(*) AS total
FROM
	teams
`

func (q *Queries) Count(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, count)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countGroups = `-- name: CountGroups :one
SELECT
	COUNT(*) AS total
FROM
	groups
WHERE
	team_slug = $1::slug
`

func (q *Queries) CountGroups(ctx context.Context, teamSlug slug.Slug) (int64, error) {
	row := q.db.QueryRow(ctx, countGroups, teamSlug)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const delete = `-- name: Delete :exec
DELETE FROM teams
WHERE
	slug = $1
	AND delete_key_confirmed_at IS NOT NULL
`

func (q *Queries) Delete(ctx context.Context, argSlug slug.Slug) error {
	_, err := q.db.Exec(ctx, delete, argSlug)
	return err
}

const get = `-- name: Get :one
SELECT
	slug, purpose, last_successful_sync, delete_key_confirmed_at, section_code, is_managed, display_name
FROM
	teams
WHERE
	slug = $1
`

func (q *Queries) Get(ctx context.Context, argSlug slug.Slug) (*Team, error) {
	row := q.db.QueryRow(ctx, get, argSlug)
	var i Team
	err := row.Scan(
		&i.Slug,
		&i.Purpose,
		&i.LastSuccessfulSync,
		&i.DeleteKeyConfirmedAt,
		&i.SectionCode,
		&i.IsManaged,
		&i.DisplayName,
	)
	return &i, err
}

const list = `-- name: List :many
SELECT
	slug, purpose, last_successful_sync, delete_key_confirmed_at, section_code, is_managed, display_name
FROM
	teams
ORDER BY
	slug ASC
LIMIT
	$2
OFFSET
	$1
`

type ListParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]*Team, error) {
	rows, err := q.db.Query(ctx, list, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.Slug,
			&i.Purpose,
			&i.LastSuccessfulSync,
			&i.DeleteKeyConfirmedAt,
			&i.SectionCode,
			&i.IsManaged,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT
	name,
	team_slug,
	external_id
FROM
	groups
WHERE
	team_slug = $1::slug
ORDER BY
	name ASC
LIMIT
	$3
OFFSET
	$2
`

type ListGroupsParams struct {
	TeamSlug slug.Slug
	Offset   int32
	Limit    int32
}

type ListGroupsRow struct {
	Name       string
	TeamSlug   slug.Slug
	ExternalID *string
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]*ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups, arg.TeamSlug, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListGroupsRow{}
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(&i.Name, &i.TeamSlug, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLastSuccessfulSync = `-- name: SetLastSuccessfulSync :exec
UPDATE teams
SET
	last_successful_sync = NOW()
WHERE
	teams.slug = $1
`

func (q *Queries) SetLastSuccessfulSync(ctx context.Context, argSlug slug.Slug) error {
	_, err := q.db.Exec(ctx, setLastSuccessfulSync, argSlug)
	return err
}
