// Code generated by sqlc. DO NOT EDIT.
// source: teams.sql

package grpcteamsql

import (
	"context"

	"github.com/statisticsnorway/dapla-api/internal/slug"
)

const count = `-- name: Count :one
SELECT
	COUNT(*) AS total
FROM
	teams
`

func (q *Queries) Count(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, count)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countMembers = `-- name: CountMembers :one
SELECT
	COUNT(user_roles.*) AS total
FROM
	user_roles
	JOIN teams ON teams.slug = user_roles.target_team_slug
WHERE
	user_roles.target_team_slug = $1::slug
`

func (q *Queries) CountMembers(ctx context.Context, teamSlug slug.Slug) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, teamSlug)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const delete = `-- name: Delete :exec
DELETE FROM teams
WHERE
	slug = $1
	AND delete_key_confirmed_at IS NOT NULL
`

func (q *Queries) Delete(ctx context.Context, argSlug slug.Slug) error {
	_, err := q.db.Exec(ctx, delete, argSlug)
	return err
}

const get = `-- name: Get :one
SELECT
	slug, purpose, last_successful_sync, delete_key_confirmed_at
FROM
	teams
WHERE
	slug = $1
`

func (q *Queries) Get(ctx context.Context, argSlug slug.Slug) (*Team, error) {
	row := q.db.QueryRow(ctx, get, argSlug)
	var i Team
	err := row.Scan(
		&i.Slug,
		&i.Purpose,
		&i.LastSuccessfulSync,
		&i.DeleteKeyConfirmedAt,
	)
	return &i, err
}

const list = `-- name: List :many
SELECT
	slug, purpose, last_successful_sync, delete_key_confirmed_at
FROM
	teams
ORDER BY
	slug ASC
LIMIT
	$2
OFFSET
	$1
`

type ListParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]*Team, error) {
	rows, err := q.db.Query(ctx, list, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.Slug,
			&i.Purpose,
			&i.LastSuccessfulSync,
			&i.DeleteKeyConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT
	users.id, users.email, users.name, users.external_id, users.admin
FROM
	user_roles
	JOIN teams ON teams.slug = user_roles.target_team_slug
	JOIN users ON users.id = user_roles.user_id
WHERE
	user_roles.target_team_slug = $1::slug
ORDER BY
	users.name ASC
LIMIT
	$3
OFFSET
	$2
`

type ListMembersParams struct {
	TeamSlug slug.Slug
	Offset   int32
	Limit    int32
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.TeamSlug, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.ExternalID,
			&i.Admin,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLastSuccessfulSync = `-- name: SetLastSuccessfulSync :exec
UPDATE teams
SET
	last_successful_sync = NOW()
WHERE
	teams.slug = $1
`

func (q *Queries) SetLastSuccessfulSync(ctx context.Context, argSlug slug.Slug) error {
	_, err := q.db.Exec(ctx, setLastSuccessfulSync, argSlug)
	return err
}
