// Code generated by sqlc. DO NOT EDIT.

package teamsql

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/statisticsnorway/dapla-api/internal/slug"
)

type Team struct {
	Slug                 slug.Slug
	Purpose              string
	LastSuccessfulSync   pgtype.Timestamp
	DeleteKeyConfirmedAt pgtype.Timestamptz
	SectionCode          string
	IsManaged            bool
}

type TeamDeleteKey struct {
	Key         uuid.UUID
	TeamSlug    slug.Slug
	CreatedAt   pgtype.Timestamptz
	CreatedBy   uuid.UUID
	ConfirmedAt pgtype.Timestamptz
}
