// Code generated by sqlc. DO NOT EDIT.
// source: teams.sql

package teamsql

import (
	"context"

	"github.com/google/uuid"
	"github.com/statisticsnorway/dapla-api/internal/slug"
)

const confirmDeleteKey = `-- name: ConfirmDeleteKey :exec
UPDATE team_delete_keys
SET
	confirmed_at = NOW()
WHERE
	key = $1
`

func (q *Queries) ConfirmDeleteKey(ctx context.Context, key uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmDeleteKey, key)
	return err
}

const create = `-- name: Create :one
INSERT INTO
	teams (
		slug,
		display_name,
		purpose,
		section_code,
		is_managed
	)
VALUES
	(
		$1,
		$2,
		$3,
		$4,
		$5
	)
RETURNING
	slug, display_name, purpose, last_successful_sync, delete_key_confirmed_at, section_code, is_managed
`

type CreateParams struct {
	Slug        slug.Slug
	DisplayName string
	Purpose     string
	SectionCode string
	IsManaged   bool
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*Team, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Slug,
		arg.DisplayName,
		arg.Purpose,
		arg.SectionCode,
		arg.IsManaged,
	)
	var i Team
	err := row.Scan(
		&i.Slug,
		&i.DisplayName,
		&i.Purpose,
		&i.LastSuccessfulSync,
		&i.DeleteKeyConfirmedAt,
		&i.SectionCode,
		&i.IsManaged,
	)
	return &i, err
}

const createDeleteKey = `-- name: CreateDeleteKey :one
INSERT INTO
	team_delete_keys (team_slug, created_by)
VALUES
	($1, $2)
RETURNING
	key, team_slug, created_at, created_by, confirmed_at
`

type CreateDeleteKeyParams struct {
	TeamSlug  slug.Slug
	CreatedBy uuid.UUID
}

func (q *Queries) CreateDeleteKey(ctx context.Context, arg CreateDeleteKeyParams) (*TeamDeleteKey, error) {
	row := q.db.QueryRow(ctx, createDeleteKey, arg.TeamSlug, arg.CreatedBy)
	var i TeamDeleteKey
	err := row.Scan(
		&i.Key,
		&i.TeamSlug,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ConfirmedAt,
	)
	return &i, err
}

const exists = `-- name: Exists :one
SELECT
	EXISTS (
		SELECT
			slug
		FROM
			teams
		WHERE
			slug = $1
	)
`

func (q *Queries) Exists(ctx context.Context, argSlug slug.Slug) (bool, error) {
	row := q.db.QueryRow(ctx, exists, argSlug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const get = `-- name: Get :one
SELECT
	slug, display_name, purpose, last_successful_sync, delete_key_confirmed_at, section_code, is_managed
FROM
	teams
WHERE
	slug = $1
`

func (q *Queries) Get(ctx context.Context, argSlug slug.Slug) (*Team, error) {
	row := q.db.QueryRow(ctx, get, argSlug)
	var i Team
	err := row.Scan(
		&i.Slug,
		&i.DisplayName,
		&i.Purpose,
		&i.LastSuccessfulSync,
		&i.DeleteKeyConfirmedAt,
		&i.SectionCode,
		&i.IsManaged,
	)
	return &i, err
}

const getDeleteKey = `-- name: GetDeleteKey :one
SELECT
	key, team_slug, created_at, created_by, confirmed_at
FROM
	team_delete_keys
WHERE
	key = $1
	AND team_slug = $2::slug
`

type GetDeleteKeyParams struct {
	Key  uuid.UUID
	Slug slug.Slug
}

func (q *Queries) GetDeleteKey(ctx context.Context, arg GetDeleteKeyParams) (*TeamDeleteKey, error) {
	row := q.db.QueryRow(ctx, getDeleteKey, arg.Key, arg.Slug)
	var i TeamDeleteKey
	err := row.Scan(
		&i.Key,
		&i.TeamSlug,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ConfirmedAt,
	)
	return &i, err
}

const list = `-- name: List :many
SELECT
	teams.slug, teams.display_name, teams.purpose, teams.last_successful_sync, teams.delete_key_confirmed_at, teams.section_code, teams.is_managed,
	COUNT(*) OVER () AS total_count
FROM
	teams
ORDER BY
	CASE
		WHEN $1::TEXT = 'slug:asc' THEN slug
	END ASC,
	CASE
		WHEN $1::TEXT = 'slug:desc' THEN slug
	END DESC,
	slug ASC
LIMIT
	$3
OFFSET
	$2
`

type ListParams struct {
	OrderBy string
	Offset  int32
	Limit   int32
}

type ListRow struct {
	Team       Team
	TotalCount int64
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]*ListRow, error) {
	rows, err := q.db.Query(ctx, list, arg.OrderBy, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListRow{}
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(
			&i.Team.Slug,
			&i.Team.DisplayName,
			&i.Team.Purpose,
			&i.Team.LastSuccessfulSync,
			&i.Team.DeleteKeyConfirmedAt,
			&i.Team.SectionCode,
			&i.Team.IsManaged,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllForSearch = `-- name: ListAllForSearch :many
SELECT
	slug,
	purpose,
	section_code
FROM
	teams
ORDER BY
	slug ASC
`

type ListAllForSearchRow struct {
	Slug        slug.Slug
	Purpose     string
	SectionCode string
}

func (q *Queries) ListAllForSearch(ctx context.Context) ([]*ListAllForSearchRow, error) {
	rows, err := q.db.Query(ctx, listAllForSearch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListAllForSearchRow{}
	for rows.Next() {
		var i ListAllForSearchRow
		if err := rows.Scan(&i.Slug, &i.Purpose, &i.SectionCode); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSlugs = `-- name: ListAllSlugs :one
SELECT
	ARRAY_AGG(slug)::slug[] AS slugs
FROM
	teams
`

func (q *Queries) ListAllSlugs(ctx context.Context) ([]slug.Slug, error) {
	row := q.db.QueryRow(ctx, listAllSlugs)
	var slugs []slug.Slug
	err := row.Scan(&slugs)
	return slugs, err
}

const listBySlugs = `-- name: ListBySlugs :many
SELECT
	slug, display_name, purpose, last_successful_sync, delete_key_confirmed_at, section_code, is_managed
FROM
	teams
WHERE
	slug = ANY ($1::slug[])
ORDER BY
	slug ASC
`

func (q *Queries) ListBySlugs(ctx context.Context, slugs []slug.Slug) ([]*Team, error) {
	rows, err := q.db.Query(ctx, listBySlugs, slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.Purpose,
			&i.LastSuccessfulSync,
			&i.DeleteKeyConfirmedAt,
			&i.SectionCode,
			&i.IsManaged,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeleteKeyConfirmedAt = `-- name: SetDeleteKeyConfirmedAt :exec
UPDATE teams
SET
	delete_key_confirmed_at = NOW()
WHERE
	slug = $1
`

func (q *Queries) SetDeleteKeyConfirmedAt(ctx context.Context, argSlug slug.Slug) error {
	_, err := q.db.Exec(ctx, setDeleteKeyConfirmedAt, argSlug)
	return err
}

const slugAvailable = `-- name: SlugAvailable :one
SELECT
	NOT EXISTS (
		SELECT
			slug
		FROM
			team_slugs
		WHERE
			slug = $1
	)
`

func (q *Queries) SlugAvailable(ctx context.Context, argSlug slug.Slug) (bool, error) {
	row := q.db.QueryRow(ctx, slugAvailable, argSlug)
	var not_exists bool
	err := row.Scan(&not_exists)
	return not_exists, err
}

const update = `-- name: Update :one
UPDATE teams
SET
	purpose = COALESCE($1, purpose),
	display_name = COALESCE($2, display_name)
WHERE
	teams.slug = $3
RETURNING
	slug, display_name, purpose, last_successful_sync, delete_key_confirmed_at, section_code, is_managed
`

type UpdateParams struct {
	Purpose     *string
	DisplayName *string
	Slug        slug.Slug
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*Team, error) {
	row := q.db.QueryRow(ctx, update, arg.Purpose, arg.DisplayName, arg.Slug)
	var i Team
	err := row.Scan(
		&i.Slug,
		&i.DisplayName,
		&i.Purpose,
		&i.LastSuccessfulSync,
		&i.DeleteKeyConfirmedAt,
		&i.SectionCode,
		&i.IsManaged,
	)
	return &i, err
}
