// Code generated by sqlc. DO NOT EDIT.
// source: team_members.sql

package teamsql

import (
	"context"

	"github.com/google/uuid"
	"github.com/statisticsnorway/dapla-api/internal/slug"
)

const listForUser = `-- name: ListForUser :many
SELECT
	teams.slug,
	users.id,
	ARRAY_AGG(groups.name)::TEXT[] AS groups,
	COUNT(*) OVER () AS total_count
FROM
	teams
	JOIN groups ON groups.team_slug = teams.slug
	JOIN group_members ON group_members.group_name = groups.name
	JOIN users ON users.id = group_members.user_id
WHERE
	group_members.user_id = $1
GROUP BY
	users.id,
	teams.slug
ORDER BY
	CASE
		WHEN $2::TEXT = 'slug:asc' THEN teams.slug
	END ASC,
	CASE
		WHEN $2::TEXT = 'slug:desc' THEN teams.slug
	END DESC,
	CASE
		WHEN $2::TEXT = 'section_code:asc' THEN teams.section_code
	END ASC,
	CASE
		WHEN $2::TEXT = 'section_code:desc' THEN teams.section_code
	END DESC,
	teams.slug ASC
LIMIT
	$4
OFFSET
	$3
`

type ListForUserParams struct {
	UserID  uuid.UUID
	OrderBy string
	Offset  int32
	Limit   int32
}

type ListForUserRow struct {
	Slug       slug.Slug
	ID         uuid.UUID
	Groups     []string
	TotalCount int64
}

func (q *Queries) ListForUser(ctx context.Context, arg ListForUserParams) ([]*ListForUserRow, error) {
	rows, err := q.db.Query(ctx, listForUser,
		arg.UserID,
		arg.OrderBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListForUserRow{}
	for rows.Next() {
		var i ListForUserRow
		if err := rows.Scan(
			&i.Slug,
			&i.ID,
			&i.Groups,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT
	users.id,
	groups.team_slug,
	ARRAY_AGG(groups.name)::TEXT[] AS groups,
	COUNT(*) OVER () AS total_count
FROM
	group_members
	JOIN groups ON groups.name = group_members.group_name
	JOIN users ON users.id = group_members.user_id
WHERE
	groups.team_slug = $1::slug
GROUP BY
	groups.team_slug,
	users.id
ORDER BY
	CASE
		WHEN $2::TEXT = 'name:asc' THEN LOWER(users.name)
	END ASC,
	CASE
		WHEN $2::TEXT = 'name:desc' THEN LOWER(users.name)
	END DESC,
	CASE
		WHEN $2::TEXT = 'email:asc' THEN users.email
	END ASC,
	CASE
		WHEN $2::TEXT = 'email:desc' THEN users.email
	END DESC,
	CASE
		WHEN $2::TEXT = 'section_code:asc' THEN users.section_code
	END ASC,
	CASE
		WHEN $2::TEXT = 'section_code:desc' THEN users.section_code
	END DESC,
	users.name,
	users.email ASC
LIMIT
	$4
OFFSET
	$3
`

type ListMembersParams struct {
	TeamSlug slug.Slug
	OrderBy  string
	Offset   int32
	Limit    int32
}

type ListMembersRow struct {
	ID         uuid.UUID
	TeamSlug   slug.Slug
	Groups     []string
	TotalCount int64
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]*ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers,
		arg.TeamSlug,
		arg.OrderBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamSlug,
			&i.Groups,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userIsMember = `-- name: UserIsMember :one
SELECT
	(
		EXISTS (
			SELECT
				1
			FROM
				group_members
				JOIN groups ON groups.name = group_members.group_name
			WHERE
				user_id = $1
				AND groups.team_slug = $2::slug
		)
		OR EXISTS (
			SELECT
				1
			FROM
				sections
				JOIN teams ON teams.section_code = sections.code
			WHERE
				teams.slug = $2::slug
				AND sections.manager_id = $1
		)
	)::BOOLEAN
`

type UserIsMemberParams struct {
	UserID   uuid.UUID
	TeamSlug slug.Slug
}

func (q *Queries) UserIsMember(ctx context.Context, arg UserIsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, userIsMember, arg.UserID, arg.TeamSlug)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const userIsOwner = `-- name: UserIsOwner :one
SELECT
	(
		EXISTS (
			SELECT
				1
			FROM
				group_members
				JOIN groups ON groups.name = group_members.group_name
			WHERE
				group_members.user_id = $1
				AND groups.team_slug = $2::slug
				AND groups.category = 'managers'
				AND groups.suffix = ''
		)
		OR EXISTS (
			SELECT
				1
			FROM
				sections
				JOIN teams ON teams.section_code = sections.code
			WHERE
				teams.slug = $2::slug
				AND sections.manager_id = $1
		)
	)::BOOLEAN
`

type UserIsOwnerParams struct {
	UserID   uuid.UUID
	TeamSlug slug.Slug
}

func (q *Queries) UserIsOwner(ctx context.Context, arg UserIsOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, userIsOwner, arg.UserID, arg.TeamSlug)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
