// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: artifactregistry.proto

//go:build !protoopaque

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactRegistryRepo struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	TeamSlug      string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3" json:"team_slug,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRegistryRepo) Reset() {
	*x = ArtifactRegistryRepo{}
	mi := &file_artifactregistry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRegistryRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRegistryRepo) ProtoMessage() {}

func (x *ArtifactRegistryRepo) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ArtifactRegistryRepo) GetTeamSlug() string {
	if x != nil {
		return x.TeamSlug
	}
	return ""
}

func (x *ArtifactRegistryRepo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ArtifactRegistryRepo) SetTeamSlug(v string) {
	x.TeamSlug = v
}

func (x *ArtifactRegistryRepo) SetFormat(v string) {
	x.Format = v
}

type ArtifactRegistryRepo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug string
	Format   string
}

func (b0 ArtifactRegistryRepo_builder) Build() *ArtifactRegistryRepo {
	m0 := &ArtifactRegistryRepo{}
	b, x := &b0, m0
	_, _ = b, x
	x.TeamSlug = b.TeamSlug
	x.Format = b.Format
	return m0
}

type GetArtifactRegistryRepoResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Repo          *ArtifactRegistryRepo  `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactRegistryRepoResponse) Reset() {
	*x = GetArtifactRegistryRepoResponse{}
	mi := &file_artifactregistry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRegistryRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRegistryRepoResponse) ProtoMessage() {}

func (x *GetArtifactRegistryRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetArtifactRegistryRepoResponse) GetRepo() *ArtifactRegistryRepo {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *GetArtifactRegistryRepoResponse) SetRepo(v *ArtifactRegistryRepo) {
	x.Repo = v
}

func (x *GetArtifactRegistryRepoResponse) HasRepo() bool {
	if x == nil {
		return false
	}
	return x.Repo != nil
}

func (x *GetArtifactRegistryRepoResponse) ClearRepo() {
	x.Repo = nil
}

type GetArtifactRegistryRepoResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Repo *ArtifactRegistryRepo
}

func (b0 GetArtifactRegistryRepoResponse_builder) Build() *GetArtifactRegistryRepoResponse {
	m0 := &GetArtifactRegistryRepoResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Repo = b.Repo
	return m0
}

type GetArtifactRegistryRepoRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	TeamSlug      string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3" json:"team_slug,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactRegistryRepoRequest) Reset() {
	*x = GetArtifactRegistryRepoRequest{}
	mi := &file_artifactregistry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRegistryRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRegistryRepoRequest) ProtoMessage() {}

func (x *GetArtifactRegistryRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetArtifactRegistryRepoRequest) GetTeamSlug() string {
	if x != nil {
		return x.TeamSlug
	}
	return ""
}

func (x *GetArtifactRegistryRepoRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetArtifactRegistryRepoRequest) SetTeamSlug(v string) {
	x.TeamSlug = v
}

func (x *GetArtifactRegistryRepoRequest) SetFormat(v string) {
	x.Format = v
}

type GetArtifactRegistryRepoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug string
	Format   string
}

func (b0 GetArtifactRegistryRepoRequest_builder) Build() *GetArtifactRegistryRepoRequest {
	m0 := &GetArtifactRegistryRepoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.TeamSlug = b.TeamSlug
	x.Format = b.Format
	return m0
}

type ListArtifactRegistryReposForTeamRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	TeamSlug      string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3" json:"team_slug,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactRegistryReposForTeamRequest) Reset() {
	*x = ListArtifactRegistryReposForTeamRequest{}
	mi := &file_artifactregistry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactRegistryReposForTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactRegistryReposForTeamRequest) ProtoMessage() {}

func (x *ListArtifactRegistryReposForTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListArtifactRegistryReposForTeamRequest) GetTeamSlug() string {
	if x != nil {
		return x.TeamSlug
	}
	return ""
}

func (x *ListArtifactRegistryReposForTeamRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArtifactRegistryReposForTeamRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListArtifactRegistryReposForTeamRequest) SetTeamSlug(v string) {
	x.TeamSlug = v
}

func (x *ListArtifactRegistryReposForTeamRequest) SetLimit(v int64) {
	x.Limit = v
}

func (x *ListArtifactRegistryReposForTeamRequest) SetOffset(v int64) {
	x.Offset = v
}

type ListArtifactRegistryReposForTeamRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug string
	Limit    int64
	Offset   int64
}

func (b0 ListArtifactRegistryReposForTeamRequest_builder) Build() *ListArtifactRegistryReposForTeamRequest {
	m0 := &ListArtifactRegistryReposForTeamRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.TeamSlug = b.TeamSlug
	x.Limit = b.Limit
	x.Offset = b.Offset
	return m0
}

type ListArtifactRegistryReposForTeamResponse struct {
	state         protoimpl.MessageState  `protogen:"hybrid.v1"`
	Team          string                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	Nodes         []*ArtifactRegistryRepo `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	PageInfo      *PageInfo               `protobuf:"bytes,3,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactRegistryReposForTeamResponse) Reset() {
	*x = ListArtifactRegistryReposForTeamResponse{}
	mi := &file_artifactregistry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactRegistryReposForTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactRegistryReposForTeamResponse) ProtoMessage() {}

func (x *ListArtifactRegistryReposForTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifactregistry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListArtifactRegistryReposForTeamResponse) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *ListArtifactRegistryReposForTeamResponse) GetNodes() []*ArtifactRegistryRepo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListArtifactRegistryReposForTeamResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *ListArtifactRegistryReposForTeamResponse) SetTeam(v string) {
	x.Team = v
}

func (x *ListArtifactRegistryReposForTeamResponse) SetNodes(v []*ArtifactRegistryRepo) {
	x.Nodes = v
}

func (x *ListArtifactRegistryReposForTeamResponse) SetPageInfo(v *PageInfo) {
	x.PageInfo = v
}

func (x *ListArtifactRegistryReposForTeamResponse) HasPageInfo() bool {
	if x == nil {
		return false
	}
	return x.PageInfo != nil
}

func (x *ListArtifactRegistryReposForTeamResponse) ClearPageInfo() {
	x.PageInfo = nil
}

type ListArtifactRegistryReposForTeamResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Team     string
	Nodes    []*ArtifactRegistryRepo
	PageInfo *PageInfo
}

func (b0 ListArtifactRegistryReposForTeamResponse_builder) Build() *ListArtifactRegistryReposForTeamResponse {
	m0 := &ListArtifactRegistryReposForTeamResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Team = b.Team
	x.Nodes = b.Nodes
	x.PageInfo = b.PageInfo
	return m0
}

var File_artifactregistry_proto protoreflect.FileDescriptor

var file_artifactregistry_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x10, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b,
	0x0a, 0x14, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x73,
	0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x53,
	0x6c, 0x75, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x5f, 0x0a, 0x1f, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64,
	0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x22, 0x55, 0x0a, 0x1e,
	0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x22, 0x74, 0x0a, 0x27, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x46, 0x6f, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0xb9, 0x01, 0x0a, 0x28, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x12, 0x3e, 0x0a, 0x05, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64, 0x61, 0x70, 0x6c,
	0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52,
	0x65, 0x70, 0x6f, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0xbb, 0x02, 0x0a, 0x10, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x84, 0x01, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x32, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52,
	0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x64, 0x61, 0x70,
	0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x9f, 0x01, 0x0a, 0x20, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x46,
	0x6f, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x3b, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x52, 0x65, 0x70, 0x6f, 0x73, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x3c, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x65, 0x70,
	0x6f, 0x73, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_artifactregistry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_artifactregistry_proto_goTypes = []any{
	(*ArtifactRegistryRepo)(nil),                     // 0: dapla.api.protobuf.ArtifactRegistryRepo
	(*GetArtifactRegistryRepoResponse)(nil),          // 1: dapla.api.protobuf.GetArtifactRegistryRepoResponse
	(*GetArtifactRegistryRepoRequest)(nil),           // 2: dapla.api.protobuf.GetArtifactRegistryRepoRequest
	(*ListArtifactRegistryReposForTeamRequest)(nil),  // 3: dapla.api.protobuf.ListArtifactRegistryReposForTeamRequest
	(*ListArtifactRegistryReposForTeamResponse)(nil), // 4: dapla.api.protobuf.ListArtifactRegistryReposForTeamResponse
	(*PageInfo)(nil),                                 // 5: dapla.api.protobuf.PageInfo
}
var file_artifactregistry_proto_depIdxs = []int32{
	0, // 0: dapla.api.protobuf.GetArtifactRegistryRepoResponse.repo:type_name -> dapla.api.protobuf.ArtifactRegistryRepo
	0, // 1: dapla.api.protobuf.ListArtifactRegistryReposForTeamResponse.nodes:type_name -> dapla.api.protobuf.ArtifactRegistryRepo
	5, // 2: dapla.api.protobuf.ListArtifactRegistryReposForTeamResponse.page_info:type_name -> dapla.api.protobuf.PageInfo
	2, // 3: dapla.api.protobuf.ArtifactRegistry.GetArtifactRegistryRepo:input_type -> dapla.api.protobuf.GetArtifactRegistryRepoRequest
	3, // 4: dapla.api.protobuf.ArtifactRegistry.ListArtifactRegistryReposForTeam:input_type -> dapla.api.protobuf.ListArtifactRegistryReposForTeamRequest
	1, // 5: dapla.api.protobuf.ArtifactRegistry.GetArtifactRegistryRepo:output_type -> dapla.api.protobuf.GetArtifactRegistryRepoResponse
	4, // 6: dapla.api.protobuf.ArtifactRegistry.ListArtifactRegistryReposForTeam:output_type -> dapla.api.protobuf.ListArtifactRegistryReposForTeamResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_artifactregistry_proto_init() }
func file_artifactregistry_proto_init() {
	if File_artifactregistry_proto != nil {
		return
	}
	file_pagination_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifactregistry_proto_rawDesc), len(file_artifactregistry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artifactregistry_proto_goTypes,
		DependencyIndexes: file_artifactregistry_proto_depIdxs,
		MessageInfos:      file_artifactregistry_proto_msgTypes,
	}.Build()
	File_artifactregistry_proto = out.File
	file_artifactregistry_proto_goTypes = nil
	file_artifactregistry_proto_depIdxs = nil
}
