// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: groups.proto

//go:build protoopaque

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Group struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamSlug    string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3"`
	xxx_hidden_Name        string                 `protobuf:"bytes,2,opt,name=name,proto3"`
	xxx_hidden_ExternalId  *string                `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Group) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Group) GetExternalId() string {
	if x != nil {
		if x.xxx_hidden_ExternalId != nil {
			return *x.xxx_hidden_ExternalId
		}
		return ""
	}
	return ""
}

func (x *Group) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

func (x *Group) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Group) SetExternalId(v string) {
	x.xxx_hidden_ExternalId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Group) HasExternalId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Group) ClearExternalId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ExternalId = nil
}

type Group_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug   string
	Name       string
	ExternalId *string
}

func (b0 Group_builder) Build() *Group {
	m0 := &Group{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamSlug = b.TeamSlug
	x.xxx_hidden_Name = b.Name
	if b.ExternalId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ExternalId = b.ExternalId
	}
	return m0
}

type ListGroupMembersRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit  int64                  `protobuf:"varint,1,opt,name=limit,proto3"`
	xxx_hidden_Offset int64                  `protobuf:"varint,2,opt,name=offset,proto3"`
	xxx_hidden_Name   string                 `protobuf:"bytes,3,opt,name=name,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListGroupMembersRequest) Reset() {
	*x = ListGroupMembersRequest{}
	mi := &file_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersRequest) ProtoMessage() {}

func (x *ListGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListGroupMembersRequest) GetLimit() int64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListGroupMembersRequest) GetOffset() int64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListGroupMembersRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ListGroupMembersRequest) SetLimit(v int64) {
	x.xxx_hidden_Limit = v
}

func (x *ListGroupMembersRequest) SetOffset(v int64) {
	x.xxx_hidden_Offset = v
}

func (x *ListGroupMembersRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

type ListGroupMembersRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit  int64
	Offset int64
	Name   string
}

func (b0 ListGroupMembersRequest_builder) Build() *ListGroupMembersRequest {
	m0 := &ListGroupMembersRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_Name = b.Name
	return m0
}

type GetGroupRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetGroupRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GetGroupRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

type GetGroupRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
}

func (b0 GetGroupRequest_builder) Build() *GetGroupRequest {
	m0 := &GetGroupRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

type SetExternalIdRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name       string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_ExternalId string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SetExternalIdRequest) Reset() {
	*x = SetExternalIdRequest{}
	mi := &file_groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetExternalIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExternalIdRequest) ProtoMessage() {}

func (x *SetExternalIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetExternalIdRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *SetExternalIdRequest) GetExternalId() string {
	if x != nil {
		return x.xxx_hidden_ExternalId
	}
	return ""
}

func (x *SetExternalIdRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *SetExternalIdRequest) SetExternalId(v string) {
	x.xxx_hidden_ExternalId = v
}

type SetExternalIdRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name       string
	ExternalId string
}

func (b0 SetExternalIdRequest_builder) Build() *SetExternalIdRequest {
	m0 := &SetExternalIdRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_ExternalId = b.ExternalId
	return m0
}

type ListGroupMembersResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes    *[]*GroupMember        `protobuf:"bytes,1,rep,name=nodes,proto3"`
	xxx_hidden_PageInfo *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListGroupMembersResponse) Reset() {
	*x = ListGroupMembersResponse{}
	mi := &file_groups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersResponse) ProtoMessage() {}

func (x *ListGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListGroupMembersResponse) GetNodes() []*GroupMember {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *ListGroupMembersResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.xxx_hidden_PageInfo
	}
	return nil
}

func (x *ListGroupMembersResponse) SetNodes(v []*GroupMember) {
	x.xxx_hidden_Nodes = &v
}

func (x *ListGroupMembersResponse) SetPageInfo(v *PageInfo) {
	x.xxx_hidden_PageInfo = v
}

func (x *ListGroupMembersResponse) HasPageInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PageInfo != nil
}

func (x *ListGroupMembersResponse) ClearPageInfo() {
	x.xxx_hidden_PageInfo = nil
}

type ListGroupMembersResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes    []*GroupMember
	PageInfo *PageInfo
}

func (b0 ListGroupMembersResponse_builder) Build() *ListGroupMembersResponse {
	m0 := &ListGroupMembersResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = &b.Nodes
	x.xxx_hidden_PageInfo = b.PageInfo
	return m0
}

type GetGroupResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Group *Group                 `protobuf:"bytes,1,opt,name=group,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_groups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.xxx_hidden_Group
	}
	return nil
}

func (x *GetGroupResponse) SetGroup(v *Group) {
	x.xxx_hidden_Group = v
}

func (x *GetGroupResponse) HasGroup() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Group != nil
}

func (x *GetGroupResponse) ClearGroup() {
	x.xxx_hidden_Group = nil
}

type GetGroupResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Group *Group
}

func (b0 GetGroupResponse_builder) Build() *GetGroupResponse {
	m0 := &GetGroupResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Group = b.Group
	return m0
}

type SetExternalIdResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetExternalIdResponse) Reset() {
	*x = SetExternalIdResponse{}
	mi := &file_groups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetExternalIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExternalIdResponse) ProtoMessage() {}

func (x *SetExternalIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SetExternalIdResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SetExternalIdResponse_builder) Build() *SetExternalIdResponse {
	m0 := &SetExternalIdResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GroupMember struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User *User                  `protobuf:"bytes,1,opt,name=user,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_groups_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupMember) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *GroupMember) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *GroupMember) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *GroupMember) ClearUser() {
	x.xxx_hidden_User = nil
}

type GroupMember_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User *User
}

func (b0 GroupMember_builder) Build() *GroupMember {
	m0 := &GroupMember{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	return m0
}

type AddMemberRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserExternalId string                 `protobuf:"bytes,1,opt,name=user_external_id,json=userExternalId,proto3"`
	xxx_hidden_Groupname      string                 `protobuf:"bytes,2,opt,name=groupname,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_groups_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddMemberRequest) GetUserExternalId() string {
	if x != nil {
		return x.xxx_hidden_UserExternalId
	}
	return ""
}

func (x *AddMemberRequest) GetGroupname() string {
	if x != nil {
		return x.xxx_hidden_Groupname
	}
	return ""
}

func (x *AddMemberRequest) SetUserExternalId(v string) {
	x.xxx_hidden_UserExternalId = v
}

func (x *AddMemberRequest) SetGroupname(v string) {
	x.xxx_hidden_Groupname = v
}

type AddMemberRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserExternalId string
	Groupname      string
}

func (b0 AddMemberRequest_builder) Build() *AddMemberRequest {
	m0 := &AddMemberRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserExternalId = b.UserExternalId
	x.xxx_hidden_Groupname = b.Groupname
	return m0
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_groups_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AddMemberResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AddMemberResponse_builder) Build() *AddMemberResponse {
	m0 := &AddMemberResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RemoveMemberRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserExternalId string                 `protobuf:"bytes,1,opt,name=user_external_id,json=userExternalId,proto3"`
	xxx_hidden_Groupname      string                 `protobuf:"bytes,2,opt,name=groupname,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_groups_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RemoveMemberRequest) GetUserExternalId() string {
	if x != nil {
		return x.xxx_hidden_UserExternalId
	}
	return ""
}

func (x *RemoveMemberRequest) GetGroupname() string {
	if x != nil {
		return x.xxx_hidden_Groupname
	}
	return ""
}

func (x *RemoveMemberRequest) SetUserExternalId(v string) {
	x.xxx_hidden_UserExternalId = v
}

func (x *RemoveMemberRequest) SetGroupname(v string) {
	x.xxx_hidden_Groupname = v
}

type RemoveMemberRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserExternalId string
	Groupname      string
}

func (b0 RemoveMemberRequest_builder) Build() *RemoveMemberRequest {
	m0 := &RemoveMemberRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserExternalId = b.UserExternalId
	x.xxx_hidden_Groupname = b.Groupname
	return m0
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_groups_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RemoveMemberResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RemoveMemberResponse_builder) Build() *RemoveMemberResponse {
	m0 := &RemoveMemberResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_groups_proto protoreflect.FileDescriptor

const file_groups_proto_rawDesc = "" +
	"\n" +
	"\fgroups.proto\x12\x12dapla.api.protobuf\x1a\x10pagination.proto\x1a\vusers.proto\"n\n" +
	"\x05Group\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\vexternal_id\x18\x03 \x01(\tH\x00R\n" +
	"externalId\x88\x01\x01B\x0e\n" +
	"\f_external_id\"[\n" +
	"\x17ListGroupMembersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"%\n" +
	"\x0fGetGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x14SetExternalIdRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\"\x8c\x01\n" +
	"\x18ListGroupMembersResponse\x125\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1f.dapla.api.protobuf.GroupMemberR\x05nodes\x129\n" +
	"\tpage_info\x18\x02 \x01(\v2\x1c.dapla.api.protobuf.PageInfoR\bpageInfo\"C\n" +
	"\x10GetGroupResponse\x12/\n" +
	"\x05group\x18\x01 \x01(\v2\x19.dapla.api.protobuf.GroupR\x05group\"\x17\n" +
	"\x15SetExternalIdResponse\";\n" +
	"\vGroupMember\x12,\n" +
	"\x04user\x18\x01 \x01(\v2\x18.dapla.api.protobuf.UserR\x04user\"Z\n" +
	"\x10AddMemberRequest\x12(\n" +
	"\x10user_external_id\x18\x01 \x01(\tR\x0euserExternalId\x12\x1c\n" +
	"\tgroupname\x18\x02 \x01(\tR\tgroupname\"\x13\n" +
	"\x11AddMemberResponse\"]\n" +
	"\x13RemoveMemberRequest\x12(\n" +
	"\x10user_external_id\x18\x01 \x01(\tR\x0euserExternalId\x12\x1c\n" +
	"\tgroupname\x18\x02 \x01(\tR\tgroupname\"\x16\n" +
	"\x14RemoveMemberResponse2\xed\x03\n" +
	"\x06Groups\x12f\n" +
	"\aMembers\x12+.dapla.api.protobuf.ListGroupMembersRequest\x1a,.dapla.api.protobuf.ListGroupMembersResponse\"\x00\x12R\n" +
	"\x03Get\x12#.dapla.api.protobuf.GetGroupRequest\x1a$.dapla.api.protobuf.GetGroupResponse\"\x00\x12f\n" +
	"\rSetExternalId\x12(.dapla.api.protobuf.SetExternalIdRequest\x1a).dapla.api.protobuf.SetExternalIdResponse\"\x00\x12Z\n" +
	"\tAddMember\x12$.dapla.api.protobuf.AddMemberRequest\x1a%.dapla.api.protobuf.AddMemberResponse\"\x00\x12c\n" +
	"\fRemoveMember\x12'.dapla.api.protobuf.RemoveMemberRequest\x1a(.dapla.api.protobuf.RemoveMemberResponse\"\x00B\x1aZ\x18./pkg/apiclient/protoapib\x06proto3"

var file_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_groups_proto_goTypes = []any{
	(*Group)(nil),                    // 0: dapla.api.protobuf.Group
	(*ListGroupMembersRequest)(nil),  // 1: dapla.api.protobuf.ListGroupMembersRequest
	(*GetGroupRequest)(nil),          // 2: dapla.api.protobuf.GetGroupRequest
	(*SetExternalIdRequest)(nil),     // 3: dapla.api.protobuf.SetExternalIdRequest
	(*ListGroupMembersResponse)(nil), // 4: dapla.api.protobuf.ListGroupMembersResponse
	(*GetGroupResponse)(nil),         // 5: dapla.api.protobuf.GetGroupResponse
	(*SetExternalIdResponse)(nil),    // 6: dapla.api.protobuf.SetExternalIdResponse
	(*GroupMember)(nil),              // 7: dapla.api.protobuf.GroupMember
	(*AddMemberRequest)(nil),         // 8: dapla.api.protobuf.AddMemberRequest
	(*AddMemberResponse)(nil),        // 9: dapla.api.protobuf.AddMemberResponse
	(*RemoveMemberRequest)(nil),      // 10: dapla.api.protobuf.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),     // 11: dapla.api.protobuf.RemoveMemberResponse
	(*PageInfo)(nil),                 // 12: dapla.api.protobuf.PageInfo
	(*User)(nil),                     // 13: dapla.api.protobuf.User
}
var file_groups_proto_depIdxs = []int32{
	7,  // 0: dapla.api.protobuf.ListGroupMembersResponse.nodes:type_name -> dapla.api.protobuf.GroupMember
	12, // 1: dapla.api.protobuf.ListGroupMembersResponse.page_info:type_name -> dapla.api.protobuf.PageInfo
	0,  // 2: dapla.api.protobuf.GetGroupResponse.group:type_name -> dapla.api.protobuf.Group
	13, // 3: dapla.api.protobuf.GroupMember.user:type_name -> dapla.api.protobuf.User
	1,  // 4: dapla.api.protobuf.Groups.Members:input_type -> dapla.api.protobuf.ListGroupMembersRequest
	2,  // 5: dapla.api.protobuf.Groups.Get:input_type -> dapla.api.protobuf.GetGroupRequest
	3,  // 6: dapla.api.protobuf.Groups.SetExternalId:input_type -> dapla.api.protobuf.SetExternalIdRequest
	8,  // 7: dapla.api.protobuf.Groups.AddMember:input_type -> dapla.api.protobuf.AddMemberRequest
	10, // 8: dapla.api.protobuf.Groups.RemoveMember:input_type -> dapla.api.protobuf.RemoveMemberRequest
	4,  // 9: dapla.api.protobuf.Groups.Members:output_type -> dapla.api.protobuf.ListGroupMembersResponse
	5,  // 10: dapla.api.protobuf.Groups.Get:output_type -> dapla.api.protobuf.GetGroupResponse
	6,  // 11: dapla.api.protobuf.Groups.SetExternalId:output_type -> dapla.api.protobuf.SetExternalIdResponse
	9,  // 12: dapla.api.protobuf.Groups.AddMember:output_type -> dapla.api.protobuf.AddMemberResponse
	11, // 13: dapla.api.protobuf.Groups.RemoveMember:output_type -> dapla.api.protobuf.RemoveMemberResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_groups_proto_init() }
func file_groups_proto_init() {
	if File_groups_proto != nil {
		return
	}
	file_pagination_proto_init()
	file_users_proto_init()
	file_groups_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_groups_proto_rawDesc), len(file_groups_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_groups_proto_goTypes,
		DependencyIndexes: file_groups_proto_depIdxs,
		MessageInfos:      file_groups_proto_msgTypes,
	}.Build()
	File_groups_proto = out.File
	file_groups_proto_goTypes = nil
	file_groups_proto_depIdxs = nil
}
