// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package protoapi

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockArtifactRegistryServer creates a new instance of MockArtifactRegistryServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArtifactRegistryServer(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockArtifactRegistryServer {
	mock := &MockArtifactRegistryServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArtifactRegistryServer is an autogenerated mock type for the ArtifactRegistryServer type
type MockArtifactRegistryServer struct {
	mock.Mock
}

type MockArtifactRegistryServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArtifactRegistryServer) EXPECT() *MockArtifactRegistryServer_Expecter {
	return &MockArtifactRegistryServer_Expecter{mock: &_m.Mock}
}

// GetArtifactRegistryGithubAllowlist provides a mock function for the type MockArtifactRegistryServer
func (_mock *MockArtifactRegistryServer) GetArtifactRegistryGithubAllowlist(context1 context.Context, getArtifactRegistryGithubAllowlistRequest *GetArtifactRegistryGithubAllowlistRequest) (*GetArtifactRegistryGithubAllowlistResponse, error) {
	ret := _mock.Called(context1, getArtifactRegistryGithubAllowlistRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactRegistryGithubAllowlist")
	}

	var r0 *GetArtifactRegistryGithubAllowlistResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetArtifactRegistryGithubAllowlistRequest) (*GetArtifactRegistryGithubAllowlistResponse, error)); ok {
		return returnFunc(context1, getArtifactRegistryGithubAllowlistRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetArtifactRegistryGithubAllowlistRequest) *GetArtifactRegistryGithubAllowlistResponse); ok {
		r0 = returnFunc(context1, getArtifactRegistryGithubAllowlistRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetArtifactRegistryGithubAllowlistResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *GetArtifactRegistryGithubAllowlistRequest) error); ok {
		r1 = returnFunc(context1, getArtifactRegistryGithubAllowlistRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtifactRegistryServer_GetArtifactRegistryGithubAllowlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactRegistryGithubAllowlist'
type MockArtifactRegistryServer_GetArtifactRegistryGithubAllowlist_Call struct {
	*mock.Call
}

// GetArtifactRegistryGithubAllowlist is a helper method to define mock.On call
//   - context1 context.Context
//   - getArtifactRegistryGithubAllowlistRequest *GetArtifactRegistryGithubAllowlistRequest
func (_e *MockArtifactRegistryServer_Expecter) GetArtifactRegistryGithubAllowlist(context1 interface{}, getArtifactRegistryGithubAllowlistRequest interface{}) *MockArtifactRegistryServer_GetArtifactRegistryGithubAllowlist_Call {
	return &MockArtifactRegistryServer_GetArtifactRegistryGithubAllowlist_Call{Call: _e.mock.On("GetArtifactRegistryGithubAllowlist", context1, getArtifactRegistryGithubAllowlistRequest)}
}

func (_c *MockArtifactRegistryServer_GetArtifactRegistryGithubAllowlist_Call) Run(run func(context1 context.Context, getArtifactRegistryGithubAllowlistRequest *GetArtifactRegistryGithubAllowlistRequest)) *MockArtifactRegistryServer_GetArtifactRegistryGithubAllowlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *GetArtifactRegistryGithubAllowlistRequest
		if args[1] != nil {
			arg1 = args[1].(*GetArtifactRegistryGithubAllowlistRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtifactRegistryServer_GetArtifactRegistryGithubAllowlist_Call) Return(getArtifactRegistryGithubAllowlistResponse *GetArtifactRegistryGithubAllowlistResponse, err error) *MockArtifactRegistryServer_GetArtifactRegistryGithubAllowlist_Call {
	_c.Call.Return(getArtifactRegistryGithubAllowlistResponse, err)
	return _c
}

func (_c *MockArtifactRegistryServer_GetArtifactRegistryGithubAllowlist_Call) RunAndReturn(run func(context1 context.Context, getArtifactRegistryGithubAllowlistRequest *GetArtifactRegistryGithubAllowlistRequest) (*GetArtifactRegistryGithubAllowlistResponse, error)) *MockArtifactRegistryServer_GetArtifactRegistryGithubAllowlist_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifactRegistryRepo provides a mock function for the type MockArtifactRegistryServer
func (_mock *MockArtifactRegistryServer) GetArtifactRegistryRepo(context1 context.Context, getArtifactRegistryRepoRequest *GetArtifactRegistryRepoRequest) (*GetArtifactRegistryRepoResponse, error) {
	ret := _mock.Called(context1, getArtifactRegistryRepoRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactRegistryRepo")
	}

	var r0 *GetArtifactRegistryRepoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetArtifactRegistryRepoRequest) (*GetArtifactRegistryRepoResponse, error)); ok {
		return returnFunc(context1, getArtifactRegistryRepoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetArtifactRegistryRepoRequest) *GetArtifactRegistryRepoResponse); ok {
		r0 = returnFunc(context1, getArtifactRegistryRepoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetArtifactRegistryRepoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *GetArtifactRegistryRepoRequest) error); ok {
		r1 = returnFunc(context1, getArtifactRegistryRepoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtifactRegistryServer_GetArtifactRegistryRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactRegistryRepo'
type MockArtifactRegistryServer_GetArtifactRegistryRepo_Call struct {
	*mock.Call
}

// GetArtifactRegistryRepo is a helper method to define mock.On call
//   - context1 context.Context
//   - getArtifactRegistryRepoRequest *GetArtifactRegistryRepoRequest
func (_e *MockArtifactRegistryServer_Expecter) GetArtifactRegistryRepo(context1 interface{}, getArtifactRegistryRepoRequest interface{}) *MockArtifactRegistryServer_GetArtifactRegistryRepo_Call {
	return &MockArtifactRegistryServer_GetArtifactRegistryRepo_Call{Call: _e.mock.On("GetArtifactRegistryRepo", context1, getArtifactRegistryRepoRequest)}
}

func (_c *MockArtifactRegistryServer_GetArtifactRegistryRepo_Call) Run(run func(context1 context.Context, getArtifactRegistryRepoRequest *GetArtifactRegistryRepoRequest)) *MockArtifactRegistryServer_GetArtifactRegistryRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *GetArtifactRegistryRepoRequest
		if args[1] != nil {
			arg1 = args[1].(*GetArtifactRegistryRepoRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtifactRegistryServer_GetArtifactRegistryRepo_Call) Return(getArtifactRegistryRepoResponse *GetArtifactRegistryRepoResponse, err error) *MockArtifactRegistryServer_GetArtifactRegistryRepo_Call {
	_c.Call.Return(getArtifactRegistryRepoResponse, err)
	return _c
}

func (_c *MockArtifactRegistryServer_GetArtifactRegistryRepo_Call) RunAndReturn(run func(context1 context.Context, getArtifactRegistryRepoRequest *GetArtifactRegistryRepoRequest) (*GetArtifactRegistryRepoResponse, error)) *MockArtifactRegistryServer_GetArtifactRegistryRepo_Call {
	_c.Call.Return(run)
	return _c
}

// ListArtifactRegistryReposForTeam provides a mock function for the type MockArtifactRegistryServer
func (_mock *MockArtifactRegistryServer) ListArtifactRegistryReposForTeam(context1 context.Context, listArtifactRegistryReposForTeamRequest *ListArtifactRegistryReposForTeamRequest) (*ListArtifactRegistryReposForTeamResponse, error) {
	ret := _mock.Called(context1, listArtifactRegistryReposForTeamRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListArtifactRegistryReposForTeam")
	}

	var r0 *ListArtifactRegistryReposForTeamResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListArtifactRegistryReposForTeamRequest) (*ListArtifactRegistryReposForTeamResponse, error)); ok {
		return returnFunc(context1, listArtifactRegistryReposForTeamRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListArtifactRegistryReposForTeamRequest) *ListArtifactRegistryReposForTeamResponse); ok {
		r0 = returnFunc(context1, listArtifactRegistryReposForTeamRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ListArtifactRegistryReposForTeamResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ListArtifactRegistryReposForTeamRequest) error); ok {
		r1 = returnFunc(context1, listArtifactRegistryReposForTeamRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtifactRegistryServer_ListArtifactRegistryReposForTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArtifactRegistryReposForTeam'
type MockArtifactRegistryServer_ListArtifactRegistryReposForTeam_Call struct {
	*mock.Call
}

// ListArtifactRegistryReposForTeam is a helper method to define mock.On call
//   - context1 context.Context
//   - listArtifactRegistryReposForTeamRequest *ListArtifactRegistryReposForTeamRequest
func (_e *MockArtifactRegistryServer_Expecter) ListArtifactRegistryReposForTeam(context1 interface{}, listArtifactRegistryReposForTeamRequest interface{}) *MockArtifactRegistryServer_ListArtifactRegistryReposForTeam_Call {
	return &MockArtifactRegistryServer_ListArtifactRegistryReposForTeam_Call{Call: _e.mock.On("ListArtifactRegistryReposForTeam", context1, listArtifactRegistryReposForTeamRequest)}
}

func (_c *MockArtifactRegistryServer_ListArtifactRegistryReposForTeam_Call) Run(run func(context1 context.Context, listArtifactRegistryReposForTeamRequest *ListArtifactRegistryReposForTeamRequest)) *MockArtifactRegistryServer_ListArtifactRegistryReposForTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ListArtifactRegistryReposForTeamRequest
		if args[1] != nil {
			arg1 = args[1].(*ListArtifactRegistryReposForTeamRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtifactRegistryServer_ListArtifactRegistryReposForTeam_Call) Return(listArtifactRegistryReposForTeamResponse *ListArtifactRegistryReposForTeamResponse, err error) *MockArtifactRegistryServer_ListArtifactRegistryReposForTeam_Call {
	_c.Call.Return(listArtifactRegistryReposForTeamResponse, err)
	return _c
}

func (_c *MockArtifactRegistryServer_ListArtifactRegistryReposForTeam_Call) RunAndReturn(run func(context1 context.Context, listArtifactRegistryReposForTeamRequest *ListArtifactRegistryReposForTeamRequest) (*ListArtifactRegistryReposForTeamResponse, error)) *MockArtifactRegistryServer_ListArtifactRegistryReposForTeam_Call {
	_c.Call.Return(run)
	return _c
}

// SetArtifactRegistryRepoSizeBytes provides a mock function for the type MockArtifactRegistryServer
func (_mock *MockArtifactRegistryServer) SetArtifactRegistryRepoSizeBytes(context1 context.Context, setArtifactRegistryRepoSizeBytesRequest *SetArtifactRegistryRepoSizeBytesRequest) (*SetArtifactRegistryRepoSizeBytesResponse, error) {
	ret := _mock.Called(context1, setArtifactRegistryRepoSizeBytesRequest)

	if len(ret) == 0 {
		panic("no return value specified for SetArtifactRegistryRepoSizeBytes")
	}

	var r0 *SetArtifactRegistryRepoSizeBytesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SetArtifactRegistryRepoSizeBytesRequest) (*SetArtifactRegistryRepoSizeBytesResponse, error)); ok {
		return returnFunc(context1, setArtifactRegistryRepoSizeBytesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SetArtifactRegistryRepoSizeBytesRequest) *SetArtifactRegistryRepoSizeBytesResponse); ok {
		r0 = returnFunc(context1, setArtifactRegistryRepoSizeBytesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SetArtifactRegistryRepoSizeBytesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *SetArtifactRegistryRepoSizeBytesRequest) error); ok {
		r1 = returnFunc(context1, setArtifactRegistryRepoSizeBytesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtifactRegistryServer_SetArtifactRegistryRepoSizeBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetArtifactRegistryRepoSizeBytes'
type MockArtifactRegistryServer_SetArtifactRegistryRepoSizeBytes_Call struct {
	*mock.Call
}

// SetArtifactRegistryRepoSizeBytes is a helper method to define mock.On call
//   - context1 context.Context
//   - setArtifactRegistryRepoSizeBytesRequest *SetArtifactRegistryRepoSizeBytesRequest
func (_e *MockArtifactRegistryServer_Expecter) SetArtifactRegistryRepoSizeBytes(context1 interface{}, setArtifactRegistryRepoSizeBytesRequest interface{}) *MockArtifactRegistryServer_SetArtifactRegistryRepoSizeBytes_Call {
	return &MockArtifactRegistryServer_SetArtifactRegistryRepoSizeBytes_Call{Call: _e.mock.On("SetArtifactRegistryRepoSizeBytes", context1, setArtifactRegistryRepoSizeBytesRequest)}
}

func (_c *MockArtifactRegistryServer_SetArtifactRegistryRepoSizeBytes_Call) Run(run func(context1 context.Context, setArtifactRegistryRepoSizeBytesRequest *SetArtifactRegistryRepoSizeBytesRequest)) *MockArtifactRegistryServer_SetArtifactRegistryRepoSizeBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *SetArtifactRegistryRepoSizeBytesRequest
		if args[1] != nil {
			arg1 = args[1].(*SetArtifactRegistryRepoSizeBytesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtifactRegistryServer_SetArtifactRegistryRepoSizeBytes_Call) Return(setArtifactRegistryRepoSizeBytesResponse *SetArtifactRegistryRepoSizeBytesResponse, err error) *MockArtifactRegistryServer_SetArtifactRegistryRepoSizeBytes_Call {
	_c.Call.Return(setArtifactRegistryRepoSizeBytesResponse, err)
	return _c
}

func (_c *MockArtifactRegistryServer_SetArtifactRegistryRepoSizeBytes_Call) RunAndReturn(run func(context1 context.Context, setArtifactRegistryRepoSizeBytesRequest *SetArtifactRegistryRepoSizeBytesRequest) (*SetArtifactRegistryRepoSizeBytesResponse, error)) *MockArtifactRegistryServer_SetArtifactRegistryRepoSizeBytes_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedArtifactRegistryServer provides a mock function for the type MockArtifactRegistryServer
func (_mock *MockArtifactRegistryServer) mustEmbedUnimplementedArtifactRegistryServer() {
	_mock.Called()
	return
}

// MockArtifactRegistryServer_mustEmbedUnimplementedArtifactRegistryServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedArtifactRegistryServer'
type MockArtifactRegistryServer_mustEmbedUnimplementedArtifactRegistryServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedArtifactRegistryServer is a helper method to define mock.On call
func (_e *MockArtifactRegistryServer_Expecter) mustEmbedUnimplementedArtifactRegistryServer() *MockArtifactRegistryServer_mustEmbedUnimplementedArtifactRegistryServer_Call {
	return &MockArtifactRegistryServer_mustEmbedUnimplementedArtifactRegistryServer_Call{Call: _e.mock.On("mustEmbedUnimplementedArtifactRegistryServer")}
}

func (_c *MockArtifactRegistryServer_mustEmbedUnimplementedArtifactRegistryServer_Call) Run(run func()) *MockArtifactRegistryServer_mustEmbedUnimplementedArtifactRegistryServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArtifactRegistryServer_mustEmbedUnimplementedArtifactRegistryServer_Call) Return() *MockArtifactRegistryServer_mustEmbedUnimplementedArtifactRegistryServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockArtifactRegistryServer_mustEmbedUnimplementedArtifactRegistryServer_Call) RunAndReturn(run func()) *MockArtifactRegistryServer_mustEmbedUnimplementedArtifactRegistryServer_Call {
	_c.Run(run)
	return _c
}
