// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package protoapi

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAtlantisServer creates a new instance of MockAtlantisServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAtlantisServer(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockAtlantisServer {
	mock := &MockAtlantisServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAtlantisServer is an autogenerated mock type for the AtlantisServer type
type MockAtlantisServer struct {
	mock.Mock
}

type MockAtlantisServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAtlantisServer) EXPECT() *MockAtlantisServer_Expecter {
	return &MockAtlantisServer_Expecter{mock: &_m.Mock}
}

// GetTeamAtlantis provides a mock function for the type MockAtlantisServer
func (_mock *MockAtlantisServer) GetTeamAtlantis(context1 context.Context, getTeamAtlantisRequest *GetTeamAtlantisRequest) (*GetTeamAtlantisResponse, error) {
	ret := _mock.Called(context1, getTeamAtlantisRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamAtlantis")
	}

	var r0 *GetTeamAtlantisResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetTeamAtlantisRequest) (*GetTeamAtlantisResponse, error)); ok {
		return returnFunc(context1, getTeamAtlantisRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetTeamAtlantisRequest) *GetTeamAtlantisResponse); ok {
		r0 = returnFunc(context1, getTeamAtlantisRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetTeamAtlantisResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *GetTeamAtlantisRequest) error); ok {
		r1 = returnFunc(context1, getTeamAtlantisRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAtlantisServer_GetTeamAtlantis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamAtlantis'
type MockAtlantisServer_GetTeamAtlantis_Call struct {
	*mock.Call
}

// GetTeamAtlantis is a helper method to define mock.On call
//   - context1 context.Context
//   - getTeamAtlantisRequest *GetTeamAtlantisRequest
func (_e *MockAtlantisServer_Expecter) GetTeamAtlantis(context1 interface{}, getTeamAtlantisRequest interface{}) *MockAtlantisServer_GetTeamAtlantis_Call {
	return &MockAtlantisServer_GetTeamAtlantis_Call{Call: _e.mock.On("GetTeamAtlantis", context1, getTeamAtlantisRequest)}
}

func (_c *MockAtlantisServer_GetTeamAtlantis_Call) Run(run func(context1 context.Context, getTeamAtlantisRequest *GetTeamAtlantisRequest)) *MockAtlantisServer_GetTeamAtlantis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *GetTeamAtlantisRequest
		if args[1] != nil {
			arg1 = args[1].(*GetTeamAtlantisRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAtlantisServer_GetTeamAtlantis_Call) Return(getTeamAtlantisResponse *GetTeamAtlantisResponse, err error) *MockAtlantisServer_GetTeamAtlantis_Call {
	_c.Call.Return(getTeamAtlantisResponse, err)
	return _c
}

func (_c *MockAtlantisServer_GetTeamAtlantis_Call) RunAndReturn(run func(context1 context.Context, getTeamAtlantisRequest *GetTeamAtlantisRequest) (*GetTeamAtlantisResponse, error)) *MockAtlantisServer_GetTeamAtlantis_Call {
	_c.Call.Return(run)
	return _c
}

// SetTeamAtlantisWebhookSecret provides a mock function for the type MockAtlantisServer
func (_mock *MockAtlantisServer) SetTeamAtlantisWebhookSecret(context1 context.Context, setTeamAtlantisWebhookSecretRequest *SetTeamAtlantisWebhookSecretRequest) (*SetTeamAtlantisWebhookSecretResponse, error) {
	ret := _mock.Called(context1, setTeamAtlantisWebhookSecretRequest)

	if len(ret) == 0 {
		panic("no return value specified for SetTeamAtlantisWebhookSecret")
	}

	var r0 *SetTeamAtlantisWebhookSecretResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SetTeamAtlantisWebhookSecretRequest) (*SetTeamAtlantisWebhookSecretResponse, error)); ok {
		return returnFunc(context1, setTeamAtlantisWebhookSecretRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SetTeamAtlantisWebhookSecretRequest) *SetTeamAtlantisWebhookSecretResponse); ok {
		r0 = returnFunc(context1, setTeamAtlantisWebhookSecretRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SetTeamAtlantisWebhookSecretResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *SetTeamAtlantisWebhookSecretRequest) error); ok {
		r1 = returnFunc(context1, setTeamAtlantisWebhookSecretRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAtlantisServer_SetTeamAtlantisWebhookSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTeamAtlantisWebhookSecret'
type MockAtlantisServer_SetTeamAtlantisWebhookSecret_Call struct {
	*mock.Call
}

// SetTeamAtlantisWebhookSecret is a helper method to define mock.On call
//   - context1 context.Context
//   - setTeamAtlantisWebhookSecretRequest *SetTeamAtlantisWebhookSecretRequest
func (_e *MockAtlantisServer_Expecter) SetTeamAtlantisWebhookSecret(context1 interface{}, setTeamAtlantisWebhookSecretRequest interface{}) *MockAtlantisServer_SetTeamAtlantisWebhookSecret_Call {
	return &MockAtlantisServer_SetTeamAtlantisWebhookSecret_Call{Call: _e.mock.On("SetTeamAtlantisWebhookSecret", context1, setTeamAtlantisWebhookSecretRequest)}
}

func (_c *MockAtlantisServer_SetTeamAtlantisWebhookSecret_Call) Run(run func(context1 context.Context, setTeamAtlantisWebhookSecretRequest *SetTeamAtlantisWebhookSecretRequest)) *MockAtlantisServer_SetTeamAtlantisWebhookSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *SetTeamAtlantisWebhookSecretRequest
		if args[1] != nil {
			arg1 = args[1].(*SetTeamAtlantisWebhookSecretRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAtlantisServer_SetTeamAtlantisWebhookSecret_Call) Return(setTeamAtlantisWebhookSecretResponse *SetTeamAtlantisWebhookSecretResponse, err error) *MockAtlantisServer_SetTeamAtlantisWebhookSecret_Call {
	_c.Call.Return(setTeamAtlantisWebhookSecretResponse, err)
	return _c
}

func (_c *MockAtlantisServer_SetTeamAtlantisWebhookSecret_Call) RunAndReturn(run func(context1 context.Context, setTeamAtlantisWebhookSecretRequest *SetTeamAtlantisWebhookSecretRequest) (*SetTeamAtlantisWebhookSecretResponse, error)) *MockAtlantisServer_SetTeamAtlantisWebhookSecret_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedAtlantisServer provides a mock function for the type MockAtlantisServer
func (_mock *MockAtlantisServer) mustEmbedUnimplementedAtlantisServer() {
	_mock.Called()
	return
}

// MockAtlantisServer_mustEmbedUnimplementedAtlantisServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedAtlantisServer'
type MockAtlantisServer_mustEmbedUnimplementedAtlantisServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedAtlantisServer is a helper method to define mock.On call
func (_e *MockAtlantisServer_Expecter) mustEmbedUnimplementedAtlantisServer() *MockAtlantisServer_mustEmbedUnimplementedAtlantisServer_Call {
	return &MockAtlantisServer_mustEmbedUnimplementedAtlantisServer_Call{Call: _e.mock.On("mustEmbedUnimplementedAtlantisServer")}
}

func (_c *MockAtlantisServer_mustEmbedUnimplementedAtlantisServer_Call) Run(run func()) *MockAtlantisServer_mustEmbedUnimplementedAtlantisServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAtlantisServer_mustEmbedUnimplementedAtlantisServer_Call) Return() *MockAtlantisServer_mustEmbedUnimplementedAtlantisServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAtlantisServer_mustEmbedUnimplementedAtlantisServer_Call) RunAndReturn(run func()) *MockAtlantisServer_mustEmbedUnimplementedAtlantisServer_Call {
	_c.Run(run)
	return _c
}
