query Groups($team: Slug!) {
	team(slug: $team) {
		id
		slug
		groups(first: 20) {
			nodes {
				id
				name
				members(first: 20) {
					pageInfo {
						totalCount
						hasNextPage
						hasPreviousPage
						pageStart
						pageEnd
						startCursor
						endCursor
					}
					nodes {
						user {
							id
							name
							email
						}
					}
				}
			}
		}
	}
}
