// Code generated by sqlc. DO NOT EDIT.

package grpcsharedbucketsstopgapsql

import (
	"github.com/statisticsnorway/dapla-api/internal/slug"
)

type Group struct {
	Name       string
	TeamSlug   slug.Slug
	Category   string
	Suffix     string
	ExternalID *string
}

type SharedBucketsStopgap struct {
	Name      string
	TeamSlug  slug.Slug
	ShortName string
	Kind      string
	Env       string
}
