// Code generated by sqlc. DO NOT EDIT.

package grpcsharedbucketsstopgapsql

import (
	"context"
)

type Querier interface {
	AddGroup(ctx context.Context, arg AddGroupParams) error
	Create(ctx context.Context, arg CreateParams) error
	Get(ctx context.Context, arg GetParams) (*GetRow, error)
	ListGroups(ctx context.Context, name string) ([]*ListGroupsRow, error)
	RemoveGroup(ctx context.Context, arg RemoveGroupParams) error
}

var _ Querier = (*Queries)(nil)
