// Code generated by sqlc. DO NOT EDIT.

package grpcsharedbucketsstopgapsql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

type Querier interface {
	AddGroup(ctx context.Context, arg AddGroupParams) error
	Create(ctx context.Context, arg CreateParams) error
	Delete(ctx context.Context, arg DeleteParams) error
	Get(ctx context.Context, arg GetParams) (*GetRow, error)
	ListForTeam(ctx context.Context, teamSlug slug.Slug) ([]*ListForTeamRow, error)
	ListGroups(ctx context.Context, name string) ([]*ListGroupsRow, error)
	RemoveGroup(ctx context.Context, arg RemoveGroupParams) error
}

var _ Querier = (*Queries)(nil)
