// Code generated by sqlc. DO NOT EDIT.
// source: sharedbucketsstopgap.sql

package grpcsharedbucketsstopgapsql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

const addGroup = `-- name: AddGroup :exec
INSERT INTO
	shared_buckets_access_stopgap (bucket_name, group_name)
VALUES
	($1, $2)
`

type AddGroupParams struct {
	BucketName string
	GroupName  string
}

func (q *Queries) AddGroup(ctx context.Context, arg AddGroupParams) error {
	_, err := q.db.Exec(ctx, addGroup, arg.BucketName, arg.GroupName)
	return err
}

const create = `-- name: Create :exec
INSERT INTO
	shared_buckets_stopgap (name, team_slug, short_name, kind, env)
VALUES
	($1, $2, $3, $4, $5)
`

type CreateParams struct {
	Name      string
	TeamSlug  slug.Slug
	ShortName string
	Kind      string
	Env       string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create,
		arg.Name,
		arg.TeamSlug,
		arg.ShortName,
		arg.Kind,
		arg.Env,
	)
	return err
}

const get = `-- name: Get :one
SELECT
	shared_buckets_stopgap.name, shared_buckets_stopgap.team_slug, shared_buckets_stopgap.short_name, shared_buckets_stopgap.kind, shared_buckets_stopgap.env
FROM
	shared_buckets_stopgap
WHERE
	team_slug = $1
	AND short_name = $2
	AND kind = $3
	AND env = $4
`

type GetParams struct {
	TeamSlug  slug.Slug
	ShortName string
	Kind      string
	Env       string
}

type GetRow struct {
	SharedBucketsStopgap SharedBucketsStopgap
}

func (q *Queries) Get(ctx context.Context, arg GetParams) (*GetRow, error) {
	row := q.db.QueryRow(ctx, get,
		arg.TeamSlug,
		arg.ShortName,
		arg.Kind,
		arg.Env,
	)
	var i GetRow
	err := row.Scan(
		&i.SharedBucketsStopgap.Name,
		&i.SharedBucketsStopgap.TeamSlug,
		&i.SharedBucketsStopgap.ShortName,
		&i.SharedBucketsStopgap.Kind,
		&i.SharedBucketsStopgap.Env,
	)
	return &i, err
}

const listGroups = `-- name: ListGroups :many
SELECT
	groups.name, groups.team_slug, groups.category, groups.suffix, groups.external_id
FROM
	groups
	JOIN shared_buckets_access_stopgap ON groups.name = shared_buckets_access_stopgap.group_name
WHERE
	shared_buckets_access_stopgap.bucket_name = $1
ORDER BY
	bucket_name
`

type ListGroupsRow struct {
	Group Group
}

func (q *Queries) ListGroups(ctx context.Context, name string) ([]*ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListGroupsRow{}
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.Group.Name,
			&i.Group.TeamSlug,
			&i.Group.Category,
			&i.Group.Suffix,
			&i.Group.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroup = `-- name: RemoveGroup :exec
DELETE FROM shared_buckets_access_stopgap
WHERE
	bucket_name = $1
	AND group_name = $2
`

type RemoveGroupParams struct {
	BucketName string
	GroupName  string
}

func (q *Queries) RemoveGroup(ctx context.Context, arg RemoveGroupParams) error {
	_, err := q.db.Exec(ctx, removeGroup, arg.BucketName, arg.GroupName)
	return err
}
