// Code generated by sqlc. DO NOT EDIT.

package sectionsql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetByCodes(ctx context.Context, codes []string) ([]*Section, error)
	GetByManagerId(ctx context.Context, userID *uuid.UUID) (*Section, error)
	List(ctx context.Context, arg ListParams) ([]*ListRow, error)
}

var _ Querier = (*Queries)(nil)
