// Code generated by sqlc. DO NOT EDIT.

package artifactregistrysql

import (
	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

type TeamArtifactRegistryRepository struct {
	TeamSlug  slug.Slug
	Format    string
	SizeBytes int64
}
