// Code generated by sqlc. DO NOT EDIT.

package artifactregistrysql

import (
	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

type TeamArtifactRegistryGithubRepository struct {
	TeamSlug         slug.Slug
	GithubRepository string
}
