// Code generated by sqlc. DO NOT EDIT.

package artifactregistrysql

import (
	"context"
)

type Querier interface {
	AddGithubRepositoryToTeam(ctx context.Context, arg AddGithubRepositoryToTeamParams) (*TeamArtifactRegistryGithubRepository, error)
	ListGithubReposForTeam(ctx context.Context, arg ListGithubReposForTeamParams) ([]*ListGithubReposForTeamRow, error)
	RemoveGithubRepositoryFromTeam(ctx context.Context, arg RemoveGithubRepositoryFromTeamParams) error
}

var _ Querier = (*Queries)(nil)
