// Code generated by sqlc. DO NOT EDIT.
// source: repository.sql

package artifactregistrysql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

const listForTeam = `-- name: ListForTeam :many
SELECT
	team_artifact_registry_repositories.team_slug, team_artifact_registry_repositories.format, team_artifact_registry_repositories.size_bytes,
	COUNT(*) OVER () AS total_count
FROM
	team_artifact_registry_repositories
WHERE
	team_slug = $1
ORDER BY
	format ASC
LIMIT
	$3
OFFSET
	$2
`

type ListForTeamParams struct {
	TeamSlug slug.Slug
	Offset   int32
	Limit    int32
}

type ListForTeamRow struct {
	TeamArtifactRegistryRepository TeamArtifactRegistryRepository
	TotalCount                     int64
}

func (q *Queries) ListForTeam(ctx context.Context, arg ListForTeamParams) ([]*ListForTeamRow, error) {
	rows, err := q.db.Query(ctx, listForTeam, arg.TeamSlug, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListForTeamRow{}
	for rows.Next() {
		var i ListForTeamRow
		if err := rows.Scan(
			&i.TeamArtifactRegistryRepository.TeamSlug,
			&i.TeamArtifactRegistryRepository.Format,
			&i.TeamArtifactRegistryRepository.SizeBytes,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
