// Code generated by metago; DO NOT EDIT.

package artifactregistry

import (
	"fmt"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/model"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/pagination"
	"io"
	"slices"
	"strconv"
	"strings"
)

type (
	ArtifactRegistryAllowedGithubReposConnection = pagination.Connection[*ArtifactRegistryAllowedGithubRepos]
	ArtifactRegistryAllowedGithubReposEdge       = pagination.Edge[*ArtifactRegistryAllowedGithubRepos]
)

func (ArtifactRegistryAllowedGithubRepos) IsNode() {}

type ArtifactRegistryAllowedGithubReposOrder struct {
	Field     ArtifactRegistryAllowedGithubReposOrderField `json:"field"`
	Direction model.OrderDirection                         `json:"direction"`
}

func (o *ArtifactRegistryAllowedGithubReposOrder) String() string {
	if o == nil {
		return ""
	}

	return strings.ToLower(o.Field.String() + ":" + o.Direction.String())
}

type ArtifactRegistryAllowedGithubReposOrderField string

const (
	ArtifactRegistryAllowedGithubReposOrderFieldName ArtifactRegistryAllowedGithubReposOrderField = "NAME"
)

var AllArtifactRegistryAllowedGithubReposOrderFields = []ArtifactRegistryAllowedGithubReposOrderField{
	ArtifactRegistryAllowedGithubReposOrderFieldName,
}

func (e ArtifactRegistryAllowedGithubReposOrderField) IsValid() bool {
	return slices.Contains(AllArtifactRegistryAllowedGithubReposOrderFields, e)
}

func (e ArtifactRegistryAllowedGithubReposOrderField) String() string {
	return string(e)
}

func (e *ArtifactRegistryAllowedGithubReposOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ArtifactRegistryAllowedGithubReposOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ArtifactRegistryAllowedGithubReposOrderField", str)
	}
	return nil
}

func (e ArtifactRegistryAllowedGithubReposOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
