// Code generated by metago; DO NOT EDIT.

package artifactregistry

import (
	"fmt"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/model"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/pagination"
	"io"
	"slices"
	"strconv"
	"strings"
)

type (
	ArtifactRegistryGithubRepositoryConnection = pagination.Connection[*ArtifactRegistryGithubRepository]
	ArtifactRegistryGithubRepositoryEdge       = pagination.Edge[*ArtifactRegistryGithubRepository]
)

func (ArtifactRegistryGithubRepository) IsNode() {}

type ArtifactRegistryGithubRepositoryOrder struct {
	Field     ArtifactRegistryGithubRepositoryOrderField `json:"field"`
	Direction model.OrderDirection                       `json:"direction"`
}

func (o *ArtifactRegistryGithubRepositoryOrder) String() string {
	if o == nil {
		return ""
	}

	return strings.ToLower(o.Field.String() + ":" + o.Direction.String())
}

type ArtifactRegistryGithubRepositoryOrderField string

const (
	ArtifactRegistryGithubRepositoryOrderFieldName ArtifactRegistryGithubRepositoryOrderField = "NAME"
)

var AllArtifactRegistryGithubRepositoryOrderFields = []ArtifactRegistryGithubRepositoryOrderField{
	ArtifactRegistryGithubRepositoryOrderFieldName,
}

func (e ArtifactRegistryGithubRepositoryOrderField) IsValid() bool {
	return slices.Contains(AllArtifactRegistryGithubRepositoryOrderFields, e)
}

func (e ArtifactRegistryGithubRepositoryOrderField) String() string {
	return string(e)
}

func (e *ArtifactRegistryGithubRepositoryOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ArtifactRegistryGithubRepositoryOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ArtifactRegistryGithubRepositoryOrderField", str)
	}
	return nil
}

func (e ArtifactRegistryGithubRepositoryOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
