// Code generated by sqlc. DO NOT EDIT.
// source: authz.sql

package authzsql

import (
	"context"

	"github.com/google/uuid"
	"github.com/statisticsnorway/dapla-api/internal/slug"
)

const isGlobalAdmin = `-- name: IsGlobalAdmin :one
SELECT
	(
		EXISTS (
			SELECT
				1
			FROM
				users
			WHERE
				id = $1
				AND admin = TRUE
		)
	)
`

func (q *Queries) IsGlobalAdmin(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isGlobalAdmin, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isManagerForTeamSection = `-- name: IsManagerForTeamSection :one
SELECT
	(
		(
			EXISTS (
				SELECT
					1
				FROM
					sections
					JOIN teams ON teams.section_code = sections.code
				WHERE
					sections.manager_id = $1
					AND teams.slug = $2::slug
			)
		)
	)
`

type IsManagerForTeamSectionParams struct {
	UserID   *uuid.UUID
	TeamSlug slug.Slug
}

func (q *Queries) IsManagerForTeamSection(ctx context.Context, arg IsManagerForTeamSectionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isManagerForTeamSection, arg.UserID, arg.TeamSlug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isSectionManager = `-- name: IsSectionManager :one
SELECT
	(
		EXISTS (
			SELECT
				1
			FROM
				sections
			WHERE
				manager_id = $1
		)
	)
`

func (q *Queries) IsSectionManager(ctx context.Context, userID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isSectionManager, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
