// Code generated by metago; DO NOT EDIT.

package section

import (
	"fmt"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/model"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/pagination"
	"io"
	"slices"
	"strconv"
	"strings"
)

type (
	SectionConnection = pagination.Connection[*Section]
	SectionEdge       = pagination.Edge[*Section]
)

func (Section) IsNode() {}

type SectionOrder struct {
	Field     SectionOrderField    `json:"field"`
	Direction model.OrderDirection `json:"direction"`
}

func (o *SectionOrder) String() string {
	if o == nil {
		return ""
	}

	return strings.ToLower(o.Field.String() + ":" + o.Direction.String())
}

type SectionOrderField string

const (
	SectionOrderFieldName SectionOrderField = "NAME"
	SectionOrderFieldCode SectionOrderField = "CODE"
)

var AllSectionOrderFields = []SectionOrderField{
	SectionOrderFieldName,
	SectionOrderFieldCode,
}

func (e SectionOrderField) IsValid() bool {
	return slices.Contains(AllSectionOrderFields, e)
}

func (e SectionOrderField) String() string {
	return string(e)
}

func (e *SectionOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SectionOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SectionOrderField", str)
	}
	return nil
}

func (e SectionOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
