// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package protoapi

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGroupsServer creates a new instance of MockGroupsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupsServer(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockGroupsServer {
	mock := &MockGroupsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupsServer is an autogenerated mock type for the GroupsServer type
type MockGroupsServer struct {
	mock.Mock
}

type MockGroupsServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupsServer) EXPECT() *MockGroupsServer_Expecter {
	return &MockGroupsServer_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockGroupsServer
func (_mock *MockGroupsServer) Get(context1 context.Context, getGroupRequest *GetGroupRequest) (*GetGroupResponse, error) {
	ret := _mock.Called(context1, getGroupRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *GetGroupResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetGroupRequest) (*GetGroupResponse, error)); ok {
		return returnFunc(context1, getGroupRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetGroupRequest) *GetGroupResponse); ok {
		r0 = returnFunc(context1, getGroupRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetGroupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *GetGroupRequest) error); ok {
		r1 = returnFunc(context1, getGroupRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupsServer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGroupsServer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - getGroupRequest *GetGroupRequest
func (_e *MockGroupsServer_Expecter) Get(context1 interface{}, getGroupRequest interface{}) *MockGroupsServer_Get_Call {
	return &MockGroupsServer_Get_Call{Call: _e.mock.On("Get", context1, getGroupRequest)}
}

func (_c *MockGroupsServer_Get_Call) Run(run func(context1 context.Context, getGroupRequest *GetGroupRequest)) *MockGroupsServer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *GetGroupRequest
		if args[1] != nil {
			arg1 = args[1].(*GetGroupRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupsServer_Get_Call) Return(getGroupResponse *GetGroupResponse, err error) *MockGroupsServer_Get_Call {
	_c.Call.Return(getGroupResponse, err)
	return _c
}

func (_c *MockGroupsServer_Get_Call) RunAndReturn(run func(context1 context.Context, getGroupRequest *GetGroupRequest) (*GetGroupResponse, error)) *MockGroupsServer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Members provides a mock function for the type MockGroupsServer
func (_mock *MockGroupsServer) Members(context1 context.Context, listGroupMembersRequest *ListGroupMembersRequest) (*ListGroupMembersResponse, error) {
	ret := _mock.Called(context1, listGroupMembersRequest)

	if len(ret) == 0 {
		panic("no return value specified for Members")
	}

	var r0 *ListGroupMembersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListGroupMembersRequest) (*ListGroupMembersResponse, error)); ok {
		return returnFunc(context1, listGroupMembersRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListGroupMembersRequest) *ListGroupMembersResponse); ok {
		r0 = returnFunc(context1, listGroupMembersRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ListGroupMembersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ListGroupMembersRequest) error); ok {
		r1 = returnFunc(context1, listGroupMembersRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupsServer_Members_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Members'
type MockGroupsServer_Members_Call struct {
	*mock.Call
}

// Members is a helper method to define mock.On call
//   - context1 context.Context
//   - listGroupMembersRequest *ListGroupMembersRequest
func (_e *MockGroupsServer_Expecter) Members(context1 interface{}, listGroupMembersRequest interface{}) *MockGroupsServer_Members_Call {
	return &MockGroupsServer_Members_Call{Call: _e.mock.On("Members", context1, listGroupMembersRequest)}
}

func (_c *MockGroupsServer_Members_Call) Run(run func(context1 context.Context, listGroupMembersRequest *ListGroupMembersRequest)) *MockGroupsServer_Members_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ListGroupMembersRequest
		if args[1] != nil {
			arg1 = args[1].(*ListGroupMembersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupsServer_Members_Call) Return(listGroupMembersResponse *ListGroupMembersResponse, err error) *MockGroupsServer_Members_Call {
	_c.Call.Return(listGroupMembersResponse, err)
	return _c
}

func (_c *MockGroupsServer_Members_Call) RunAndReturn(run func(context1 context.Context, listGroupMembersRequest *ListGroupMembersRequest) (*ListGroupMembersResponse, error)) *MockGroupsServer_Members_Call {
	_c.Call.Return(run)
	return _c
}

// SetExternalId provides a mock function for the type MockGroupsServer
func (_mock *MockGroupsServer) SetExternalId(context1 context.Context, setExternalIdRequest *SetExternalIdRequest) (*SetExternalIdResponse, error) {
	ret := _mock.Called(context1, setExternalIdRequest)

	if len(ret) == 0 {
		panic("no return value specified for SetExternalId")
	}

	var r0 *SetExternalIdResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SetExternalIdRequest) (*SetExternalIdResponse, error)); ok {
		return returnFunc(context1, setExternalIdRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SetExternalIdRequest) *SetExternalIdResponse); ok {
		r0 = returnFunc(context1, setExternalIdRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SetExternalIdResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *SetExternalIdRequest) error); ok {
		r1 = returnFunc(context1, setExternalIdRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupsServer_SetExternalId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExternalId'
type MockGroupsServer_SetExternalId_Call struct {
	*mock.Call
}

// SetExternalId is a helper method to define mock.On call
//   - context1 context.Context
//   - setExternalIdRequest *SetExternalIdRequest
func (_e *MockGroupsServer_Expecter) SetExternalId(context1 interface{}, setExternalIdRequest interface{}) *MockGroupsServer_SetExternalId_Call {
	return &MockGroupsServer_SetExternalId_Call{Call: _e.mock.On("SetExternalId", context1, setExternalIdRequest)}
}

func (_c *MockGroupsServer_SetExternalId_Call) Run(run func(context1 context.Context, setExternalIdRequest *SetExternalIdRequest)) *MockGroupsServer_SetExternalId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *SetExternalIdRequest
		if args[1] != nil {
			arg1 = args[1].(*SetExternalIdRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupsServer_SetExternalId_Call) Return(setExternalIdResponse *SetExternalIdResponse, err error) *MockGroupsServer_SetExternalId_Call {
	_c.Call.Return(setExternalIdResponse, err)
	return _c
}

func (_c *MockGroupsServer_SetExternalId_Call) RunAndReturn(run func(context1 context.Context, setExternalIdRequest *SetExternalIdRequest) (*SetExternalIdResponse, error)) *MockGroupsServer_SetExternalId_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedGroupsServer provides a mock function for the type MockGroupsServer
func (_mock *MockGroupsServer) mustEmbedUnimplementedGroupsServer() {
	_mock.Called()
	return
}

// MockGroupsServer_mustEmbedUnimplementedGroupsServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedGroupsServer'
type MockGroupsServer_mustEmbedUnimplementedGroupsServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedGroupsServer is a helper method to define mock.On call
func (_e *MockGroupsServer_Expecter) mustEmbedUnimplementedGroupsServer() *MockGroupsServer_mustEmbedUnimplementedGroupsServer_Call {
	return &MockGroupsServer_mustEmbedUnimplementedGroupsServer_Call{Call: _e.mock.On("mustEmbedUnimplementedGroupsServer")}
}

func (_c *MockGroupsServer_mustEmbedUnimplementedGroupsServer_Call) Run(run func()) *MockGroupsServer_mustEmbedUnimplementedGroupsServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGroupsServer_mustEmbedUnimplementedGroupsServer_Call) Return() *MockGroupsServer_mustEmbedUnimplementedGroupsServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGroupsServer_mustEmbedUnimplementedGroupsServer_Call) RunAndReturn(run func()) *MockGroupsServer_mustEmbedUnimplementedGroupsServer_Call {
	_c.Run(run)
	return _c
}
