// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: teams.proto

//go:build protoopaque

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Team struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Slug                 string                 `protobuf:"bytes,1,opt,name=slug,proto3"`
	xxx_hidden_Purpose              string                 `protobuf:"bytes,2,opt,name=purpose,proto3"`
	xxx_hidden_DeleteKeyConfirmedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=delete_key_confirmed_at,json=deleteKeyConfirmedAt,proto3,oneof"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_teams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Team) GetSlug() string {
	if x != nil {
		return x.xxx_hidden_Slug
	}
	return ""
}

func (x *Team) GetPurpose() string {
	if x != nil {
		return x.xxx_hidden_Purpose
	}
	return ""
}

func (x *Team) GetDeleteKeyConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DeleteKeyConfirmedAt
	}
	return nil
}

func (x *Team) SetSlug(v string) {
	x.xxx_hidden_Slug = v
}

func (x *Team) SetPurpose(v string) {
	x.xxx_hidden_Purpose = v
}

func (x *Team) SetDeleteKeyConfirmedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_DeleteKeyConfirmedAt = v
}

func (x *Team) HasDeleteKeyConfirmedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeleteKeyConfirmedAt != nil
}

func (x *Team) ClearDeleteKeyConfirmedAt() {
	x.xxx_hidden_DeleteKeyConfirmedAt = nil
}

type Team_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Slug                 string
	Purpose              string
	DeleteKeyConfirmedAt *timestamppb.Timestamp
}

func (b0 Team_builder) Build() *Team {
	m0 := &Team{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Slug = b.Slug
	x.xxx_hidden_Purpose = b.Purpose
	x.xxx_hidden_DeleteKeyConfirmedAt = b.DeleteKeyConfirmedAt
	return m0
}

type DeleteTeamRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Slug string                 `protobuf:"bytes,1,opt,name=slug,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteTeamRequest) Reset() {
	*x = DeleteTeamRequest{}
	mi := &file_teams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequest) ProtoMessage() {}

func (x *DeleteTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteTeamRequest) GetSlug() string {
	if x != nil {
		return x.xxx_hidden_Slug
	}
	return ""
}

func (x *DeleteTeamRequest) SetSlug(v string) {
	x.xxx_hidden_Slug = v
}

type DeleteTeamRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Slug string
}

func (b0 DeleteTeamRequest_builder) Build() *DeleteTeamRequest {
	m0 := &DeleteTeamRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Slug = b.Slug
	return m0
}

type DeleteTeamResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamResponse) Reset() {
	*x = DeleteTeamResponse{}
	mi := &file_teams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamResponse) ProtoMessage() {}

func (x *DeleteTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteTeamResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteTeamResponse_builder) Build() *DeleteTeamResponse {
	m0 := &DeleteTeamResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListTeamEnvironmentsRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit  int64                  `protobuf:"varint,1,opt,name=limit,proto3"`
	xxx_hidden_Offset int64                  `protobuf:"varint,2,opt,name=offset,proto3"`
	xxx_hidden_Slug   string                 `protobuf:"bytes,3,opt,name=slug,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListTeamEnvironmentsRequest) Reset() {
	*x = ListTeamEnvironmentsRequest{}
	mi := &file_teams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamEnvironmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamEnvironmentsRequest) ProtoMessage() {}

func (x *ListTeamEnvironmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTeamEnvironmentsRequest) GetLimit() int64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListTeamEnvironmentsRequest) GetOffset() int64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListTeamEnvironmentsRequest) GetSlug() string {
	if x != nil {
		return x.xxx_hidden_Slug
	}
	return ""
}

func (x *ListTeamEnvironmentsRequest) SetLimit(v int64) {
	x.xxx_hidden_Limit = v
}

func (x *ListTeamEnvironmentsRequest) SetOffset(v int64) {
	x.xxx_hidden_Offset = v
}

func (x *ListTeamEnvironmentsRequest) SetSlug(v string) {
	x.xxx_hidden_Slug = v
}

type ListTeamEnvironmentsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit  int64
	Offset int64
	Slug   string
}

func (b0 ListTeamEnvironmentsRequest_builder) Build() *ListTeamEnvironmentsRequest {
	m0 := &ListTeamEnvironmentsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_Slug = b.Slug
	return m0
}

type ListTeamEnvironmentsResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes    *[]*TeamEnvironment    `protobuf:"bytes,1,rep,name=nodes,proto3"`
	xxx_hidden_PageInfo *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListTeamEnvironmentsResponse) Reset() {
	*x = ListTeamEnvironmentsResponse{}
	mi := &file_teams_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamEnvironmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamEnvironmentsResponse) ProtoMessage() {}

func (x *ListTeamEnvironmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTeamEnvironmentsResponse) GetNodes() []*TeamEnvironment {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *ListTeamEnvironmentsResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.xxx_hidden_PageInfo
	}
	return nil
}

func (x *ListTeamEnvironmentsResponse) SetNodes(v []*TeamEnvironment) {
	x.xxx_hidden_Nodes = &v
}

func (x *ListTeamEnvironmentsResponse) SetPageInfo(v *PageInfo) {
	x.xxx_hidden_PageInfo = v
}

func (x *ListTeamEnvironmentsResponse) HasPageInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PageInfo != nil
}

func (x *ListTeamEnvironmentsResponse) ClearPageInfo() {
	x.xxx_hidden_PageInfo = nil
}

type ListTeamEnvironmentsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes    []*TeamEnvironment
	PageInfo *PageInfo
}

func (b0 ListTeamEnvironmentsResponse_builder) Build() *ListTeamEnvironmentsResponse {
	m0 := &ListTeamEnvironmentsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = &b.Nodes
	x.xxx_hidden_PageInfo = b.PageInfo
	return m0
}

type TeamEnvironment struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id              string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Slug            string                 `protobuf:"bytes,2,opt,name=slug,proto3"`
	xxx_hidden_EnvironmentName string                 `protobuf:"bytes,3,opt,name=environment_name,json=environmentName,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TeamEnvironment) Reset() {
	*x = TeamEnvironment{}
	mi := &file_teams_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEnvironment) ProtoMessage() {}

func (x *TeamEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TeamEnvironment) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *TeamEnvironment) GetSlug() string {
	if x != nil {
		return x.xxx_hidden_Slug
	}
	return ""
}

func (x *TeamEnvironment) GetEnvironmentName() string {
	if x != nil {
		return x.xxx_hidden_EnvironmentName
	}
	return ""
}

func (x *TeamEnvironment) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *TeamEnvironment) SetSlug(v string) {
	x.xxx_hidden_Slug = v
}

func (x *TeamEnvironment) SetEnvironmentName(v string) {
	x.xxx_hidden_EnvironmentName = v
}

type TeamEnvironment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id              string
	Slug            string
	EnvironmentName string
}

func (b0 TeamEnvironment_builder) Build() *TeamEnvironment {
	m0 := &TeamEnvironment{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Slug = b.Slug
	x.xxx_hidden_EnvironmentName = b.EnvironmentName
	return m0
}

type GetTeamResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Team *Team                  `protobuf:"bytes,1,opt,name=team,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTeamResponse) Reset() {
	*x = GetTeamResponse{}
	mi := &file_teams_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamResponse) ProtoMessage() {}

func (x *GetTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.xxx_hidden_Team
	}
	return nil
}

func (x *GetTeamResponse) SetTeam(v *Team) {
	x.xxx_hidden_Team = v
}

func (x *GetTeamResponse) HasTeam() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Team != nil
}

func (x *GetTeamResponse) ClearTeam() {
	x.xxx_hidden_Team = nil
}

type GetTeamResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Team *Team
}

func (b0 GetTeamResponse_builder) Build() *GetTeamResponse {
	m0 := &GetTeamResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Team = b.Team
	return m0
}

type GetTeamRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Slug string                 `protobuf:"bytes,1,opt,name=slug,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_teams_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetTeamRequest) GetSlug() string {
	if x != nil {
		return x.xxx_hidden_Slug
	}
	return ""
}

func (x *GetTeamRequest) SetSlug(v string) {
	x.xxx_hidden_Slug = v
}

type GetTeamRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Slug string
}

func (b0 GetTeamRequest_builder) Build() *GetTeamRequest {
	m0 := &GetTeamRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Slug = b.Slug
	return m0
}

type ListTeamsRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit  int64                  `protobuf:"varint,1,opt,name=limit,proto3"`
	xxx_hidden_Offset int64                  `protobuf:"varint,2,opt,name=offset,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListTeamsRequest) Reset() {
	*x = ListTeamsRequest{}
	mi := &file_teams_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsRequest) ProtoMessage() {}

func (x *ListTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTeamsRequest) GetLimit() int64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListTeamsRequest) GetOffset() int64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListTeamsRequest) SetLimit(v int64) {
	x.xxx_hidden_Limit = v
}

func (x *ListTeamsRequest) SetOffset(v int64) {
	x.xxx_hidden_Offset = v
}

type ListTeamsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit  int64
	Offset int64
}

func (b0 ListTeamsRequest_builder) Build() *ListTeamsRequest {
	m0 := &ListTeamsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Offset = b.Offset
	return m0
}

type ListTeamsResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes    *[]*Team               `protobuf:"bytes,1,rep,name=nodes,proto3"`
	xxx_hidden_PageInfo *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListTeamsResponse) Reset() {
	*x = ListTeamsResponse{}
	mi := &file_teams_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsResponse) ProtoMessage() {}

func (x *ListTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTeamsResponse) GetNodes() []*Team {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *ListTeamsResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.xxx_hidden_PageInfo
	}
	return nil
}

func (x *ListTeamsResponse) SetNodes(v []*Team) {
	x.xxx_hidden_Nodes = &v
}

func (x *ListTeamsResponse) SetPageInfo(v *PageInfo) {
	x.xxx_hidden_PageInfo = v
}

func (x *ListTeamsResponse) HasPageInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PageInfo != nil
}

func (x *ListTeamsResponse) ClearPageInfo() {
	x.xxx_hidden_PageInfo = nil
}

type ListTeamsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes    []*Team
	PageInfo *PageInfo
}

func (b0 ListTeamsResponse_builder) Build() *ListTeamsResponse {
	m0 := &ListTeamsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = &b.Nodes
	x.xxx_hidden_PageInfo = b.PageInfo
	return m0
}

type ListTeamGroupsRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit  int64                  `protobuf:"varint,1,opt,name=limit,proto3"`
	xxx_hidden_Offset int64                  `protobuf:"varint,2,opt,name=offset,proto3"`
	xxx_hidden_Slug   string                 `protobuf:"bytes,3,opt,name=slug,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListTeamGroupsRequest) Reset() {
	*x = ListTeamGroupsRequest{}
	mi := &file_teams_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamGroupsRequest) ProtoMessage() {}

func (x *ListTeamGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTeamGroupsRequest) GetLimit() int64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListTeamGroupsRequest) GetOffset() int64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListTeamGroupsRequest) GetSlug() string {
	if x != nil {
		return x.xxx_hidden_Slug
	}
	return ""
}

func (x *ListTeamGroupsRequest) SetLimit(v int64) {
	x.xxx_hidden_Limit = v
}

func (x *ListTeamGroupsRequest) SetOffset(v int64) {
	x.xxx_hidden_Offset = v
}

func (x *ListTeamGroupsRequest) SetSlug(v string) {
	x.xxx_hidden_Slug = v
}

type ListTeamGroupsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit  int64
	Offset int64
	Slug   string
}

func (b0 ListTeamGroupsRequest_builder) Build() *ListTeamGroupsRequest {
	m0 := &ListTeamGroupsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_Slug = b.Slug
	return m0
}

type ListTeamMembersRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit  int64                  `protobuf:"varint,1,opt,name=limit,proto3"`
	xxx_hidden_Offset int64                  `protobuf:"varint,2,opt,name=offset,proto3"`
	xxx_hidden_Slug   string                 `protobuf:"bytes,3,opt,name=slug,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListTeamMembersRequest) Reset() {
	*x = ListTeamMembersRequest{}
	mi := &file_teams_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamMembersRequest) ProtoMessage() {}

func (x *ListTeamMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTeamMembersRequest) GetLimit() int64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListTeamMembersRequest) GetOffset() int64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListTeamMembersRequest) GetSlug() string {
	if x != nil {
		return x.xxx_hidden_Slug
	}
	return ""
}

func (x *ListTeamMembersRequest) SetLimit(v int64) {
	x.xxx_hidden_Limit = v
}

func (x *ListTeamMembersRequest) SetOffset(v int64) {
	x.xxx_hidden_Offset = v
}

func (x *ListTeamMembersRequest) SetSlug(v string) {
	x.xxx_hidden_Slug = v
}

type ListTeamMembersRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit  int64
	Offset int64
	Slug   string
}

func (b0 ListTeamMembersRequest_builder) Build() *ListTeamMembersRequest {
	m0 := &ListTeamMembersRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_Slug = b.Slug
	return m0
}

type ListTeamGroupsResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes    *[]*TeamGroup          `protobuf:"bytes,1,rep,name=nodes,proto3"`
	xxx_hidden_PageInfo *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListTeamGroupsResponse) Reset() {
	*x = ListTeamGroupsResponse{}
	mi := &file_teams_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamGroupsResponse) ProtoMessage() {}

func (x *ListTeamGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTeamGroupsResponse) GetNodes() []*TeamGroup {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *ListTeamGroupsResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.xxx_hidden_PageInfo
	}
	return nil
}

func (x *ListTeamGroupsResponse) SetNodes(v []*TeamGroup) {
	x.xxx_hidden_Nodes = &v
}

func (x *ListTeamGroupsResponse) SetPageInfo(v *PageInfo) {
	x.xxx_hidden_PageInfo = v
}

func (x *ListTeamGroupsResponse) HasPageInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PageInfo != nil
}

func (x *ListTeamGroupsResponse) ClearPageInfo() {
	x.xxx_hidden_PageInfo = nil
}

type ListTeamGroupsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes    []*TeamGroup
	PageInfo *PageInfo
}

func (b0 ListTeamGroupsResponse_builder) Build() *ListTeamGroupsResponse {
	m0 := &ListTeamGroupsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = &b.Nodes
	x.xxx_hidden_PageInfo = b.PageInfo
	return m0
}

type ListTeamMembersResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes    *[]*TeamMember         `protobuf:"bytes,1,rep,name=nodes,proto3"`
	xxx_hidden_PageInfo *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListTeamMembersResponse) Reset() {
	*x = ListTeamMembersResponse{}
	mi := &file_teams_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamMembersResponse) ProtoMessage() {}

func (x *ListTeamMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTeamMembersResponse) GetNodes() []*TeamMember {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *ListTeamMembersResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.xxx_hidden_PageInfo
	}
	return nil
}

func (x *ListTeamMembersResponse) SetNodes(v []*TeamMember) {
	x.xxx_hidden_Nodes = &v
}

func (x *ListTeamMembersResponse) SetPageInfo(v *PageInfo) {
	x.xxx_hidden_PageInfo = v
}

func (x *ListTeamMembersResponse) HasPageInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PageInfo != nil
}

func (x *ListTeamMembersResponse) ClearPageInfo() {
	x.xxx_hidden_PageInfo = nil
}

type ListTeamMembersResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes    []*TeamMember
	PageInfo *PageInfo
}

func (b0 ListTeamMembersResponse_builder) Build() *ListTeamMembersResponse {
	m0 := &ListTeamMembersResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = &b.Nodes
	x.xxx_hidden_PageInfo = b.PageInfo
	return m0
}

type TeamGroup struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Group *Group                 `protobuf:"bytes,1,opt,name=group,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TeamGroup) Reset() {
	*x = TeamGroup{}
	mi := &file_teams_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamGroup) ProtoMessage() {}

func (x *TeamGroup) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TeamGroup) GetGroup() *Group {
	if x != nil {
		return x.xxx_hidden_Group
	}
	return nil
}

func (x *TeamGroup) SetGroup(v *Group) {
	x.xxx_hidden_Group = v
}

func (x *TeamGroup) HasGroup() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Group != nil
}

func (x *TeamGroup) ClearGroup() {
	x.xxx_hidden_Group = nil
}

type TeamGroup_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Group *Group
}

func (b0 TeamGroup_builder) Build() *TeamGroup {
	m0 := &TeamGroup{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Group = b.Group
	return m0
}

type TeamMember struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User *User                  `protobuf:"bytes,1,opt,name=user,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TeamMember) Reset() {
	*x = TeamMember{}
	mi := &file_teams_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMember) ProtoMessage() {}

func (x *TeamMember) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TeamMember) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *TeamMember) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *TeamMember) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *TeamMember) ClearUser() {
	x.xxx_hidden_User = nil
}

type TeamMember_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User *User
}

func (b0 TeamMember_builder) Build() *TeamMember {
	m0 := &TeamMember{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	return m0
}

var File_teams_proto protoreflect.FileDescriptor

var file_teams_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x64,
	0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0c, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x10, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa8, 0x01, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x17, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x14, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01, 0x42, 0x1a,
	0x0a, 0x18, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x22, 0x27, 0x0a, 0x11, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x6c, 0x75, 0x67, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5f, 0x0a, 0x1b, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x22, 0x94, 0x01, 0x0a, 0x1c, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x61, 0x70,
	0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x61, 0x70, 0x6c,
	0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x60, 0x0a, 0x0f, 0x54, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x04,
	0x74, 0x65, 0x61, 0x6d, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x22, 0x40, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x7e, 0x0a, 0x11,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x39, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x59, 0x0a, 0x15,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x22, 0x5a, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x54,
	0x65, 0x61, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x6c, 0x75, 0x67, 0x22, 0x88, 0x01, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x8a,
	0x01, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x61, 0x70, 0x6c,
	0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x65, 0x61, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x12, 0x39, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3c, 0x0a, 0x09, 0x54,
	0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x2f, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x3a, 0x0a, 0x0a, 0x54, 0x65, 0x61,
	0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x32, 0xc9, 0x04, 0x0a, 0x05, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x12,
	0x50, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x22, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x61, 0x70,
	0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x55, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x64, 0x61, 0x70, 0x6c,
	0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x06, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x12, 0x29, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e,
	0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x07, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x73, 0x0a, 0x0c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x2f, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x45,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x30, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d,
	0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x25, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x64, 0x61, 0x70, 0x6c, 0x61, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1a, 0x5a, 0x18, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_teams_proto_goTypes = []any{
	(*Team)(nil),                         // 0: dapla.api.protobuf.Team
	(*DeleteTeamRequest)(nil),            // 1: dapla.api.protobuf.DeleteTeamRequest
	(*DeleteTeamResponse)(nil),           // 2: dapla.api.protobuf.DeleteTeamResponse
	(*ListTeamEnvironmentsRequest)(nil),  // 3: dapla.api.protobuf.ListTeamEnvironmentsRequest
	(*ListTeamEnvironmentsResponse)(nil), // 4: dapla.api.protobuf.ListTeamEnvironmentsResponse
	(*TeamEnvironment)(nil),              // 5: dapla.api.protobuf.TeamEnvironment
	(*GetTeamResponse)(nil),              // 6: dapla.api.protobuf.GetTeamResponse
	(*GetTeamRequest)(nil),               // 7: dapla.api.protobuf.GetTeamRequest
	(*ListTeamsRequest)(nil),             // 8: dapla.api.protobuf.ListTeamsRequest
	(*ListTeamsResponse)(nil),            // 9: dapla.api.protobuf.ListTeamsResponse
	(*ListTeamGroupsRequest)(nil),        // 10: dapla.api.protobuf.ListTeamGroupsRequest
	(*ListTeamMembersRequest)(nil),       // 11: dapla.api.protobuf.ListTeamMembersRequest
	(*ListTeamGroupsResponse)(nil),       // 12: dapla.api.protobuf.ListTeamGroupsResponse
	(*ListTeamMembersResponse)(nil),      // 13: dapla.api.protobuf.ListTeamMembersResponse
	(*TeamGroup)(nil),                    // 14: dapla.api.protobuf.TeamGroup
	(*TeamMember)(nil),                   // 15: dapla.api.protobuf.TeamMember
	(*timestamppb.Timestamp)(nil),        // 16: google.protobuf.Timestamp
	(*PageInfo)(nil),                     // 17: dapla.api.protobuf.PageInfo
	(*Group)(nil),                        // 18: dapla.api.protobuf.Group
	(*User)(nil),                         // 19: dapla.api.protobuf.User
}
var file_teams_proto_depIdxs = []int32{
	16, // 0: dapla.api.protobuf.Team.delete_key_confirmed_at:type_name -> google.protobuf.Timestamp
	5,  // 1: dapla.api.protobuf.ListTeamEnvironmentsResponse.nodes:type_name -> dapla.api.protobuf.TeamEnvironment
	17, // 2: dapla.api.protobuf.ListTeamEnvironmentsResponse.page_info:type_name -> dapla.api.protobuf.PageInfo
	0,  // 3: dapla.api.protobuf.GetTeamResponse.team:type_name -> dapla.api.protobuf.Team
	0,  // 4: dapla.api.protobuf.ListTeamsResponse.nodes:type_name -> dapla.api.protobuf.Team
	17, // 5: dapla.api.protobuf.ListTeamsResponse.page_info:type_name -> dapla.api.protobuf.PageInfo
	14, // 6: dapla.api.protobuf.ListTeamGroupsResponse.nodes:type_name -> dapla.api.protobuf.TeamGroup
	17, // 7: dapla.api.protobuf.ListTeamGroupsResponse.page_info:type_name -> dapla.api.protobuf.PageInfo
	15, // 8: dapla.api.protobuf.ListTeamMembersResponse.nodes:type_name -> dapla.api.protobuf.TeamMember
	17, // 9: dapla.api.protobuf.ListTeamMembersResponse.page_info:type_name -> dapla.api.protobuf.PageInfo
	18, // 10: dapla.api.protobuf.TeamGroup.group:type_name -> dapla.api.protobuf.Group
	19, // 11: dapla.api.protobuf.TeamMember.user:type_name -> dapla.api.protobuf.User
	7,  // 12: dapla.api.protobuf.Teams.Get:input_type -> dapla.api.protobuf.GetTeamRequest
	8,  // 13: dapla.api.protobuf.Teams.List:input_type -> dapla.api.protobuf.ListTeamsRequest
	10, // 14: dapla.api.protobuf.Teams.Groups:input_type -> dapla.api.protobuf.ListTeamGroupsRequest
	11, // 15: dapla.api.protobuf.Teams.Members:input_type -> dapla.api.protobuf.ListTeamMembersRequest
	3,  // 16: dapla.api.protobuf.Teams.Environments:input_type -> dapla.api.protobuf.ListTeamEnvironmentsRequest
	1,  // 17: dapla.api.protobuf.Teams.Delete:input_type -> dapla.api.protobuf.DeleteTeamRequest
	6,  // 18: dapla.api.protobuf.Teams.Get:output_type -> dapla.api.protobuf.GetTeamResponse
	9,  // 19: dapla.api.protobuf.Teams.List:output_type -> dapla.api.protobuf.ListTeamsResponse
	12, // 20: dapla.api.protobuf.Teams.Groups:output_type -> dapla.api.protobuf.ListTeamGroupsResponse
	13, // 21: dapla.api.protobuf.Teams.Members:output_type -> dapla.api.protobuf.ListTeamMembersResponse
	4,  // 22: dapla.api.protobuf.Teams.Environments:output_type -> dapla.api.protobuf.ListTeamEnvironmentsResponse
	2,  // 23: dapla.api.protobuf.Teams.Delete:output_type -> dapla.api.protobuf.DeleteTeamResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_teams_proto_init() }
func file_teams_proto_init() {
	if File_teams_proto != nil {
		return
	}
	file_groups_proto_init()
	file_pagination_proto_init()
	file_users_proto_init()
	file_teams_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_teams_proto_rawDesc), len(file_teams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teams_proto_goTypes,
		DependencyIndexes: file_teams_proto_depIdxs,
		MessageInfos:      file_teams_proto_msgTypes,
	}.Build()
	File_teams_proto = out.File
	file_teams_proto_goTypes = nil
	file_teams_proto_depIdxs = nil
}
