query UserOverview($user: String) @cache(policy: NetworkOnly) {
	user(email: $user) {
		name
		email
		isAdmin
		isSectionManager
		teams(first: 25) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageEnd
				pageStart
				startCursor
				endCursor
				totalCount
			}
			nodes {
				groups {
					name
				}
				team {
					id
					slug
					displayName
					purpose
					section {
						code
						name
						manager {
							name
							email
						}
					}
					members {
						pageInfo {
							totalCount
						}
					}
				}
			}
		}
	}
}
