query TeamOverview($team: Slug!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		id
		displayName
		slug
		purpose
		isManaged
		section {
			id
			code
			name
			manager {
				id
				name
				email
			}
		}
	}
}
