// Code generated by sqlc. DO NOT EDIT.

package repositorysql

import (
	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

type TeamRepository struct {
	TeamSlug         slug.Slug
	GithubRepository string
}
