// Code generated by sqlc. DO NOT EDIT.

package grpcteamsql

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

type Team struct {
	Slug                 slug.Slug
	DisplayName          string
	LastSuccessfulSync   pgtype.Timestamp
	DeleteKeyConfirmedAt pgtype.Timestamptz
	SectionCode          string
	IsManaged            bool
}
