// Code generated by sqlc. DO NOT EDIT.

package grpcteamsql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

type Querier interface {
	Count(ctx context.Context) (int64, error)
	CountGroups(ctx context.Context, teamSlug slug.Slug) (int64, error)
	Delete(ctx context.Context, argSlug slug.Slug) error
	Get(ctx context.Context, argSlug slug.Slug) (*Team, error)
	List(ctx context.Context, arg ListParams) ([]*Team, error)
	ListGroups(ctx context.Context, arg ListGroupsParams) ([]*ListGroupsRow, error)
	SetLastSuccessfulSync(ctx context.Context, argSlug slug.Slug) error
}

var _ Querier = (*Queries)(nil)
