// Code generated by sqlc. DO NOT EDIT.
// source: repos.sql

package grpcartifactregistrysql

import (
	"context"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/slug"
)

const countTeamRepos = `-- name: CountTeamRepos :one
SELECT
    COUNT(*) as total
FROM
    team_artifact_registry_repositories
WHERE
   team_slug = $1::slug
`

func (q *Queries) CountTeamRepos(ctx context.Context, teamSlug slug.Slug) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamRepos, teamSlug)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const get = `-- name: Get :one
SELECT
    team_artifact_registry_repositories.team_slug, team_artifact_registry_repositories.format, team_artifact_registry_repositories.size_bytes
FROM
    team_artifact_registry_repositories
WHERE
    team_slug = $1::slug AND
    format = $2
`

type GetParams struct {
	TeamSlug slug.Slug
	Format   string
}

type GetRow struct {
	TeamArtifactRegistryRepository TeamArtifactRegistryRepository
}

func (q *Queries) Get(ctx context.Context, arg GetParams) (*GetRow, error) {
	row := q.db.QueryRow(ctx, get, arg.TeamSlug, arg.Format)
	var i GetRow
	err := row.Scan(&i.TeamArtifactRegistryRepository.TeamSlug, &i.TeamArtifactRegistryRepository.Format, &i.TeamArtifactRegistryRepository.SizeBytes)
	return &i, err
}

const list = `-- name: List :many
SELECT
    team_artifact_registry_repositories.team_slug, team_artifact_registry_repositories.format, team_artifact_registry_repositories.size_bytes
FROM
    team_artifact_registry_repositories
WHERE
    team_slug = $1::slug
ORDER BY
    format ASC
LIMIT
    $3
OFFSET
    $2
`

type ListParams struct {
	TeamSlug slug.Slug
	Offset   int32
	Limit    int32
}

type ListRow struct {
	TeamArtifactRegistryRepository TeamArtifactRegistryRepository
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]*ListRow, error) {
	rows, err := q.db.Query(ctx, list, arg.TeamSlug, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListRow{}
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(&i.TeamArtifactRegistryRepository.TeamSlug, &i.TeamArtifactRegistryRepository.Format, &i.TeamArtifactRegistryRepository.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
