// Code generated by metago; DO NOT EDIT.

package teambuckets

import (
	"fmt"
	"io"
	"slices"
	"strconv"
	"strings"

	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/model"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/pagination"
)

type (
	TeamBucketConnection = pagination.Connection[*TeamBucket]
	TeamBucketEdge       = pagination.Edge[*TeamBucket]
)

func (TeamBucket) IsNode()       {}
func (TeamBucket) IsSearchNode() {}

type TeamBucketOrder struct {
	Field     TeamBucketOrderField `json:"field"`
	Direction model.OrderDirection `json:"direction"`
}

func (o *TeamBucketOrder) String() string {
	if o == nil {
		return ""
	}

	return strings.ToLower(o.Field.String() + ":" + o.Direction.String())
}

type TeamBucketOrderField string

const (
	TeamBucketOrderFieldName TeamBucketOrderField = "NAME"
	TeamBucketOrderFieldKind TeamBucketOrderField = "KIND"
	TeamBucketOrderFieldEnv  TeamBucketOrderField = "ENV"
	TeamBucketOrderFieldTeam TeamBucketOrderField = "TEAM"
)

var AllTeamBucketOrderFields = []TeamBucketOrderField{
	TeamBucketOrderFieldName,
	TeamBucketOrderFieldKind,
	TeamBucketOrderFieldEnv,
	TeamBucketOrderFieldTeam,
}

func (e TeamBucketOrderField) IsValid() bool {
	return slices.Contains(AllTeamBucketOrderFields, e)
}

func (e TeamBucketOrderField) String() string {
	return string(e)
}

func (e *TeamBucketOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TeamBucketOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TeamBucketOrderField", str)
	}
	return nil
}

func (e TeamBucketOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
