query AllTeams @cache(policy: CacheAndNetwork) {
	me {
		__typename
		... on User {
			teams(first: 1) {
				pageInfo {
					totalCount
				}
			}
		}
	}
	teams(first: 25) @paginate(mode: SinglePage) {
		pageInfo {
			hasNextPage
			hasPreviousPage
			pageEnd
			pageStart
			startCursor
			endCursor
			totalCount
		}
		nodes {
			id
			slug
			displayName
			purpose
			section {
				code
				name
				manager {
					name
					email
				}
			}
			members {
				pageInfo {
					totalCount
				}
			}
			groups {
				nodes {
					name
					category
					suffix
					members {
						nodes {
							user {
								name
								email
							}
						}
					}
				}
			}
		}
	}
}
