// Code generated by sqlc. DO NOT EDIT.
// source: messages.sql

package messagesql

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO
	messages (actor, recipient, status, subject, message)
VALUES
	($1, $2, 'PENDING', $3, $4)
RETURNING
	id, actor, recipient, subject, message, status, created_at
`

type CreateParams struct {
	Actor     string
	Recipient uuid.UUID
	Subject   string
	Message   string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*Message, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Actor,
		arg.Recipient,
		arg.Subject,
		arg.Message,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Recipient,
		&i.Subject,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getByIDs = `-- name: GetByIDs :many
SELECT
	id, actor, recipient, subject, message, status, created_at
FROM
	messages
WHERE
	id = ANY ($1::UUID[])
ORDER BY
	created_at DESC
`

func (q *Queries) GetByIDs(ctx context.Context, ids []uuid.UUID) ([]*Message, error) {
	rows, err := q.db.Query(ctx, getByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Recipient,
			&i.Subject,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByStatus = `-- name: GetByStatus :many
SELECT
	id, actor, recipient, subject, message, status, created_at
FROM
	messages
WHERE
	status = $1
ORDER BY
	created_at DESC
`

func (q *Queries) GetByStatus(ctx context.Context, status string) ([]*Message, error) {
	rows, err := q.db.Query(ctx, getByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Recipient,
			&i.Subject,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
	id, email, name, external_id, admin, section_code, job_title
FROM
	users
WHERE
	email = LOWER($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.ExternalID,
		&i.Admin,
		&i.SectionCode,
		&i.JobTitle,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
	id, email, name, external_id, admin, section_code, job_title
FROM
	users
WHERE
	id = $1::UUID
ORDER BY
	name,
	email ASC
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.ExternalID,
		&i.Admin,
		&i.SectionCode,
		&i.JobTitle,
	)
	return &i, err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE messages
SET
	status = $1
WHERE
	messages.id = $2
RETURNING
	id, actor, recipient, subject, message, status, created_at
`

type UpdateStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (*Message, error) {
	row := q.db.QueryRow(ctx, updateStatus, arg.Status, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Recipient,
		&i.Subject,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const userExists = `-- name: UserExists :one
SELECT
	EXISTS (
		SELECT
			email
		FROM
			users
		WHERE
			email = $1
	)
`

func (q *Queries) UserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
