// Code generated by metago; DO NOT EDIT.

package team

import (
	"fmt"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/model"
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/pagination"
	"io"
	"slices"
	"strconv"
	"strings"
)

type (
	TeamConnection = pagination.Connection[*Team]
	TeamEdge       = pagination.Edge[*Team]
)

func (Team) IsNode()           {}
func (Team) IsSearchNode()     {}
func (Team) IsActivityLogger() {}

type TeamOrder struct {
	Field     TeamOrderField       `json:"field"`
	Direction model.OrderDirection `json:"direction"`
}

func (o *TeamOrder) String() string {
	if o == nil {
		return ""
	}

	return strings.ToLower(o.Field.String() + ":" + o.Direction.String())
}

type TeamOrderField string

const (
	TeamOrderFieldSlug        TeamOrderField = "SLUG"
	TeamOrderFieldSectionCode TeamOrderField = "SECTION_CODE"
)

var AllTeamOrderFields = []TeamOrderField{
	TeamOrderFieldSlug,
	TeamOrderFieldSectionCode,
}

func (e TeamOrderField) IsValid() bool {
	return slices.Contains(AllTeamOrderFields, e)
}

func (e TeamOrderField) String() string {
	return string(e)
}

func (e *TeamOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TeamOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TeamOrderField", str)
	}
	return nil
}

func (e TeamOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type (
	TeamMemberConnection = pagination.Connection[*TeamMember]
	TeamMemberEdge       = pagination.Edge[*TeamMember]
)

type TeamMemberOrder struct {
	Field     TeamMemberOrderField `json:"field"`
	Direction model.OrderDirection `json:"direction"`
}

func (o *TeamMemberOrder) String() string {
	if o == nil {
		return ""
	}

	return strings.ToLower(o.Field.String() + ":" + o.Direction.String())
}

type TeamMemberOrderField string

const (
	TeamMemberOrderFieldName  TeamMemberOrderField = "NAME"
	TeamMemberOrderFieldEmail TeamMemberOrderField = "EMAIL"
)

var AllTeamMemberOrderFields = []TeamMemberOrderField{
	TeamMemberOrderFieldName,
	TeamMemberOrderFieldEmail,
}

func (e TeamMemberOrderField) IsValid() bool {
	return slices.Contains(AllTeamMemberOrderFields, e)
}

func (e TeamMemberOrderField) String() string {
	return string(e)
}

func (e *TeamMemberOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TeamMemberOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TeamMemberOrderField", str)
	}
	return nil
}

func (e TeamMemberOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type (
	TeamGroupConnection = pagination.Connection[*TeamGroup]
	TeamGroupEdge       = pagination.Edge[*TeamGroup]
)
