// Code generated by metago; DO NOT EDIT.

package message

import (
	"github.com/statisticsnorway/dapla-ctrl/api/internal/graph/pagination"
)

type (
	MessageConnection = pagination.Connection[*Message]
	MessageEdge       = pagination.Edge[*Message]
)

func (Message) IsNode() {}
