query TeamSharedBucketAccess($bucket: String!) {
	sharedBucket(name: $bucket) {
		id
		shortName
		users(first: 25) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				startCursor
				endCursor
				totalCount
			}
			nodes {
				team {
					id
					slug
					displayName
				}
				groups {
					id
					name
				}
				user {
					id
					name
					email
					section {
						id
						code
						name
						manager {
							id
							name
							email
						}
					}
				}
			}
		}
	}
}
