name: Build and Deploy Docker Image

on:
  push:
    branches:
      - develop
      - main
  release:
    types: [published]

env:
  REGISTRY: europe-north1-docker.pkg.dev/artifact-registry-5n/dapla-stat-docker/dapla-ctrl
  IMAGE_NAME: dapla-ctrl

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Determine Tag
        id: tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "::set-output name=version::latest"
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            echo "::set-output name=version::${{ github.event.release.tag_name }}"
          else
            echo "::set-output name=version::$(date +'%Y%m%d%H%M%S')"
          fi
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.version }}
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/base-image:latest
