name: Deploy to NAIS prod
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker-build:
    name: Docker Build
    permissions:
      contents: 'read'
      id-token: 'write'
      actions: 'read'
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
      only-config-changed: ${{ steps.changed-files.outputs.changed == 'only-inputs'}}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0

      - run: cd frontend

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 #v5.0.0
        with:
          version: 10
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae #v5.0.5
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.json') }}-

      - name: Install dependencies
        run: pnpm install

      - name: Check what changed
        id: changed-files
        uses: nais/what-changed@bc3dad0463b36ad29044134bba5898f0af73c34c #main
        with:
          files: .nais/nais.yaml
          main-branch-name: 'main'

      - name: Lint
        if: steps.changed-files.outputs.changed != 'only-inputs'
        run: pnpm run lint

      - name: Type check
        if: steps.changed-files.outputs.changed != 'only-inputs'
        run: pnpm run check

      - name: Run tests
        if: steps.changed-files.outputs.changed != 'only-inputs'
        run: pnpm test --run

      - name: Build and push
        if: steps.changed-files.outputs.changed != 'only-inputs'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: dapla-platform

  deploy:
    name: Deploy
    needs: docker-build
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - run: cd frontend

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod
          RESOURCE: .nais/frontend.yaml
          WORKLOAD_IMAGE: ${{ needs.docker-build.outputs.image }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
          WAIT: true
          TELEMETRY: ${{ needs.docker-build.outputs.telemetry }}
