name: Build and push image
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  NAME: dapla-console
jobs:
  build_push:
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      nais-tag: ${{steps.nais-deploy-vars.outputs.nais_tag}}
      nais-cluster: ${{steps.nais-deploy-vars.outputs.cluster}}
      nais-config-path: ${{steps.nais-deploy-vars.outputs.nais_config_path}}
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Type check
        run: pnpm run check
      - name: Run tests
        run: pnpm test --run
      - name: Build and push image and SBOM to Nais OCI registry
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: dapla-platform
      - name: Generate image tags
        id: nais-deploy-vars
        run: |
          echo "nais_tag=${{ steps.docker-push.outputs.tag }}" >> "$GITHUB_OUTPUT"
          echo "cluster=test" >> "$GITHUB_OUTPUT"
          echo "nais_config_path=.nais/dev.yaml" >> "$GITHUB_OUTPUT"

  deploy:
    name: Deploy to NAIS
    needs: build_push
    if: ${{github.event_name != 'pull_request'}} && endsWith(github.ref, '/main')
    uses: ./.github/workflows/deploy.yaml
    with:
      registry: europe-north1-docker.pkg.dev
      repository: dapla-platform
      image-name: dapla-console
      image-tag: ${{ needs.build-push.outputs.nais-tag }}
      cluster: ${{needs.build-push.outputs.nais-cluster}}
      nais-config-path: ${{needs.build-push.outputs.nais-config-path}}
    secrets:
      registry-project: ${{ secrets.NAIS_MANAGEMENT_PROJECT_ID }}
