name: Check pull request
on:
  workflow_dispatch:
jobs:
  test:
    name: Check pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Find go cache dir
        id: go-cache
        run: |
          go version
          # Clear cache dirs to avoid error when restoring
          go clean -cache -modcache
          echo "gocache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      - name: Cache go modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.go-cache.outputs.gocache }}
            ${{ steps.go-cache.outputs.gomodcache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - run: mise run test
      - run: mise run check
      - name: Check code format and run code generators
        run: |
          mise run fmt
          mise run generate
          git diff --exit-code --name-only
