// Code generated by sqlc. DO NOT EDIT.

package messagesql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*Message, error)
	GetByIDs(ctx context.Context, ids []uuid.UUID) ([]*Message, error)
	GetByStatus(ctx context.Context, status string) ([]*Message, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (*User, error)
	List(ctx context.Context, arg ListParams) ([]*ListRow, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (*Message, error)
	UserExists(ctx context.Context, email string) (bool, error)
}

var _ Querier = (*Queries)(nil)
