query UserSharedBucketAccess($user: String!) {
	user(email: $user) {
		sharedBucketsAccess(first: 25) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				startCursor
				endCursor
				totalCount
			}
			nodes {
				name
				shortName
				kind
				env
				team {
					slug
					displayName
				}
			}
		}
	}
}
